package com.airchina.datacenter.spnr.sdk.dao.pojo;

/**
 * Database Table Remarks:
 *   存储MP是哪些乘客使用，是对旅客类型、数量的一个简单统计。
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_Ptcs
 */

import lombok.Data;

/**
 * <p>Class Name: com.airchina.datacenter.spnr.sdk.dao.pojo.MP_PTCsPo </p>
 * <p>Description: 存储MP是哪些乘客使用，是对旅客类型、数量的一个简单统计。 </p>
 * <p>Sample: new MP_PTCsPo() </p>
 * <p>Author: FanShuai </p>
 * <p>Date: 2023/4/20 </p>
 * <p>Modified History: 修改记录，格式(Name) (Version) (Date) (Reason & Contents) </p>
 */
@Data
public class MP_PTCsPo {

    /**
     * 功能说明: SPNR ID,唯一标识
     * 最后修改时间: 2023/04/20
     */
    private String superPnrId;

    /**
     * 功能说明: 最终用户进行的搜索的 ID的唯一标识。
     * 最后修改时间: 2023/04/20
     */
    private String searchId;

    /**
     * 功能说明: 该SPNR内MP唯一序号
     * 最后修改时间: 2023/04/20
     */
    private Long productNumber;

    /**
     * 功能说明: PNR号
     * 最后修改时间: 2023/04/20
     */
    private String pnr;

    /**
     * 功能说明: 旅客类型
     * 最后修改时间: 2023/04/20
     */
    private String ptcCode;

    /**
     * 功能说明: 该类型旅客的数量
     * 最后修改时间: 2023/04/20
     */
    private Long ptcQuantity;

    /**
     * 功能说明: 该类型旅客的OJ_SuperPNR_RPH值,多个旅客以空格间隔
     * 最后修改时间: 2023/04/20
     */
    private String rphList;

}