package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP附加产品：预付费选座、预付费餐食
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_AncillaryProduct
 */
public class MP_AncillaryProductPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   该产品关联的机票PNR
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   该产品是否能单独取消
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.cancelable
     *
     * @mbg.generated
     */
    private String cancelable;

    /**
     * Database Column Remarks:
     *   该产品所关联的类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     * Database Column Remarks:
     *   对应此次调价的业务配置的CODE值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   预定该产品的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.book_date
     *
     * @mbg.generated
     */
    private String bookDate;

    /**
     * Database Column Remarks:
     *   该产品对应航段的出发地
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.origin
     *
     * @mbg.generated
     */
    private String origin;

    /**
     * Database Column Remarks:
     *   该产品对应航段的目的地
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.destination
     *
     * @mbg.generated
     */
    private String destination;

    /**
     * Database Column Remarks:
     *   该产品对应航段的航班号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.flight_number
     *
     * @mbg.generated
     */
    private String flightNumber;

    /**
     * Database Column Remarks:
     *   该产品对应航段的航班序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.flight_segment_rph
     *
     * @mbg.generated
     */
    private String flightSegmentRph;

    /**
     * Database Column Remarks:
     *   该产品对应航段的航班市场方
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.marketing_airline
     *
     * @mbg.generated
     */
    private String marketingAirline;

    /**
     * Database Column Remarks:
     *   产品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.quantity
     *
     * @mbg.generated
     */
    private String quantity;

    /**
     * Database Column Remarks:
     *   该产品能否单独退
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.refundable
     *
     * @mbg.generated
     */
    private String refundable;

    /**
     * Database Column Remarks:
     *   预付费座位特有，预定的座位号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.seat_number
     *
     * @mbg.generated
     */
    private String seatNumber;

    /**
     * Database Column Remarks:
     *   产品类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   该产品是否与机票绑定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.is_seg_bind
     *
     * @mbg.generated
     */
    private String isSegBind;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.traveler_ref_number_rph
     *
     * @mbg.generated
     */
    private String travelerRefNumberRph;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.e_ticket_number
     *
     * @mbg.generated
     */
    private String eTicketNumber;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.ticket_advisory
     *
     * @mbg.generated
     */
    private String ticketAdvisory;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.contact_person_name
     *
     * @mbg.generated
     */
    private String contactPersonName;

    /**
     * Database Column Remarks:
     *   机场
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.airport
     *
     * @mbg.generated
     */
    private String airport;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.booking_channel
     *
     * @mbg.generated
     */
    private String bookingChannel;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.booking_reference_id
     *
     * @mbg.generated
     */
    private String bookingReferenceId;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.booking_status
     *
     * @mbg.generated
     */
    private String bookingStatus;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.cabin_class
     *
     * @mbg.generated
     */
    private String cabinClass;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.carrier
     *
     * @mbg.generated
     */
    private String carrier;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.origin_destination_rph
     *
     * @mbg.generated
     */
    private String originDestinationRph;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.pool_id
     *
     * @mbg.generated
     */
    private String poolId;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.product_sequence
     *
     * @mbg.generated
     */
    private String productSequence;

    /**
     * Database Column Remarks:
     *   不知道啥
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.ref
     *
     * @mbg.generated
     */
    private String ref;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.selling_proposition
     *
     * @mbg.generated
     */
    private String sellingProposition;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.sub_type
     *
     * @mbg.generated
     */
    private String subType;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.supplier_code
     *
     * @mbg.generated
     */
    private String supplierCode;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.supplier_product_code
     *
     * @mbg.generated
     */
    private String supplierProductCode;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.terminal
     *
     * @mbg.generated
     */
    private String terminal;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.cancel_penalty_deadline_offset_time_unit
     *
     * @mbg.generated
     */
    private String cancelPenaltyDeadlineOffsetTimeUnit;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.cancel_penalty_deadline_offset_unit_multiplier
     *
     * @mbg.generated
     */
    private String cancelPenaltyDeadlineOffsetUnitMultiplier;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.amount_percent
     *
     * @mbg.generated
     */
    private String amountPercent;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.loyalty_level
     *
     * @mbg.generated
     */
    private String loyaltyLevel;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.passenger_type_code
     *
     * @mbg.generated
     */
    private String passengerTypeCode;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.base_amount
     *
     * @mbg.generated
     */
    private String baseAmount;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.unit_price
     *
     * @mbg.generated
     */
    private String unitPrice;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.price_adjustments_amount
     *
     * @mbg.generated
     */
    private String priceAdjustmentsAmount;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.total_adjusted
     *
     * @mbg.generated
     */
    private String totalAdjusted;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.total_amount
     *
     * @mbg.generated
     */
    private String totalAmount;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.checkin_offset_drop_time
     *
     * @mbg.generated
     */
    private String checkinOffsetDropTime;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.checkin_offset_time_unit
     *
     * @mbg.generated
     */
    private String checkinOffsetTimeUnit;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.checkin_offset_unit_multiplier
     *
     * @mbg.generated
     */
    private String checkinOffsetUnitMultiplier;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.area_sub_type
     *
     * @mbg.generated
     */
    private String areaSubType;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.area_type
     *
     * @mbg.generated
     */
    private String areaType;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.capacity
     *
     * @mbg.generated
     */
    private String capacity;

    /**
     * Database Column Remarks:
     *   休息室
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.room_code
     *
     * @mbg.generated
     */
    private String roomCode;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.room_opentime_language
     *
     * @mbg.generated
     */
    private String roomOpentimeLanguage;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.descriptive_text
     *
     * @mbg.generated
     */
    private String descriptiveText;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.gate
     *
     * @mbg.generated
     */
    private String gate;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.room_language
     *
     * @mbg.generated
     */
    private String roomLanguage;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.display_name
     *
     * @mbg.generated
     */
    private String displayName;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.airport_name
     *
     * @mbg.generated
     */
    private String airportName;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.short_content
     *
     * @mbg.generated
     */
    private String shortContent;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.location_description
     *
     * @mbg.generated
     */
    private String locationDescription;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.official_name
     *
     * @mbg.generated
     */
    private String officialName;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AncillaryProduct.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.super_pnr_id
     *
     * @return the value of MP_AncillaryProduct.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.super_pnr_id
     *
     * @param superPnrId the value for MP_AncillaryProduct.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.search_id
     *
     * @return the value of MP_AncillaryProduct.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.search_id
     *
     * @param searchId the value for MP_AncillaryProduct.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.product_number
     *
     * @return the value of MP_AncillaryProduct.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.product_number
     *
     * @param productNumber the value for MP_AncillaryProduct.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.pnr
     *
     * @return the value of MP_AncillaryProduct.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.pnr
     *
     * @param pnr the value for MP_AncillaryProduct.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.cancelable
     *
     * @return the value of MP_AncillaryProduct.cancelable
     *
     * @mbg.generated
     */
    public String getCancelable() {
        return cancelable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.cancelable
     *
     * @param cancelable the value for MP_AncillaryProduct.cancelable
     *
     * @mbg.generated
     */
    public void setCancelable(String cancelable) {
        this.cancelable = cancelable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.category
     *
     * @return the value of MP_AncillaryProduct.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.category
     *
     * @param category the value for MP_AncillaryProduct.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.code
     *
     * @return the value of MP_AncillaryProduct.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.code
     *
     * @param code the value for MP_AncillaryProduct.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.book_date
     *
     * @return the value of MP_AncillaryProduct.book_date
     *
     * @mbg.generated
     */
    public String getBookDate() {
        return bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.book_date
     *
     * @param bookDate the value for MP_AncillaryProduct.book_date
     *
     * @mbg.generated
     */
    public void setBookDate(String bookDate) {
        this.bookDate = bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.origin
     *
     * @return the value of MP_AncillaryProduct.origin
     *
     * @mbg.generated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.origin
     *
     * @param origin the value for MP_AncillaryProduct.origin
     *
     * @mbg.generated
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.destination
     *
     * @return the value of MP_AncillaryProduct.destination
     *
     * @mbg.generated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.destination
     *
     * @param destination the value for MP_AncillaryProduct.destination
     *
     * @mbg.generated
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.flight_number
     *
     * @return the value of MP_AncillaryProduct.flight_number
     *
     * @mbg.generated
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.flight_number
     *
     * @param flightNumber the value for MP_AncillaryProduct.flight_number
     *
     * @mbg.generated
     */
    public void setFlightNumber(String flightNumber) {
        this.flightNumber = flightNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.flight_segment_rph
     *
     * @return the value of MP_AncillaryProduct.flight_segment_rph
     *
     * @mbg.generated
     */
    public String getFlightSegmentRph() {
        return flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.flight_segment_rph
     *
     * @param flightSegmentRph the value for MP_AncillaryProduct.flight_segment_rph
     *
     * @mbg.generated
     */
    public void setFlightSegmentRph(String flightSegmentRph) {
        this.flightSegmentRph = flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.marketing_airline
     *
     * @return the value of MP_AncillaryProduct.marketing_airline
     *
     * @mbg.generated
     */
    public String getMarketingAirline() {
        return marketingAirline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.marketing_airline
     *
     * @param marketingAirline the value for MP_AncillaryProduct.marketing_airline
     *
     * @mbg.generated
     */
    public void setMarketingAirline(String marketingAirline) {
        this.marketingAirline = marketingAirline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.quantity
     *
     * @return the value of MP_AncillaryProduct.quantity
     *
     * @mbg.generated
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.quantity
     *
     * @param quantity the value for MP_AncillaryProduct.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.refundable
     *
     * @return the value of MP_AncillaryProduct.refundable
     *
     * @mbg.generated
     */
    public String getRefundable() {
        return refundable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.refundable
     *
     * @param refundable the value for MP_AncillaryProduct.refundable
     *
     * @mbg.generated
     */
    public void setRefundable(String refundable) {
        this.refundable = refundable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.seat_number
     *
     * @return the value of MP_AncillaryProduct.seat_number
     *
     * @mbg.generated
     */
    public String getSeatNumber() {
        return seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.seat_number
     *
     * @param seatNumber the value for MP_AncillaryProduct.seat_number
     *
     * @mbg.generated
     */
    public void setSeatNumber(String seatNumber) {
        this.seatNumber = seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.type
     *
     * @return the value of MP_AncillaryProduct.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.type
     *
     * @param type the value for MP_AncillaryProduct.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.is_seg_bind
     *
     * @return the value of MP_AncillaryProduct.is_seg_bind
     *
     * @mbg.generated
     */
    public String getIsSegBind() {
        return isSegBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.is_seg_bind
     *
     * @param isSegBind the value for MP_AncillaryProduct.is_seg_bind
     *
     * @mbg.generated
     */
    public void setIsSegBind(String isSegBind) {
        this.isSegBind = isSegBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.traveler_ref_number_rph
     *
     * @return the value of MP_AncillaryProduct.traveler_ref_number_rph
     *
     * @mbg.generated
     */
    public String getTravelerRefNumberRph() {
        return travelerRefNumberRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.traveler_ref_number_rph
     *
     * @param travelerRefNumberRph the value for MP_AncillaryProduct.traveler_ref_number_rph
     *
     * @mbg.generated
     */
    public void setTravelerRefNumberRph(String travelerRefNumberRph) {
        this.travelerRefNumberRph = travelerRefNumberRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.e_ticket_number
     *
     * @return the value of MP_AncillaryProduct.e_ticket_number
     *
     * @mbg.generated
     */
    public String geteTicketNumber() {
        return eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.e_ticket_number
     *
     * @param eTicketNumber the value for MP_AncillaryProduct.e_ticket_number
     *
     * @mbg.generated
     */
    public void seteTicketNumber(String eTicketNumber) {
        this.eTicketNumber = eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.ticket_advisory
     *
     * @return the value of MP_AncillaryProduct.ticket_advisory
     *
     * @mbg.generated
     */
    public String getTicketAdvisory() {
        return ticketAdvisory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.ticket_advisory
     *
     * @param ticketAdvisory the value for MP_AncillaryProduct.ticket_advisory
     *
     * @mbg.generated
     */
    public void setTicketAdvisory(String ticketAdvisory) {
        this.ticketAdvisory = ticketAdvisory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.contact_person_name
     *
     * @return the value of MP_AncillaryProduct.contact_person_name
     *
     * @mbg.generated
     */
    public String getContactPersonName() {
        return contactPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.contact_person_name
     *
     * @param contactPersonName the value for MP_AncillaryProduct.contact_person_name
     *
     * @mbg.generated
     */
    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.airport
     *
     * @return the value of MP_AncillaryProduct.airport
     *
     * @mbg.generated
     */
    public String getAirport() {
        return airport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.airport
     *
     * @param airport the value for MP_AncillaryProduct.airport
     *
     * @mbg.generated
     */
    public void setAirport(String airport) {
        this.airport = airport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.booking_channel
     *
     * @return the value of MP_AncillaryProduct.booking_channel
     *
     * @mbg.generated
     */
    public String getBookingChannel() {
        return bookingChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.booking_channel
     *
     * @param bookingChannel the value for MP_AncillaryProduct.booking_channel
     *
     * @mbg.generated
     */
    public void setBookingChannel(String bookingChannel) {
        this.bookingChannel = bookingChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.booking_reference_id
     *
     * @return the value of MP_AncillaryProduct.booking_reference_id
     *
     * @mbg.generated
     */
    public String getBookingReferenceId() {
        return bookingReferenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.booking_reference_id
     *
     * @param bookingReferenceId the value for MP_AncillaryProduct.booking_reference_id
     *
     * @mbg.generated
     */
    public void setBookingReferenceId(String bookingReferenceId) {
        this.bookingReferenceId = bookingReferenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.booking_status
     *
     * @return the value of MP_AncillaryProduct.booking_status
     *
     * @mbg.generated
     */
    public String getBookingStatus() {
        return bookingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.booking_status
     *
     * @param bookingStatus the value for MP_AncillaryProduct.booking_status
     *
     * @mbg.generated
     */
    public void setBookingStatus(String bookingStatus) {
        this.bookingStatus = bookingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.cabin_class
     *
     * @return the value of MP_AncillaryProduct.cabin_class
     *
     * @mbg.generated
     */
    public String getCabinClass() {
        return cabinClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.cabin_class
     *
     * @param cabinClass the value for MP_AncillaryProduct.cabin_class
     *
     * @mbg.generated
     */
    public void setCabinClass(String cabinClass) {
        this.cabinClass = cabinClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.carrier
     *
     * @return the value of MP_AncillaryProduct.carrier
     *
     * @mbg.generated
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.carrier
     *
     * @param carrier the value for MP_AncillaryProduct.carrier
     *
     * @mbg.generated
     */
    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.name
     *
     * @return the value of MP_AncillaryProduct.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.name
     *
     * @param name the value for MP_AncillaryProduct.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.origin_destination_rph
     *
     * @return the value of MP_AncillaryProduct.origin_destination_rph
     *
     * @mbg.generated
     */
    public String getOriginDestinationRph() {
        return originDestinationRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.origin_destination_rph
     *
     * @param originDestinationRph the value for MP_AncillaryProduct.origin_destination_rph
     *
     * @mbg.generated
     */
    public void setOriginDestinationRph(String originDestinationRph) {
        this.originDestinationRph = originDestinationRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.pool_id
     *
     * @return the value of MP_AncillaryProduct.pool_id
     *
     * @mbg.generated
     */
    public String getPoolId() {
        return poolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.pool_id
     *
     * @param poolId the value for MP_AncillaryProduct.pool_id
     *
     * @mbg.generated
     */
    public void setPoolId(String poolId) {
        this.poolId = poolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.product_sequence
     *
     * @return the value of MP_AncillaryProduct.product_sequence
     *
     * @mbg.generated
     */
    public String getProductSequence() {
        return productSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.product_sequence
     *
     * @param productSequence the value for MP_AncillaryProduct.product_sequence
     *
     * @mbg.generated
     */
    public void setProductSequence(String productSequence) {
        this.productSequence = productSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.ref
     *
     * @return the value of MP_AncillaryProduct.ref
     *
     * @mbg.generated
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.ref
     *
     * @param ref the value for MP_AncillaryProduct.ref
     *
     * @mbg.generated
     */
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.selling_proposition
     *
     * @return the value of MP_AncillaryProduct.selling_proposition
     *
     * @mbg.generated
     */
    public String getSellingProposition() {
        return sellingProposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.selling_proposition
     *
     * @param sellingProposition the value for MP_AncillaryProduct.selling_proposition
     *
     * @mbg.generated
     */
    public void setSellingProposition(String sellingProposition) {
        this.sellingProposition = sellingProposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.sub_type
     *
     * @return the value of MP_AncillaryProduct.sub_type
     *
     * @mbg.generated
     */
    public String getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.sub_type
     *
     * @param subType the value for MP_AncillaryProduct.sub_type
     *
     * @mbg.generated
     */
    public void setSubType(String subType) {
        this.subType = subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.supplier_code
     *
     * @return the value of MP_AncillaryProduct.supplier_code
     *
     * @mbg.generated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.supplier_code
     *
     * @param supplierCode the value for MP_AncillaryProduct.supplier_code
     *
     * @mbg.generated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.supplier_product_code
     *
     * @return the value of MP_AncillaryProduct.supplier_product_code
     *
     * @mbg.generated
     */
    public String getSupplierProductCode() {
        return supplierProductCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.supplier_product_code
     *
     * @param supplierProductCode the value for MP_AncillaryProduct.supplier_product_code
     *
     * @mbg.generated
     */
    public void setSupplierProductCode(String supplierProductCode) {
        this.supplierProductCode = supplierProductCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.tag
     *
     * @return the value of MP_AncillaryProduct.tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.tag
     *
     * @param tag the value for MP_AncillaryProduct.tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.terminal
     *
     * @return the value of MP_AncillaryProduct.terminal
     *
     * @mbg.generated
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.terminal
     *
     * @param terminal the value for MP_AncillaryProduct.terminal
     *
     * @mbg.generated
     */
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.cancel_penalty_deadline_offset_time_unit
     *
     * @return the value of MP_AncillaryProduct.cancel_penalty_deadline_offset_time_unit
     *
     * @mbg.generated
     */
    public String getCancelPenaltyDeadlineOffsetTimeUnit() {
        return cancelPenaltyDeadlineOffsetTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.cancel_penalty_deadline_offset_time_unit
     *
     * @param cancelPenaltyDeadlineOffsetTimeUnit the value for MP_AncillaryProduct.cancel_penalty_deadline_offset_time_unit
     *
     * @mbg.generated
     */
    public void setCancelPenaltyDeadlineOffsetTimeUnit(String cancelPenaltyDeadlineOffsetTimeUnit) {
        this.cancelPenaltyDeadlineOffsetTimeUnit = cancelPenaltyDeadlineOffsetTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.cancel_penalty_deadline_offset_unit_multiplier
     *
     * @return the value of MP_AncillaryProduct.cancel_penalty_deadline_offset_unit_multiplier
     *
     * @mbg.generated
     */
    public String getCancelPenaltyDeadlineOffsetUnitMultiplier() {
        return cancelPenaltyDeadlineOffsetUnitMultiplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.cancel_penalty_deadline_offset_unit_multiplier
     *
     * @param cancelPenaltyDeadlineOffsetUnitMultiplier the value for MP_AncillaryProduct.cancel_penalty_deadline_offset_unit_multiplier
     *
     * @mbg.generated
     */
    public void setCancelPenaltyDeadlineOffsetUnitMultiplier(String cancelPenaltyDeadlineOffsetUnitMultiplier) {
        this.cancelPenaltyDeadlineOffsetUnitMultiplier = cancelPenaltyDeadlineOffsetUnitMultiplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.amount_percent
     *
     * @return the value of MP_AncillaryProduct.amount_percent
     *
     * @mbg.generated
     */
    public String getAmountPercent() {
        return amountPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.amount_percent
     *
     * @param amountPercent the value for MP_AncillaryProduct.amount_percent
     *
     * @mbg.generated
     */
    public void setAmountPercent(String amountPercent) {
        this.amountPercent = amountPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.loyalty_level
     *
     * @return the value of MP_AncillaryProduct.loyalty_level
     *
     * @mbg.generated
     */
    public String getLoyaltyLevel() {
        return loyaltyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.loyalty_level
     *
     * @param loyaltyLevel the value for MP_AncillaryProduct.loyalty_level
     *
     * @mbg.generated
     */
    public void setLoyaltyLevel(String loyaltyLevel) {
        this.loyaltyLevel = loyaltyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.passenger_type_code
     *
     * @return the value of MP_AncillaryProduct.passenger_type_code
     *
     * @mbg.generated
     */
    public String getPassengerTypeCode() {
        return passengerTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.passenger_type_code
     *
     * @param passengerTypeCode the value for MP_AncillaryProduct.passenger_type_code
     *
     * @mbg.generated
     */
    public void setPassengerTypeCode(String passengerTypeCode) {
        this.passengerTypeCode = passengerTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.base_amount
     *
     * @return the value of MP_AncillaryProduct.base_amount
     *
     * @mbg.generated
     */
    public String getBaseAmount() {
        return baseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.base_amount
     *
     * @param baseAmount the value for MP_AncillaryProduct.base_amount
     *
     * @mbg.generated
     */
    public void setBaseAmount(String baseAmount) {
        this.baseAmount = baseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.unit_price
     *
     * @return the value of MP_AncillaryProduct.unit_price
     *
     * @mbg.generated
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.unit_price
     *
     * @param unitPrice the value for MP_AncillaryProduct.unit_price
     *
     * @mbg.generated
     */
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.price_adjustments_amount
     *
     * @return the value of MP_AncillaryProduct.price_adjustments_amount
     *
     * @mbg.generated
     */
    public String getPriceAdjustmentsAmount() {
        return priceAdjustmentsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.price_adjustments_amount
     *
     * @param priceAdjustmentsAmount the value for MP_AncillaryProduct.price_adjustments_amount
     *
     * @mbg.generated
     */
    public void setPriceAdjustmentsAmount(String priceAdjustmentsAmount) {
        this.priceAdjustmentsAmount = priceAdjustmentsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.total_adjusted
     *
     * @return the value of MP_AncillaryProduct.total_adjusted
     *
     * @mbg.generated
     */
    public String getTotalAdjusted() {
        return totalAdjusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.total_adjusted
     *
     * @param totalAdjusted the value for MP_AncillaryProduct.total_adjusted
     *
     * @mbg.generated
     */
    public void setTotalAdjusted(String totalAdjusted) {
        this.totalAdjusted = totalAdjusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.total_amount
     *
     * @return the value of MP_AncillaryProduct.total_amount
     *
     * @mbg.generated
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.total_amount
     *
     * @param totalAmount the value for MP_AncillaryProduct.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.checkin_offset_drop_time
     *
     * @return the value of MP_AncillaryProduct.checkin_offset_drop_time
     *
     * @mbg.generated
     */
    public String getCheckinOffsetDropTime() {
        return checkinOffsetDropTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.checkin_offset_drop_time
     *
     * @param checkinOffsetDropTime the value for MP_AncillaryProduct.checkin_offset_drop_time
     *
     * @mbg.generated
     */
    public void setCheckinOffsetDropTime(String checkinOffsetDropTime) {
        this.checkinOffsetDropTime = checkinOffsetDropTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.checkin_offset_time_unit
     *
     * @return the value of MP_AncillaryProduct.checkin_offset_time_unit
     *
     * @mbg.generated
     */
    public String getCheckinOffsetTimeUnit() {
        return checkinOffsetTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.checkin_offset_time_unit
     *
     * @param checkinOffsetTimeUnit the value for MP_AncillaryProduct.checkin_offset_time_unit
     *
     * @mbg.generated
     */
    public void setCheckinOffsetTimeUnit(String checkinOffsetTimeUnit) {
        this.checkinOffsetTimeUnit = checkinOffsetTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.checkin_offset_unit_multiplier
     *
     * @return the value of MP_AncillaryProduct.checkin_offset_unit_multiplier
     *
     * @mbg.generated
     */
    public String getCheckinOffsetUnitMultiplier() {
        return checkinOffsetUnitMultiplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.checkin_offset_unit_multiplier
     *
     * @param checkinOffsetUnitMultiplier the value for MP_AncillaryProduct.checkin_offset_unit_multiplier
     *
     * @mbg.generated
     */
    public void setCheckinOffsetUnitMultiplier(String checkinOffsetUnitMultiplier) {
        this.checkinOffsetUnitMultiplier = checkinOffsetUnitMultiplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.area_sub_type
     *
     * @return the value of MP_AncillaryProduct.area_sub_type
     *
     * @mbg.generated
     */
    public String getAreaSubType() {
        return areaSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.area_sub_type
     *
     * @param areaSubType the value for MP_AncillaryProduct.area_sub_type
     *
     * @mbg.generated
     */
    public void setAreaSubType(String areaSubType) {
        this.areaSubType = areaSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.area_type
     *
     * @return the value of MP_AncillaryProduct.area_type
     *
     * @mbg.generated
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.area_type
     *
     * @param areaType the value for MP_AncillaryProduct.area_type
     *
     * @mbg.generated
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.capacity
     *
     * @return the value of MP_AncillaryProduct.capacity
     *
     * @mbg.generated
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.capacity
     *
     * @param capacity the value for MP_AncillaryProduct.capacity
     *
     * @mbg.generated
     */
    public void setCapacity(String capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.room_code
     *
     * @return the value of MP_AncillaryProduct.room_code
     *
     * @mbg.generated
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.room_code
     *
     * @param roomCode the value for MP_AncillaryProduct.room_code
     *
     * @mbg.generated
     */
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.room_opentime_language
     *
     * @return the value of MP_AncillaryProduct.room_opentime_language
     *
     * @mbg.generated
     */
    public String getRoomOpentimeLanguage() {
        return roomOpentimeLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.room_opentime_language
     *
     * @param roomOpentimeLanguage the value for MP_AncillaryProduct.room_opentime_language
     *
     * @mbg.generated
     */
    public void setRoomOpentimeLanguage(String roomOpentimeLanguage) {
        this.roomOpentimeLanguage = roomOpentimeLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.descriptive_text
     *
     * @return the value of MP_AncillaryProduct.descriptive_text
     *
     * @mbg.generated
     */
    public String getDescriptiveText() {
        return descriptiveText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.descriptive_text
     *
     * @param descriptiveText the value for MP_AncillaryProduct.descriptive_text
     *
     * @mbg.generated
     */
    public void setDescriptiveText(String descriptiveText) {
        this.descriptiveText = descriptiveText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.gate
     *
     * @return the value of MP_AncillaryProduct.gate
     *
     * @mbg.generated
     */
    public String getGate() {
        return gate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.gate
     *
     * @param gate the value for MP_AncillaryProduct.gate
     *
     * @mbg.generated
     */
    public void setGate(String gate) {
        this.gate = gate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.room_language
     *
     * @return the value of MP_AncillaryProduct.room_language
     *
     * @mbg.generated
     */
    public String getRoomLanguage() {
        return roomLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.room_language
     *
     * @param roomLanguage the value for MP_AncillaryProduct.room_language
     *
     * @mbg.generated
     */
    public void setRoomLanguage(String roomLanguage) {
        this.roomLanguage = roomLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.display_name
     *
     * @return the value of MP_AncillaryProduct.display_name
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.display_name
     *
     * @param displayName the value for MP_AncillaryProduct.display_name
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.airport_name
     *
     * @return the value of MP_AncillaryProduct.airport_name
     *
     * @mbg.generated
     */
    public String getAirportName() {
        return airportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.airport_name
     *
     * @param airportName the value for MP_AncillaryProduct.airport_name
     *
     * @mbg.generated
     */
    public void setAirportName(String airportName) {
        this.airportName = airportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.short_content
     *
     * @return the value of MP_AncillaryProduct.short_content
     *
     * @mbg.generated
     */
    public String getShortContent() {
        return shortContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.short_content
     *
     * @param shortContent the value for MP_AncillaryProduct.short_content
     *
     * @mbg.generated
     */
    public void setShortContent(String shortContent) {
        this.shortContent = shortContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.location_description
     *
     * @return the value of MP_AncillaryProduct.location_description
     *
     * @mbg.generated
     */
    public String getLocationDescription() {
        return locationDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.location_description
     *
     * @param locationDescription the value for MP_AncillaryProduct.location_description
     *
     * @mbg.generated
     */
    public void setLocationDescription(String locationDescription) {
        this.locationDescription = locationDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.official_name
     *
     * @return the value of MP_AncillaryProduct.official_name
     *
     * @mbg.generated
     */
    public String getOfficialName() {
        return officialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.official_name
     *
     * @param officialName the value for MP_AncillaryProduct.official_name
     *
     * @mbg.generated
     */
    public void setOfficialName(String officialName) {
        this.officialName = officialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AncillaryProduct.image_url
     *
     * @return the value of MP_AncillaryProduct.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AncillaryProduct.image_url
     *
     * @param imageUrl the value for MP_AncillaryProduct.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}