package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP的票面信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_AirTicketing
 */
public class MP_AirTicketingPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   PNR号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   航段序号，唯一值，不变
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.flight_segment_ref_number
     *
     * @mbg.generated
     */
    private Integer flightSegmentRefNumber;

    /**
     * Database Column Remarks:
     *   是否非自愿退票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.irr
     *
     * @mbg.generated
     */
    private String irr;

    /**
     * Database Column Remarks:
     *   非自愿退票原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.irr_reason
     *
     * @mbg.generated
     */
    private String irrReason;

    /**
     * Database Column Remarks:
     *   出票票台
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.issuing_agent_id
     *
     * @mbg.generated
     */
    private String issuingAgentId;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.item_number
     *
     * @mbg.generated
     */
    private String itemNumber;

    /**
     * Database Column Remarks:
     *   是否出票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.printed
     *
     * @mbg.generated
     */
    private String printed;

    /**
     * Database Column Remarks:
     *   T出票时间，取自主机时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.ticket_time
     *
     * @mbg.generated
     */
    private String ticketTime;

    /**
     * Database Column Remarks:
     *   主机票面状态：OPEN FOR USE 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.ticketing_status
     *
     * @mbg.generated
     */
    private String ticketingStatus;

    /**
     * Database Column Remarks:
     *   旅客在该MP内的序号，非@OJ_Supe
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.traveler_ref_number
     *
     * @mbg.generated
     */
    private String travelerRefNumber;

    /**
     * Database Column Remarks:
     *   票号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.e_ticket_number
     *
     * @mbg.generated
     */
    private String eTicketNumber;

    /**
     * Database Column Remarks:
     *   最晚出票时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.ticket_time_limit
     *
     * @mbg.generated
     */
    private String ticketTimeLimit;

    /**
     * Database Column Remarks:
     *   记录客票有效期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.expiry_date_time
     *
     * @mbg.generated
     */
    private String expiryDateTime;

    /**
     * Database Column Remarks:
     *   客票候补状态,用于表示客票是候补客票还是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.waitlist_status
     *
     * @mbg.generated
     */
    private String waitlistStatus;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.refund_audit_id
     *
     * @mbg.generated
     */
    private String refundAuditId;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.refund_historic
     *
     * @mbg.generated
     */
    private String refundHistoric;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.refund_history_id
     *
     * @mbg.generated
     */
    private String refundHistoryId;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.refund_id
     *
     * @mbg.generated
     */
    private String refundId;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.refund_status
     *
     * @mbg.generated
     */
    private String refundStatus;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirTicketing.refund_e_refund_number
     *
     * @mbg.generated
     */
    private String refundERefundNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.super_pnr_id
     *
     * @return the value of MP_AirTicketing.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.super_pnr_id
     *
     * @param superPnrId the value for MP_AirTicketing.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.search_id
     *
     * @return the value of MP_AirTicketing.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.search_id
     *
     * @param searchId the value for MP_AirTicketing.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.product_number
     *
     * @return the value of MP_AirTicketing.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.product_number
     *
     * @param productNumber the value for MP_AirTicketing.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.pnr
     *
     * @return the value of MP_AirTicketing.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.pnr
     *
     * @param pnr the value for MP_AirTicketing.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.flight_segment_ref_number
     *
     * @return the value of MP_AirTicketing.flight_segment_ref_number
     *
     * @mbg.generated
     */
    public Integer getFlightSegmentRefNumber() {
        return flightSegmentRefNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.flight_segment_ref_number
     *
     * @param flightSegmentRefNumber the value for MP_AirTicketing.flight_segment_ref_number
     *
     * @mbg.generated
     */
    public void setFlightSegmentRefNumber(Integer flightSegmentRefNumber) {
        this.flightSegmentRefNumber = flightSegmentRefNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.irr
     *
     * @return the value of MP_AirTicketing.irr
     *
     * @mbg.generated
     */
    public String getIrr() {
        return irr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.irr
     *
     * @param irr the value for MP_AirTicketing.irr
     *
     * @mbg.generated
     */
    public void setIrr(String irr) {
        this.irr = irr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.irr_reason
     *
     * @return the value of MP_AirTicketing.irr_reason
     *
     * @mbg.generated
     */
    public String getIrrReason() {
        return irrReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.irr_reason
     *
     * @param irrReason the value for MP_AirTicketing.irr_reason
     *
     * @mbg.generated
     */
    public void setIrrReason(String irrReason) {
        this.irrReason = irrReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.issuing_agent_id
     *
     * @return the value of MP_AirTicketing.issuing_agent_id
     *
     * @mbg.generated
     */
    public String getIssuingAgentId() {
        return issuingAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.issuing_agent_id
     *
     * @param issuingAgentId the value for MP_AirTicketing.issuing_agent_id
     *
     * @mbg.generated
     */
    public void setIssuingAgentId(String issuingAgentId) {
        this.issuingAgentId = issuingAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.item_number
     *
     * @return the value of MP_AirTicketing.item_number
     *
     * @mbg.generated
     */
    public String getItemNumber() {
        return itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.item_number
     *
     * @param itemNumber the value for MP_AirTicketing.item_number
     *
     * @mbg.generated
     */
    public void setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.printed
     *
     * @return the value of MP_AirTicketing.printed
     *
     * @mbg.generated
     */
    public String getPrinted() {
        return printed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.printed
     *
     * @param printed the value for MP_AirTicketing.printed
     *
     * @mbg.generated
     */
    public void setPrinted(String printed) {
        this.printed = printed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.ticket_time
     *
     * @return the value of MP_AirTicketing.ticket_time
     *
     * @mbg.generated
     */
    public String getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.ticket_time
     *
     * @param ticketTime the value for MP_AirTicketing.ticket_time
     *
     * @mbg.generated
     */
    public void setTicketTime(String ticketTime) {
        this.ticketTime = ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.ticketing_status
     *
     * @return the value of MP_AirTicketing.ticketing_status
     *
     * @mbg.generated
     */
    public String getTicketingStatus() {
        return ticketingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.ticketing_status
     *
     * @param ticketingStatus the value for MP_AirTicketing.ticketing_status
     *
     * @mbg.generated
     */
    public void setTicketingStatus(String ticketingStatus) {
        this.ticketingStatus = ticketingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.traveler_ref_number
     *
     * @return the value of MP_AirTicketing.traveler_ref_number
     *
     * @mbg.generated
     */
    public String getTravelerRefNumber() {
        return travelerRefNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.traveler_ref_number
     *
     * @param travelerRefNumber the value for MP_AirTicketing.traveler_ref_number
     *
     * @mbg.generated
     */
    public void setTravelerRefNumber(String travelerRefNumber) {
        this.travelerRefNumber = travelerRefNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.e_ticket_number
     *
     * @return the value of MP_AirTicketing.e_ticket_number
     *
     * @mbg.generated
     */
    public String geteTicketNumber() {
        return eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.e_ticket_number
     *
     * @param eTicketNumber the value for MP_AirTicketing.e_ticket_number
     *
     * @mbg.generated
     */
    public void seteTicketNumber(String eTicketNumber) {
        this.eTicketNumber = eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.ticket_time_limit
     *
     * @return the value of MP_AirTicketing.ticket_time_limit
     *
     * @mbg.generated
     */
    public String getTicketTimeLimit() {
        return ticketTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.ticket_time_limit
     *
     * @param ticketTimeLimit the value for MP_AirTicketing.ticket_time_limit
     *
     * @mbg.generated
     */
    public void setTicketTimeLimit(String ticketTimeLimit) {
        this.ticketTimeLimit = ticketTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.expiry_date_time
     *
     * @return the value of MP_AirTicketing.expiry_date_time
     *
     * @mbg.generated
     */
    public String getExpiryDateTime() {
        return expiryDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.expiry_date_time
     *
     * @param expiryDateTime the value for MP_AirTicketing.expiry_date_time
     *
     * @mbg.generated
     */
    public void setExpiryDateTime(String expiryDateTime) {
        this.expiryDateTime = expiryDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.waitlist_status
     *
     * @return the value of MP_AirTicketing.waitlist_status
     *
     * @mbg.generated
     */
    public String getWaitlistStatus() {
        return waitlistStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.waitlist_status
     *
     * @param waitlistStatus the value for MP_AirTicketing.waitlist_status
     *
     * @mbg.generated
     */
    public void setWaitlistStatus(String waitlistStatus) {
        this.waitlistStatus = waitlistStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.refund_audit_id
     *
     * @return the value of MP_AirTicketing.refund_audit_id
     *
     * @mbg.generated
     */
    public String getRefundAuditId() {
        return refundAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.refund_audit_id
     *
     * @param refundAuditId the value for MP_AirTicketing.refund_audit_id
     *
     * @mbg.generated
     */
    public void setRefundAuditId(String refundAuditId) {
        this.refundAuditId = refundAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.refund_historic
     *
     * @return the value of MP_AirTicketing.refund_historic
     *
     * @mbg.generated
     */
    public String getRefundHistoric() {
        return refundHistoric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.refund_historic
     *
     * @param refundHistoric the value for MP_AirTicketing.refund_historic
     *
     * @mbg.generated
     */
    public void setRefundHistoric(String refundHistoric) {
        this.refundHistoric = refundHistoric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.refund_history_id
     *
     * @return the value of MP_AirTicketing.refund_history_id
     *
     * @mbg.generated
     */
    public String getRefundHistoryId() {
        return refundHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.refund_history_id
     *
     * @param refundHistoryId the value for MP_AirTicketing.refund_history_id
     *
     * @mbg.generated
     */
    public void setRefundHistoryId(String refundHistoryId) {
        this.refundHistoryId = refundHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.refund_id
     *
     * @return the value of MP_AirTicketing.refund_id
     *
     * @mbg.generated
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.refund_id
     *
     * @param refundId the value for MP_AirTicketing.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.refund_status
     *
     * @return the value of MP_AirTicketing.refund_status
     *
     * @mbg.generated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.refund_status
     *
     * @param refundStatus the value for MP_AirTicketing.refund_status
     *
     * @mbg.generated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirTicketing.refund_e_refund_number
     *
     * @return the value of MP_AirTicketing.refund_e_refund_number
     *
     * @mbg.generated
     */
    public String getRefundERefundNumber() {
        return refundERefundNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirTicketing.refund_e_refund_number
     *
     * @param refundERefundNumber the value for MP_AirTicketing.refund_e_refund_number
     *
     * @mbg.generated
     */
    public void setRefundERefundNumber(String refundERefundNumber) {
        this.refundERefundNumber = refundERefundNumber;
    }
}