package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储了MP内所有行程的信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_AirAirItinerary
 */
public class MP_AirAirItineraryPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   PNR号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   行程类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.direction_ind
     *
     * @mbg.generated
     */
    private String directionInd;

    /**
     * Database Column Remarks:
     *   确定此行程是否需要 API/TSA 信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.doc_required
     *
     * @mbg.generated
     */
    private String docRequired;

    /**
     * Database Column Remarks:
     *   OD在该MP内的唯一序列号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.od_rph
     *
     * @mbg.generated
     */
    private String odRph;

    /**
     * Database Column Remarks:
     *   OD航司两字码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.od_majority_carrier
     *
     * @mbg.generated
     */
    private String odMajorityCarrier;

    /**
     * Database Column Remarks:
     *   供应商
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.booking_channel
     *
     * @mbg.generated
     */
    private String bookingChannel;

    /**
     * Database Column Remarks:
     *   OD缺口程判断标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.od_openjaw
     *
     * @mbg.generated
     */
    private String odOpenjaw;

    /**
     * Database Column Remarks:
     *   OD航程时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.od_duration
     *
     * @mbg.generated
     */
    private String odDuration;

    /**
     * Database Column Remarks:
     *   OD航程允许的剩余婴儿数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.infant_avail_quantity
     *
     * @mbg.generated
     */
    private Integer infantAvailQuantity;

    /**
     * Database Column Remarks:
     *   通程航班虚拟航班号（特殊需求）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary.marketing_flight_num
     *
     * @mbg.generated
     */
    private String marketingFlightNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.super_pnr_id
     *
     * @return the value of MP_AirAirItinerary.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.super_pnr_id
     *
     * @param superPnrId the value for MP_AirAirItinerary.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.search_id
     *
     * @return the value of MP_AirAirItinerary.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.search_id
     *
     * @param searchId the value for MP_AirAirItinerary.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.product_number
     *
     * @return the value of MP_AirAirItinerary.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.product_number
     *
     * @param productNumber the value for MP_AirAirItinerary.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.pnr
     *
     * @return the value of MP_AirAirItinerary.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.pnr
     *
     * @param pnr the value for MP_AirAirItinerary.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.direction_ind
     *
     * @return the value of MP_AirAirItinerary.direction_ind
     *
     * @mbg.generated
     */
    public String getDirectionInd() {
        return directionInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.direction_ind
     *
     * @param directionInd the value for MP_AirAirItinerary.direction_ind
     *
     * @mbg.generated
     */
    public void setDirectionInd(String directionInd) {
        this.directionInd = directionInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.doc_required
     *
     * @return the value of MP_AirAirItinerary.doc_required
     *
     * @mbg.generated
     */
    public String getDocRequired() {
        return docRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.doc_required
     *
     * @param docRequired the value for MP_AirAirItinerary.doc_required
     *
     * @mbg.generated
     */
    public void setDocRequired(String docRequired) {
        this.docRequired = docRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.od_rph
     *
     * @return the value of MP_AirAirItinerary.od_rph
     *
     * @mbg.generated
     */
    public String getOdRph() {
        return odRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.od_rph
     *
     * @param odRph the value for MP_AirAirItinerary.od_rph
     *
     * @mbg.generated
     */
    public void setOdRph(String odRph) {
        this.odRph = odRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.od_majority_carrier
     *
     * @return the value of MP_AirAirItinerary.od_majority_carrier
     *
     * @mbg.generated
     */
    public String getOdMajorityCarrier() {
        return odMajorityCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.od_majority_carrier
     *
     * @param odMajorityCarrier the value for MP_AirAirItinerary.od_majority_carrier
     *
     * @mbg.generated
     */
    public void setOdMajorityCarrier(String odMajorityCarrier) {
        this.odMajorityCarrier = odMajorityCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.booking_channel
     *
     * @return the value of MP_AirAirItinerary.booking_channel
     *
     * @mbg.generated
     */
    public String getBookingChannel() {
        return bookingChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.booking_channel
     *
     * @param bookingChannel the value for MP_AirAirItinerary.booking_channel
     *
     * @mbg.generated
     */
    public void setBookingChannel(String bookingChannel) {
        this.bookingChannel = bookingChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.od_openjaw
     *
     * @return the value of MP_AirAirItinerary.od_openjaw
     *
     * @mbg.generated
     */
    public String getOdOpenjaw() {
        return odOpenjaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.od_openjaw
     *
     * @param odOpenjaw the value for MP_AirAirItinerary.od_openjaw
     *
     * @mbg.generated
     */
    public void setOdOpenjaw(String odOpenjaw) {
        this.odOpenjaw = odOpenjaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.od_duration
     *
     * @return the value of MP_AirAirItinerary.od_duration
     *
     * @mbg.generated
     */
    public String getOdDuration() {
        return odDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.od_duration
     *
     * @param odDuration the value for MP_AirAirItinerary.od_duration
     *
     * @mbg.generated
     */
    public void setOdDuration(String odDuration) {
        this.odDuration = odDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.infant_avail_quantity
     *
     * @return the value of MP_AirAirItinerary.infant_avail_quantity
     *
     * @mbg.generated
     */
    public Integer getInfantAvailQuantity() {
        return infantAvailQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.infant_avail_quantity
     *
     * @param infantAvailQuantity the value for MP_AirAirItinerary.infant_avail_quantity
     *
     * @mbg.generated
     */
    public void setInfantAvailQuantity(Integer infantAvailQuantity) {
        this.infantAvailQuantity = infantAvailQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary.marketing_flight_num
     *
     * @return the value of MP_AirAirItinerary.marketing_flight_num
     *
     * @mbg.generated
     */
    public String getMarketingFlightNum() {
        return marketingFlightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary.marketing_flight_num
     *
     * @param marketingFlightNum the value for MP_AirAirItinerary.marketing_flight_num
     *
     * @mbg.generated
     */
    public void setMarketingFlightNum(String marketingFlightNum) {
        this.marketingFlightNum = marketingFlightNum;
    }
}