package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储了MP内所有行程航段信息、AV信息、航班经停信息等
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_AirAirItinerary_segment
 */
public class MP_AirAirItinerary_segmentPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   PNR号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   OD在该MP内的唯一序列号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.od_rph
     *
     * @mbg.generated
     */
    private String odRph;

    /**
     * Database Column Remarks:
     *   航段RPH，SPNR内唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.flight_segment_rph
     *
     * @mbg.generated
     */
    private String flightSegmentRph;

    /**
     * Database Column Remarks:
     *   国内/国际
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.info_source
     *
     * @mbg.generated
     */
    private String infoSource;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.mod_type
     *
     * @mbg.generated
     */
    private String modType;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.original_rph
     *
     * @mbg.generated
     */
    private String originalRph;

    /**
     * Database Column Remarks:
     *   出发机场三字码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.dport
     *
     * @mbg.generated
     */
    private String dport;

    /**
     * Database Column Remarks:
     *   标识识别码的上下文，例如 IATA、Lo
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.dport_context
     *
     * @mbg.generated
     */
    private String dportContext;

    /**
     * Database Column Remarks:
     *   出发机场航站楼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.dport_terminal
     *
     * @mbg.generated
     */
    private String dportTerminal;

    /**
     * Database Column Remarks:
     *   出发城市代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.dcity
     *
     * @mbg.generated
     */
    private String dcity;

    /**
     * Database Column Remarks:
     *   出发机场国家码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.dcountry
     *
     * @mbg.generated
     */
    private String dcountry;

    /**
     * Database Column Remarks:
     *   到达机场三字码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.aport
     *
     * @mbg.generated
     */
    private String aport;

    /**
     * Database Column Remarks:
     *   标识识别码的上下文，例如 IATA、AR
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.aport_context
     *
     * @mbg.generated
     */
    private String aportContext;

    /**
     * Database Column Remarks:
     *   到达机场航站楼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.aport_terminal
     *
     * @mbg.generated
     */
    private String aportTerminal;

    /**
     * Database Column Remarks:
     *   到达城市代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.acity
     *
     * @mbg.generated
     */
    private String acity;

    /**
     * Database Column Remarks:
     *   到达机场国家码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.acountry
     *
     * @mbg.generated
     */
    private String acountry;

    /**
     * Database Column Remarks:
     *   航班出发时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.departure_time
     *
     * @mbg.generated
     */
    private String departureTime;

    /**
     * Database Column Remarks:
     *   航班原定出发时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.ori_departure_time
     *
     * @mbg.generated
     */
    private String oriDepartureTime;

    /**
     * Database Column Remarks:
     *   航段到达时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.arrival_time
     *
     * @mbg.generated
     */
    private String arrivalTime;

    /**
     * Database Column Remarks:
     *   航班号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.marketing_flight_no
     *
     * @mbg.generated
     */
    private String marketingFlightNo;

    /**
     * Database Column Remarks:
     *   承运航班号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.operating_flight_no
     *
     * @mbg.generated
     */
    private String operatingFlightNo;

    /**
     * Database Column Remarks:
     *   舱等
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.cabin_code
     *
     * @mbg.generated
     */
    private String cabinCode;

    /**
     * Database Column Remarks:
     *   预定舱位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.subclass
     *
     * @mbg.generated
     */
    private String subclass;

    /**
     * Database Column Remarks:
     *   航段主机状态：RR、NO、OPEN
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   航班飞行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.duration
     *
     * @mbg.generated
     */
    private String duration;

    /**
     * Database Column Remarks:
     *   航程允许的剩余婴儿数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.infant_avail_quantity
     *
     * @mbg.generated
     */
    private String infantAvailQuantity;

    /**
     * Database Column Remarks:
     *   餐食代号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.meal_code
     *
     * @mbg.generated
     */
    private String mealCode;

    /**
     * Database Column Remarks:
     *   分销系统航段类型，多用于国际
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.segment_type
     *
     * @mbg.generated
     */
    private String segmentType;

    /**
     * Database Column Remarks:
     *   是否占座限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.inv_control
     *
     * @mbg.generated
     */
    private String invControl;

    /**
     * Database Column Remarks:
     *   里程积累
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.mileage
     *
     * @mbg.generated
     */
    private String mileage;

    /**
     * Database Column Remarks:
     *   经停次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.stop_quantity
     *
     * @mbg.generated
     */
    private String stopQuantity;

    /**
     * Database Column Remarks:
     *   航班是否可进行预值机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.pre_checkin
     *
     * @mbg.generated
     */
    private String preCheckin;

    /**
     * Database Column Remarks:
     *   是否是线上值机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.online_checkin
     *
     * @mbg.generated
     */
    private String onlineCheckin;

    /**
     * Database Column Remarks:
     *   机型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.air_equip_type
     *
     * @mbg.generated
     */
    private String airEquipType;

    /**
     * Database Column Remarks:
     *   经停地代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.stop_over
     *
     * @mbg.generated
     */
    private String stopOver;

    /**
     * Database Column Remarks:
     *   经停机场
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.stoppoint
     *
     * @mbg.generated
     */
    private String stoppoint;

    /**
     * Database Column Remarks:
     *   经停地点code类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.stop_context
     *
     * @mbg.generated
     */
    private String stopContext;

    /**
     * Database Column Remarks:
     *   经停时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.stop_time
     *
     * @mbg.generated
     */
    private String stopTime;

    /**
     * Database Column Remarks:
     *   AV序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.av_rph
     *
     * @mbg.generated
     */
    private String avRph;

    /**
     * Database Column Remarks:
     *   预订的子舱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.av_subclass
     *
     * @mbg.generated
     */
    private String avSubclass;

    /**
     * Database Column Remarks:
     *   子舱剩余数（不代表实时数值）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.av_subclass_quantity
     *
     * @mbg.generated
     */
    private String avSubclassQuantity;

    /**
     * Database Column Remarks:
     *   子舱舱位开放状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirAirItinerary_segment.av_subclass_status
     *
     * @mbg.generated
     */
    private String avSubclassStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.super_pnr_id
     *
     * @return the value of MP_AirAirItinerary_segment.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.super_pnr_id
     *
     * @param superPnrId the value for MP_AirAirItinerary_segment.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.search_id
     *
     * @return the value of MP_AirAirItinerary_segment.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.search_id
     *
     * @param searchId the value for MP_AirAirItinerary_segment.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.product_number
     *
     * @return the value of MP_AirAirItinerary_segment.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.product_number
     *
     * @param productNumber the value for MP_AirAirItinerary_segment.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.pnr
     *
     * @return the value of MP_AirAirItinerary_segment.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.pnr
     *
     * @param pnr the value for MP_AirAirItinerary_segment.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.od_rph
     *
     * @return the value of MP_AirAirItinerary_segment.od_rph
     *
     * @mbg.generated
     */
    public String getOdRph() {
        return odRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.od_rph
     *
     * @param odRph the value for MP_AirAirItinerary_segment.od_rph
     *
     * @mbg.generated
     */
    public void setOdRph(String odRph) {
        this.odRph = odRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.flight_segment_rph
     *
     * @return the value of MP_AirAirItinerary_segment.flight_segment_rph
     *
     * @mbg.generated
     */
    public String getFlightSegmentRph() {
        return flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.flight_segment_rph
     *
     * @param flightSegmentRph the value for MP_AirAirItinerary_segment.flight_segment_rph
     *
     * @mbg.generated
     */
    public void setFlightSegmentRph(String flightSegmentRph) {
        this.flightSegmentRph = flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.info_source
     *
     * @return the value of MP_AirAirItinerary_segment.info_source
     *
     * @mbg.generated
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.info_source
     *
     * @param infoSource the value for MP_AirAirItinerary_segment.info_source
     *
     * @mbg.generated
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.mod_type
     *
     * @return the value of MP_AirAirItinerary_segment.mod_type
     *
     * @mbg.generated
     */
    public String getModType() {
        return modType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.mod_type
     *
     * @param modType the value for MP_AirAirItinerary_segment.mod_type
     *
     * @mbg.generated
     */
    public void setModType(String modType) {
        this.modType = modType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.original_rph
     *
     * @return the value of MP_AirAirItinerary_segment.original_rph
     *
     * @mbg.generated
     */
    public String getOriginalRph() {
        return originalRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.original_rph
     *
     * @param originalRph the value for MP_AirAirItinerary_segment.original_rph
     *
     * @mbg.generated
     */
    public void setOriginalRph(String originalRph) {
        this.originalRph = originalRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.dport
     *
     * @return the value of MP_AirAirItinerary_segment.dport
     *
     * @mbg.generated
     */
    public String getDport() {
        return dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.dport
     *
     * @param dport the value for MP_AirAirItinerary_segment.dport
     *
     * @mbg.generated
     */
    public void setDport(String dport) {
        this.dport = dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.dport_context
     *
     * @return the value of MP_AirAirItinerary_segment.dport_context
     *
     * @mbg.generated
     */
    public String getDportContext() {
        return dportContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.dport_context
     *
     * @param dportContext the value for MP_AirAirItinerary_segment.dport_context
     *
     * @mbg.generated
     */
    public void setDportContext(String dportContext) {
        this.dportContext = dportContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.dport_terminal
     *
     * @return the value of MP_AirAirItinerary_segment.dport_terminal
     *
     * @mbg.generated
     */
    public String getDportTerminal() {
        return dportTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.dport_terminal
     *
     * @param dportTerminal the value for MP_AirAirItinerary_segment.dport_terminal
     *
     * @mbg.generated
     */
    public void setDportTerminal(String dportTerminal) {
        this.dportTerminal = dportTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.dcity
     *
     * @return the value of MP_AirAirItinerary_segment.dcity
     *
     * @mbg.generated
     */
    public String getDcity() {
        return dcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.dcity
     *
     * @param dcity the value for MP_AirAirItinerary_segment.dcity
     *
     * @mbg.generated
     */
    public void setDcity(String dcity) {
        this.dcity = dcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.dcountry
     *
     * @return the value of MP_AirAirItinerary_segment.dcountry
     *
     * @mbg.generated
     */
    public String getDcountry() {
        return dcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.dcountry
     *
     * @param dcountry the value for MP_AirAirItinerary_segment.dcountry
     *
     * @mbg.generated
     */
    public void setDcountry(String dcountry) {
        this.dcountry = dcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.aport
     *
     * @return the value of MP_AirAirItinerary_segment.aport
     *
     * @mbg.generated
     */
    public String getAport() {
        return aport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.aport
     *
     * @param aport the value for MP_AirAirItinerary_segment.aport
     *
     * @mbg.generated
     */
    public void setAport(String aport) {
        this.aport = aport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.aport_context
     *
     * @return the value of MP_AirAirItinerary_segment.aport_context
     *
     * @mbg.generated
     */
    public String getAportContext() {
        return aportContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.aport_context
     *
     * @param aportContext the value for MP_AirAirItinerary_segment.aport_context
     *
     * @mbg.generated
     */
    public void setAportContext(String aportContext) {
        this.aportContext = aportContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.aport_terminal
     *
     * @return the value of MP_AirAirItinerary_segment.aport_terminal
     *
     * @mbg.generated
     */
    public String getAportTerminal() {
        return aportTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.aport_terminal
     *
     * @param aportTerminal the value for MP_AirAirItinerary_segment.aport_terminal
     *
     * @mbg.generated
     */
    public void setAportTerminal(String aportTerminal) {
        this.aportTerminal = aportTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.acity
     *
     * @return the value of MP_AirAirItinerary_segment.acity
     *
     * @mbg.generated
     */
    public String getAcity() {
        return acity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.acity
     *
     * @param acity the value for MP_AirAirItinerary_segment.acity
     *
     * @mbg.generated
     */
    public void setAcity(String acity) {
        this.acity = acity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.acountry
     *
     * @return the value of MP_AirAirItinerary_segment.acountry
     *
     * @mbg.generated
     */
    public String getAcountry() {
        return acountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.acountry
     *
     * @param acountry the value for MP_AirAirItinerary_segment.acountry
     *
     * @mbg.generated
     */
    public void setAcountry(String acountry) {
        this.acountry = acountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.departure_time
     *
     * @return the value of MP_AirAirItinerary_segment.departure_time
     *
     * @mbg.generated
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.departure_time
     *
     * @param departureTime the value for MP_AirAirItinerary_segment.departure_time
     *
     * @mbg.generated
     */
    public void setDepartureTime(String departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.ori_departure_time
     *
     * @return the value of MP_AirAirItinerary_segment.ori_departure_time
     *
     * @mbg.generated
     */
    public String getOriDepartureTime() {
        return oriDepartureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.ori_departure_time
     *
     * @param oriDepartureTime the value for MP_AirAirItinerary_segment.ori_departure_time
     *
     * @mbg.generated
     */
    public void setOriDepartureTime(String oriDepartureTime) {
        this.oriDepartureTime = oriDepartureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.arrival_time
     *
     * @return the value of MP_AirAirItinerary_segment.arrival_time
     *
     * @mbg.generated
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.arrival_time
     *
     * @param arrivalTime the value for MP_AirAirItinerary_segment.arrival_time
     *
     * @mbg.generated
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.marketing_flight_no
     *
     * @return the value of MP_AirAirItinerary_segment.marketing_flight_no
     *
     * @mbg.generated
     */
    public String getMarketingFlightNo() {
        return marketingFlightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.marketing_flight_no
     *
     * @param marketingFlightNo the value for MP_AirAirItinerary_segment.marketing_flight_no
     *
     * @mbg.generated
     */
    public void setMarketingFlightNo(String marketingFlightNo) {
        this.marketingFlightNo = marketingFlightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.operating_flight_no
     *
     * @return the value of MP_AirAirItinerary_segment.operating_flight_no
     *
     * @mbg.generated
     */
    public String getOperatingFlightNo() {
        return operatingFlightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.operating_flight_no
     *
     * @param operatingFlightNo the value for MP_AirAirItinerary_segment.operating_flight_no
     *
     * @mbg.generated
     */
    public void setOperatingFlightNo(String operatingFlightNo) {
        this.operatingFlightNo = operatingFlightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.cabin_code
     *
     * @return the value of MP_AirAirItinerary_segment.cabin_code
     *
     * @mbg.generated
     */
    public String getCabinCode() {
        return cabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.cabin_code
     *
     * @param cabinCode the value for MP_AirAirItinerary_segment.cabin_code
     *
     * @mbg.generated
     */
    public void setCabinCode(String cabinCode) {
        this.cabinCode = cabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.subclass
     *
     * @return the value of MP_AirAirItinerary_segment.subclass
     *
     * @mbg.generated
     */
    public String getSubclass() {
        return subclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.subclass
     *
     * @param subclass the value for MP_AirAirItinerary_segment.subclass
     *
     * @mbg.generated
     */
    public void setSubclass(String subclass) {
        this.subclass = subclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.status
     *
     * @return the value of MP_AirAirItinerary_segment.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.status
     *
     * @param status the value for MP_AirAirItinerary_segment.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.duration
     *
     * @return the value of MP_AirAirItinerary_segment.duration
     *
     * @mbg.generated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.duration
     *
     * @param duration the value for MP_AirAirItinerary_segment.duration
     *
     * @mbg.generated
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.infant_avail_quantity
     *
     * @return the value of MP_AirAirItinerary_segment.infant_avail_quantity
     *
     * @mbg.generated
     */
    public String getInfantAvailQuantity() {
        return infantAvailQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.infant_avail_quantity
     *
     * @param infantAvailQuantity the value for MP_AirAirItinerary_segment.infant_avail_quantity
     *
     * @mbg.generated
     */
    public void setInfantAvailQuantity(String infantAvailQuantity) {
        this.infantAvailQuantity = infantAvailQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.meal_code
     *
     * @return the value of MP_AirAirItinerary_segment.meal_code
     *
     * @mbg.generated
     */
    public String getMealCode() {
        return mealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.meal_code
     *
     * @param mealCode the value for MP_AirAirItinerary_segment.meal_code
     *
     * @mbg.generated
     */
    public void setMealCode(String mealCode) {
        this.mealCode = mealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.segment_type
     *
     * @return the value of MP_AirAirItinerary_segment.segment_type
     *
     * @mbg.generated
     */
    public String getSegmentType() {
        return segmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.segment_type
     *
     * @param segmentType the value for MP_AirAirItinerary_segment.segment_type
     *
     * @mbg.generated
     */
    public void setSegmentType(String segmentType) {
        this.segmentType = segmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.inv_control
     *
     * @return the value of MP_AirAirItinerary_segment.inv_control
     *
     * @mbg.generated
     */
    public String getInvControl() {
        return invControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.inv_control
     *
     * @param invControl the value for MP_AirAirItinerary_segment.inv_control
     *
     * @mbg.generated
     */
    public void setInvControl(String invControl) {
        this.invControl = invControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.mileage
     *
     * @return the value of MP_AirAirItinerary_segment.mileage
     *
     * @mbg.generated
     */
    public String getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.mileage
     *
     * @param mileage the value for MP_AirAirItinerary_segment.mileage
     *
     * @mbg.generated
     */
    public void setMileage(String mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.stop_quantity
     *
     * @return the value of MP_AirAirItinerary_segment.stop_quantity
     *
     * @mbg.generated
     */
    public String getStopQuantity() {
        return stopQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.stop_quantity
     *
     * @param stopQuantity the value for MP_AirAirItinerary_segment.stop_quantity
     *
     * @mbg.generated
     */
    public void setStopQuantity(String stopQuantity) {
        this.stopQuantity = stopQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.pre_checkin
     *
     * @return the value of MP_AirAirItinerary_segment.pre_checkin
     *
     * @mbg.generated
     */
    public String getPreCheckin() {
        return preCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.pre_checkin
     *
     * @param preCheckin the value for MP_AirAirItinerary_segment.pre_checkin
     *
     * @mbg.generated
     */
    public void setPreCheckin(String preCheckin) {
        this.preCheckin = preCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.online_checkin
     *
     * @return the value of MP_AirAirItinerary_segment.online_checkin
     *
     * @mbg.generated
     */
    public String getOnlineCheckin() {
        return onlineCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.online_checkin
     *
     * @param onlineCheckin the value for MP_AirAirItinerary_segment.online_checkin
     *
     * @mbg.generated
     */
    public void setOnlineCheckin(String onlineCheckin) {
        this.onlineCheckin = onlineCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.air_equip_type
     *
     * @return the value of MP_AirAirItinerary_segment.air_equip_type
     *
     * @mbg.generated
     */
    public String getAirEquipType() {
        return airEquipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.air_equip_type
     *
     * @param airEquipType the value for MP_AirAirItinerary_segment.air_equip_type
     *
     * @mbg.generated
     */
    public void setAirEquipType(String airEquipType) {
        this.airEquipType = airEquipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.stop_over
     *
     * @return the value of MP_AirAirItinerary_segment.stop_over
     *
     * @mbg.generated
     */
    public String getStopOver() {
        return stopOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.stop_over
     *
     * @param stopOver the value for MP_AirAirItinerary_segment.stop_over
     *
     * @mbg.generated
     */
    public void setStopOver(String stopOver) {
        this.stopOver = stopOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.stoppoint
     *
     * @return the value of MP_AirAirItinerary_segment.stoppoint
     *
     * @mbg.generated
     */
    public String getStoppoint() {
        return stoppoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.stoppoint
     *
     * @param stoppoint the value for MP_AirAirItinerary_segment.stoppoint
     *
     * @mbg.generated
     */
    public void setStoppoint(String stoppoint) {
        this.stoppoint = stoppoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.stop_context
     *
     * @return the value of MP_AirAirItinerary_segment.stop_context
     *
     * @mbg.generated
     */
    public String getStopContext() {
        return stopContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.stop_context
     *
     * @param stopContext the value for MP_AirAirItinerary_segment.stop_context
     *
     * @mbg.generated
     */
    public void setStopContext(String stopContext) {
        this.stopContext = stopContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.stop_time
     *
     * @return the value of MP_AirAirItinerary_segment.stop_time
     *
     * @mbg.generated
     */
    public String getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.stop_time
     *
     * @param stopTime the value for MP_AirAirItinerary_segment.stop_time
     *
     * @mbg.generated
     */
    public void setStopTime(String stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.av_rph
     *
     * @return the value of MP_AirAirItinerary_segment.av_rph
     *
     * @mbg.generated
     */
    public String getAvRph() {
        return avRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.av_rph
     *
     * @param avRph the value for MP_AirAirItinerary_segment.av_rph
     *
     * @mbg.generated
     */
    public void setAvRph(String avRph) {
        this.avRph = avRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.av_subclass
     *
     * @return the value of MP_AirAirItinerary_segment.av_subclass
     *
     * @mbg.generated
     */
    public String getAvSubclass() {
        return avSubclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.av_subclass
     *
     * @param avSubclass the value for MP_AirAirItinerary_segment.av_subclass
     *
     * @mbg.generated
     */
    public void setAvSubclass(String avSubclass) {
        this.avSubclass = avSubclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.av_subclass_quantity
     *
     * @return the value of MP_AirAirItinerary_segment.av_subclass_quantity
     *
     * @mbg.generated
     */
    public String getAvSubclassQuantity() {
        return avSubclassQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.av_subclass_quantity
     *
     * @param avSubclassQuantity the value for MP_AirAirItinerary_segment.av_subclass_quantity
     *
     * @mbg.generated
     */
    public void setAvSubclassQuantity(String avSubclassQuantity) {
        this.avSubclassQuantity = avSubclassQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirAirItinerary_segment.av_subclass_status
     *
     * @return the value of MP_AirAirItinerary_segment.av_subclass_status
     *
     * @mbg.generated
     */
    public String getAvSubclassStatus() {
        return avSubclassStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirAirItinerary_segment.av_subclass_status
     *
     * @param avSubclassStatus the value for MP_AirAirItinerary_segment.av_subclass_status
     *
     * @mbg.generated
     */
    public void setAvSubclassStatus(String avSubclassStatus) {
        this.avSubclassStatus = avSubclassStatus;
    }
}