package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP的品牌权益信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_AirPriceInfo_farefamily
 */
public class MP_AirPriceInfo_farefamilyPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   PNR号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   与此票价关联的票价系列代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.fare_family_code
     *
     * @mbg.generated
     */
    private String fareFamilyCode;

    /**
     * Database Column Remarks:
     *   主机返回的运价名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.fare_family_name
     *
     * @mbg.generated
     */
    private String fareFamilyName;

    /**
     * Database Column Remarks:
     *   儿童规则按Y运价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.chd_rule_as_yfare
     *
     * @mbg.generated
     */
    private String chdRuleAsYfare;

    /**
     * Database Column Remarks:
     *   舱等名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.cabin_name
     *
     * @mbg.generated
     */
    private String cabinName;

    /**
     * Database Column Remarks:
     *   改为Open票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_to_open
     *
     * @mbg.generated
     */
    private String changeToOpen;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   国内自助checkin
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.domestic_self_checkin
     *
     * @mbg.generated
     */
    private String domesticSelfCheckin;

    /**
     * Database Column Remarks:
     *   运价基础
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.fare_basis
     *
     * @mbg.generated
     */
    private String fareBasis;

    /**
     * Database Column Remarks:
     *   婴儿规则按Y运价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.inf_rule_as_y_fare
     *
     * @mbg.generated
     */
    private String infRuleAsYFare;

    /**
     * Database Column Remarks:
     *   国际自助checkin
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.intl_self_checkin
     *
     * @mbg.generated
     */
    private String intlSelfCheckin;

    /**
     * Database Column Remarks:
     *   是否可升舱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.upgradable
     *
     * @mbg.generated
     */
    private String upgradable;

    /**
     * Database Column Remarks:
     *   ？
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.user_type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     * Database Column Remarks:
     *   ？
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   航班出发后变更的费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_aft_dept_rate
     *
     * @mbg.generated
     */
    private String changeAftDeptRate;

    /**
     * Database Column Remarks:
     *   航班出发前变更的费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_bef_dept_rate
     *
     * @mbg.generated
     */
    private String changeBefDeptRate;

    /**
     * Database Column Remarks:
     *   航班变更费对应的货币种类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_currency
     *
     * @mbg.generated
     */
    private String changeCurrency;

    /**
     * Database Column Remarks:
     *   航班变更政策适用的旅客类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_psg_type
     *
     * @mbg.generated
     */
    private String changePsgType;

    /**
     * Database Column Remarks:
     *   航班变更费计算的时间偏移量（相对于出发）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_time_threshold
     *
     * @mbg.generated
     */
    private String changeTimeThreshold;

    /**
     * Database Column Remarks:
     *   航班变更费类型（百分比或数值）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_type
     *
     * @mbg.generated
     */
    private String changeType;

    /**
     * Database Column Remarks:
     *   变更自愿还是非自愿
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_voluntary
     *
     * @mbg.generated
     */
    private String changeVoluntary;

    /**
     * Database Column Remarks:
     *   变更政策适用的舱位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_policy_cabin
     *
     * @mbg.generated
     */
    private String changePolicyCabin;

    /**
     * Database Column Remarks:
     *   航班起飞前区间起始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_starttime
     *
     * @mbg.generated
     */
    private String changeStarttime;

    /**
     * Database Column Remarks:
     *   航班起飞前区间结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_endtime
     *
     * @mbg.generated
     */
    private String changeEndtime;

    /**
     * Database Column Remarks:
     *   改期政策RBD
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_policy_rbd
     *
     * @mbg.generated
     */
    private String changePolicyRbd;

    /**
     * Database Column Remarks:
     *   改期限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.change_limit
     *
     * @mbg.generated
     */
    private String changeLimit;

    /**
     * Database Column Remarks:
     *   航班出发后退的费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_aft_dept_rate
     *
     * @mbg.generated
     */
    private String refundAftDeptRate;

    /**
     * Database Column Remarks:
     *   航班出发前退的费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_bef_dept_rate
     *
     * @mbg.generated
     */
    private String refundBefDeptRate;

    /**
     * Database Column Remarks:
     *   退费的货币类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_currency
     *
     * @mbg.generated
     */
    private String refundCurrency;

    /**
     * Database Column Remarks:
     *   退改政策适用的旅客类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_psg_type
     *
     * @mbg.generated
     */
    private String refundPsgType;

    /**
     * Database Column Remarks:
     *   退费计算的时间偏移量（相对于航班出发时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_time_threshold
     *
     * @mbg.generated
     */
    private String refundTimeThreshold;

    /**
     * Database Column Remarks:
     *   退费类型（百分比或数值）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_type
     *
     * @mbg.generated
     */
    private String refundType;

    /**
     * Database Column Remarks:
     *   自愿非自愿标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_voluntary
     *
     * @mbg.generated
     */
    private String refundVoluntary;

    /**
     * Database Column Remarks:
     *   退改政策适用舱位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_policy_cabin
     *
     * @mbg.generated
     */
    private String refundPolicyCabin;

    /**
     * Database Column Remarks:
     *   退票限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_limit
     *
     * @mbg.generated
     */
    private String refundLimit;

    /**
     * Database Column Remarks:
     *   退票乘客类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_eligible
     *
     * @mbg.generated
     */
    private String refundEligible;

    /**
     * Database Column Remarks:
     *   ？
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_loyalty_refund_rule_id
     *
     * @mbg.generated
     */
    private String refundLoyaltyRefundRuleId;

    /**
     * Database Column Remarks:
     *   退票结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_endtime
     *
     * @mbg.generated
     */
    private String refundEndtime;

    /**
     * Database Column Remarks:
     *   退票开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_starttime
     *
     * @mbg.generated
     */
    private String refundStarttime;

    /**
     * Database Column Remarks:
     *   退票政策RBD
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_AirPriceInfo_farefamily.refund_policy_rbd
     *
     * @mbg.generated
     */
    private String refundPolicyRbd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.super_pnr_id
     *
     * @return the value of MP_AirPriceInfo_farefamily.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.super_pnr_id
     *
     * @param superPnrId the value for MP_AirPriceInfo_farefamily.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.search_id
     *
     * @return the value of MP_AirPriceInfo_farefamily.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.search_id
     *
     * @param searchId the value for MP_AirPriceInfo_farefamily.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.product_number
     *
     * @return the value of MP_AirPriceInfo_farefamily.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.product_number
     *
     * @param productNumber the value for MP_AirPriceInfo_farefamily.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.pnr
     *
     * @return the value of MP_AirPriceInfo_farefamily.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.pnr
     *
     * @param pnr the value for MP_AirPriceInfo_farefamily.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.fare_family_code
     *
     * @return the value of MP_AirPriceInfo_farefamily.fare_family_code
     *
     * @mbg.generated
     */
    public String getFareFamilyCode() {
        return fareFamilyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.fare_family_code
     *
     * @param fareFamilyCode the value for MP_AirPriceInfo_farefamily.fare_family_code
     *
     * @mbg.generated
     */
    public void setFareFamilyCode(String fareFamilyCode) {
        this.fareFamilyCode = fareFamilyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.fare_family_name
     *
     * @return the value of MP_AirPriceInfo_farefamily.fare_family_name
     *
     * @mbg.generated
     */
    public String getFareFamilyName() {
        return fareFamilyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.fare_family_name
     *
     * @param fareFamilyName the value for MP_AirPriceInfo_farefamily.fare_family_name
     *
     * @mbg.generated
     */
    public void setFareFamilyName(String fareFamilyName) {
        this.fareFamilyName = fareFamilyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.chd_rule_as_yfare
     *
     * @return the value of MP_AirPriceInfo_farefamily.chd_rule_as_yfare
     *
     * @mbg.generated
     */
    public String getChdRuleAsYfare() {
        return chdRuleAsYfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.chd_rule_as_yfare
     *
     * @param chdRuleAsYfare the value for MP_AirPriceInfo_farefamily.chd_rule_as_yfare
     *
     * @mbg.generated
     */
    public void setChdRuleAsYfare(String chdRuleAsYfare) {
        this.chdRuleAsYfare = chdRuleAsYfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.cabin_name
     *
     * @return the value of MP_AirPriceInfo_farefamily.cabin_name
     *
     * @mbg.generated
     */
    public String getCabinName() {
        return cabinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.cabin_name
     *
     * @param cabinName the value for MP_AirPriceInfo_farefamily.cabin_name
     *
     * @mbg.generated
     */
    public void setCabinName(String cabinName) {
        this.cabinName = cabinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_to_open
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_to_open
     *
     * @mbg.generated
     */
    public String getChangeToOpen() {
        return changeToOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_to_open
     *
     * @param changeToOpen the value for MP_AirPriceInfo_farefamily.change_to_open
     *
     * @mbg.generated
     */
    public void setChangeToOpen(String changeToOpen) {
        this.changeToOpen = changeToOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.description
     *
     * @return the value of MP_AirPriceInfo_farefamily.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.description
     *
     * @param description the value for MP_AirPriceInfo_farefamily.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.domestic_self_checkin
     *
     * @return the value of MP_AirPriceInfo_farefamily.domestic_self_checkin
     *
     * @mbg.generated
     */
    public String getDomesticSelfCheckin() {
        return domesticSelfCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.domestic_self_checkin
     *
     * @param domesticSelfCheckin the value for MP_AirPriceInfo_farefamily.domestic_self_checkin
     *
     * @mbg.generated
     */
    public void setDomesticSelfCheckin(String domesticSelfCheckin) {
        this.domesticSelfCheckin = domesticSelfCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.fare_basis
     *
     * @return the value of MP_AirPriceInfo_farefamily.fare_basis
     *
     * @mbg.generated
     */
    public String getFareBasis() {
        return fareBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.fare_basis
     *
     * @param fareBasis the value for MP_AirPriceInfo_farefamily.fare_basis
     *
     * @mbg.generated
     */
    public void setFareBasis(String fareBasis) {
        this.fareBasis = fareBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.inf_rule_as_y_fare
     *
     * @return the value of MP_AirPriceInfo_farefamily.inf_rule_as_y_fare
     *
     * @mbg.generated
     */
    public String getInfRuleAsYFare() {
        return infRuleAsYFare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.inf_rule_as_y_fare
     *
     * @param infRuleAsYFare the value for MP_AirPriceInfo_farefamily.inf_rule_as_y_fare
     *
     * @mbg.generated
     */
    public void setInfRuleAsYFare(String infRuleAsYFare) {
        this.infRuleAsYFare = infRuleAsYFare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.intl_self_checkin
     *
     * @return the value of MP_AirPriceInfo_farefamily.intl_self_checkin
     *
     * @mbg.generated
     */
    public String getIntlSelfCheckin() {
        return intlSelfCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.intl_self_checkin
     *
     * @param intlSelfCheckin the value for MP_AirPriceInfo_farefamily.intl_self_checkin
     *
     * @mbg.generated
     */
    public void setIntlSelfCheckin(String intlSelfCheckin) {
        this.intlSelfCheckin = intlSelfCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.upgradable
     *
     * @return the value of MP_AirPriceInfo_farefamily.upgradable
     *
     * @mbg.generated
     */
    public String getUpgradable() {
        return upgradable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.upgradable
     *
     * @param upgradable the value for MP_AirPriceInfo_farefamily.upgradable
     *
     * @mbg.generated
     */
    public void setUpgradable(String upgradable) {
        this.upgradable = upgradable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.user_type
     *
     * @return the value of MP_AirPriceInfo_farefamily.user_type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.user_type
     *
     * @param userType the value for MP_AirPriceInfo_farefamily.user_type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.username
     *
     * @return the value of MP_AirPriceInfo_farefamily.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.username
     *
     * @param username the value for MP_AirPriceInfo_farefamily.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_aft_dept_rate
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_aft_dept_rate
     *
     * @mbg.generated
     */
    public String getChangeAftDeptRate() {
        return changeAftDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_aft_dept_rate
     *
     * @param changeAftDeptRate the value for MP_AirPriceInfo_farefamily.change_aft_dept_rate
     *
     * @mbg.generated
     */
    public void setChangeAftDeptRate(String changeAftDeptRate) {
        this.changeAftDeptRate = changeAftDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_bef_dept_rate
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_bef_dept_rate
     *
     * @mbg.generated
     */
    public String getChangeBefDeptRate() {
        return changeBefDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_bef_dept_rate
     *
     * @param changeBefDeptRate the value for MP_AirPriceInfo_farefamily.change_bef_dept_rate
     *
     * @mbg.generated
     */
    public void setChangeBefDeptRate(String changeBefDeptRate) {
        this.changeBefDeptRate = changeBefDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_currency
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_currency
     *
     * @mbg.generated
     */
    public String getChangeCurrency() {
        return changeCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_currency
     *
     * @param changeCurrency the value for MP_AirPriceInfo_farefamily.change_currency
     *
     * @mbg.generated
     */
    public void setChangeCurrency(String changeCurrency) {
        this.changeCurrency = changeCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_psg_type
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_psg_type
     *
     * @mbg.generated
     */
    public String getChangePsgType() {
        return changePsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_psg_type
     *
     * @param changePsgType the value for MP_AirPriceInfo_farefamily.change_psg_type
     *
     * @mbg.generated
     */
    public void setChangePsgType(String changePsgType) {
        this.changePsgType = changePsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_time_threshold
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_time_threshold
     *
     * @mbg.generated
     */
    public String getChangeTimeThreshold() {
        return changeTimeThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_time_threshold
     *
     * @param changeTimeThreshold the value for MP_AirPriceInfo_farefamily.change_time_threshold
     *
     * @mbg.generated
     */
    public void setChangeTimeThreshold(String changeTimeThreshold) {
        this.changeTimeThreshold = changeTimeThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_type
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_type
     *
     * @mbg.generated
     */
    public String getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_type
     *
     * @param changeType the value for MP_AirPriceInfo_farefamily.change_type
     *
     * @mbg.generated
     */
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_voluntary
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_voluntary
     *
     * @mbg.generated
     */
    public String getChangeVoluntary() {
        return changeVoluntary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_voluntary
     *
     * @param changeVoluntary the value for MP_AirPriceInfo_farefamily.change_voluntary
     *
     * @mbg.generated
     */
    public void setChangeVoluntary(String changeVoluntary) {
        this.changeVoluntary = changeVoluntary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_policy_cabin
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_policy_cabin
     *
     * @mbg.generated
     */
    public String getChangePolicyCabin() {
        return changePolicyCabin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_policy_cabin
     *
     * @param changePolicyCabin the value for MP_AirPriceInfo_farefamily.change_policy_cabin
     *
     * @mbg.generated
     */
    public void setChangePolicyCabin(String changePolicyCabin) {
        this.changePolicyCabin = changePolicyCabin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_starttime
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_starttime
     *
     * @mbg.generated
     */
    public String getChangeStarttime() {
        return changeStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_starttime
     *
     * @param changeStarttime the value for MP_AirPriceInfo_farefamily.change_starttime
     *
     * @mbg.generated
     */
    public void setChangeStarttime(String changeStarttime) {
        this.changeStarttime = changeStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_endtime
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_endtime
     *
     * @mbg.generated
     */
    public String getChangeEndtime() {
        return changeEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_endtime
     *
     * @param changeEndtime the value for MP_AirPriceInfo_farefamily.change_endtime
     *
     * @mbg.generated
     */
    public void setChangeEndtime(String changeEndtime) {
        this.changeEndtime = changeEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_policy_rbd
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_policy_rbd
     *
     * @mbg.generated
     */
    public String getChangePolicyRbd() {
        return changePolicyRbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_policy_rbd
     *
     * @param changePolicyRbd the value for MP_AirPriceInfo_farefamily.change_policy_rbd
     *
     * @mbg.generated
     */
    public void setChangePolicyRbd(String changePolicyRbd) {
        this.changePolicyRbd = changePolicyRbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.change_limit
     *
     * @return the value of MP_AirPriceInfo_farefamily.change_limit
     *
     * @mbg.generated
     */
    public String getChangeLimit() {
        return changeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.change_limit
     *
     * @param changeLimit the value for MP_AirPriceInfo_farefamily.change_limit
     *
     * @mbg.generated
     */
    public void setChangeLimit(String changeLimit) {
        this.changeLimit = changeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_aft_dept_rate
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_aft_dept_rate
     *
     * @mbg.generated
     */
    public String getRefundAftDeptRate() {
        return refundAftDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_aft_dept_rate
     *
     * @param refundAftDeptRate the value for MP_AirPriceInfo_farefamily.refund_aft_dept_rate
     *
     * @mbg.generated
     */
    public void setRefundAftDeptRate(String refundAftDeptRate) {
        this.refundAftDeptRate = refundAftDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_bef_dept_rate
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_bef_dept_rate
     *
     * @mbg.generated
     */
    public String getRefundBefDeptRate() {
        return refundBefDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_bef_dept_rate
     *
     * @param refundBefDeptRate the value for MP_AirPriceInfo_farefamily.refund_bef_dept_rate
     *
     * @mbg.generated
     */
    public void setRefundBefDeptRate(String refundBefDeptRate) {
        this.refundBefDeptRate = refundBefDeptRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_currency
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_currency
     *
     * @mbg.generated
     */
    public String getRefundCurrency() {
        return refundCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_currency
     *
     * @param refundCurrency the value for MP_AirPriceInfo_farefamily.refund_currency
     *
     * @mbg.generated
     */
    public void setRefundCurrency(String refundCurrency) {
        this.refundCurrency = refundCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_psg_type
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_psg_type
     *
     * @mbg.generated
     */
    public String getRefundPsgType() {
        return refundPsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_psg_type
     *
     * @param refundPsgType the value for MP_AirPriceInfo_farefamily.refund_psg_type
     *
     * @mbg.generated
     */
    public void setRefundPsgType(String refundPsgType) {
        this.refundPsgType = refundPsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_time_threshold
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_time_threshold
     *
     * @mbg.generated
     */
    public String getRefundTimeThreshold() {
        return refundTimeThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_time_threshold
     *
     * @param refundTimeThreshold the value for MP_AirPriceInfo_farefamily.refund_time_threshold
     *
     * @mbg.generated
     */
    public void setRefundTimeThreshold(String refundTimeThreshold) {
        this.refundTimeThreshold = refundTimeThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_type
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_type
     *
     * @mbg.generated
     */
    public String getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_type
     *
     * @param refundType the value for MP_AirPriceInfo_farefamily.refund_type
     *
     * @mbg.generated
     */
    public void setRefundType(String refundType) {
        this.refundType = refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_voluntary
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_voluntary
     *
     * @mbg.generated
     */
    public String getRefundVoluntary() {
        return refundVoluntary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_voluntary
     *
     * @param refundVoluntary the value for MP_AirPriceInfo_farefamily.refund_voluntary
     *
     * @mbg.generated
     */
    public void setRefundVoluntary(String refundVoluntary) {
        this.refundVoluntary = refundVoluntary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_policy_cabin
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_policy_cabin
     *
     * @mbg.generated
     */
    public String getRefundPolicyCabin() {
        return refundPolicyCabin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_policy_cabin
     *
     * @param refundPolicyCabin the value for MP_AirPriceInfo_farefamily.refund_policy_cabin
     *
     * @mbg.generated
     */
    public void setRefundPolicyCabin(String refundPolicyCabin) {
        this.refundPolicyCabin = refundPolicyCabin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_limit
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_limit
     *
     * @mbg.generated
     */
    public String getRefundLimit() {
        return refundLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_limit
     *
     * @param refundLimit the value for MP_AirPriceInfo_farefamily.refund_limit
     *
     * @mbg.generated
     */
    public void setRefundLimit(String refundLimit) {
        this.refundLimit = refundLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_eligible
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_eligible
     *
     * @mbg.generated
     */
    public String getRefundEligible() {
        return refundEligible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_eligible
     *
     * @param refundEligible the value for MP_AirPriceInfo_farefamily.refund_eligible
     *
     * @mbg.generated
     */
    public void setRefundEligible(String refundEligible) {
        this.refundEligible = refundEligible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_loyalty_refund_rule_id
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_loyalty_refund_rule_id
     *
     * @mbg.generated
     */
    public String getRefundLoyaltyRefundRuleId() {
        return refundLoyaltyRefundRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_loyalty_refund_rule_id
     *
     * @param refundLoyaltyRefundRuleId the value for MP_AirPriceInfo_farefamily.refund_loyalty_refund_rule_id
     *
     * @mbg.generated
     */
    public void setRefundLoyaltyRefundRuleId(String refundLoyaltyRefundRuleId) {
        this.refundLoyaltyRefundRuleId = refundLoyaltyRefundRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_endtime
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_endtime
     *
     * @mbg.generated
     */
    public String getRefundEndtime() {
        return refundEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_endtime
     *
     * @param refundEndtime the value for MP_AirPriceInfo_farefamily.refund_endtime
     *
     * @mbg.generated
     */
    public void setRefundEndtime(String refundEndtime) {
        this.refundEndtime = refundEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_starttime
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_starttime
     *
     * @mbg.generated
     */
    public String getRefundStarttime() {
        return refundStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_starttime
     *
     * @param refundStarttime the value for MP_AirPriceInfo_farefamily.refund_starttime
     *
     * @mbg.generated
     */
    public void setRefundStarttime(String refundStarttime) {
        this.refundStarttime = refundStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_AirPriceInfo_farefamily.refund_policy_rbd
     *
     * @return the value of MP_AirPriceInfo_farefamily.refund_policy_rbd
     *
     * @mbg.generated
     */
    public String getRefundPolicyRbd() {
        return refundPolicyRbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_AirPriceInfo_farefamily.refund_policy_rbd
     *
     * @param refundPolicyRbd the value for MP_AirPriceInfo_farefamily.refund_policy_rbd
     *
     * @mbg.generated
     */
    public void setRefundPolicyRbd(String refundPolicyRbd) {
        this.refundPolicyRbd = refundPolicyRbd;
    }
}