package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP附加产品：预付费行李
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_Baggage
 */
public class MP_BaggagePo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   PNR号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   行李能否单独取消
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.cancelable
     *
     * @mbg.generated
     */
    private String cancelable;

    /**
     * Database Column Remarks:
     *   产品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   该产品能否单独退
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.refundable
     *
     * @mbg.generated
     */
    private String refundable;

    /**
     * Database Column Remarks:
     *   该产品是否与机票绑定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.is_seg_bind
     *
     * @mbg.generated
     */
    private String isSegBind;

    /**
     * Database Column Remarks:
     *   行李相对应的航段出发地
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.departure_code
     *
     * @mbg.generated
     */
    private String departureCode;

    /**
     * Database Column Remarks:
     *   行李相对应的航段到达地
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.arrival_code
     *
     * @mbg.generated
     */
    private String arrivalCode;

    /**
     * Database Column Remarks:
     *   最大重量计量单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.max_weight_unit
     *
     * @mbg.generated
     */
    private String maxWeightUnit;

    /**
     * Database Column Remarks:
     *   购买的行李最大尺寸长度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.max_dimensionsl_cm
     *
     * @mbg.generated
     */
    private String maxDimensionslCm;

    /**
     * Database Column Remarks:
     *   最大尺寸计量单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.max_dimensions_units
     *
     * @mbg.generated
     */
    private String maxDimensionsUnits;

    /**
     * Database Column Remarks:
     *   调整金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.adjusted
     *
     * @mbg.generated
     */
    private String adjusted;

    /**
     * Database Column Remarks:
     *   金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.amt
     *
     * @mbg.generated
     */
    private String amt;

    /**
     * Database Column Remarks:
     *   税前金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.amt_before_tax
     *
     * @mbg.generated
     */
    private String amtBeforeTax;

    /**
     * Database Column Remarks:
     *   货币代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.currency_code
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.decimal_places
     *
     * @mbg.generated
     */
    private String decimalPlaces;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.ori_amt_after_tax
     *
     * @mbg.generated
     */
    private String oriAmtAfterTax;

    /**
     * Database Column Remarks:
     *   原始货币代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.ori_currency_code
     *
     * @mbg.generated
     */
    private String oriCurrencyCode;

    /**
     * Database Column Remarks:
     *   航班号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.flight_segment_number
     *
     * @mbg.generated
     */
    private String flightSegmentNumber;

    /**
     * Database Column Remarks:
     *   对应的航段序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.segment_id_ref
     *
     * @mbg.generated
     */
    private String segmentIdRef;

    /**
     * Database Column Remarks:
     *   对应的旅客序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.traveler_id_ref
     *
     * @mbg.generated
     */
    private String travelerIdRef;

    /**
     * Database Column Remarks:
     *   航段序号，唯一值，不变
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.flight_segment_ref_number
     *
     * @mbg.generated
     */
    private String flightSegmentRefNumber;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.geo_indicator
     *
     * @mbg.generated
     */
    private String geoIndicator;

    /**
     * Database Column Remarks:
     *   销售模式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.sale_model
     *
     * @mbg.generated
     */
    private String saleModel;

    /**
     * Database Column Remarks:
     *   出票时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.ticket_time
     *
     * @mbg.generated
     */
    private String ticketTime;

    /**
     * Database Column Remarks:
     *   出票状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.ticketing_status
     *
     * @mbg.generated
     */
    private String ticketingStatus;

    /**
     * Database Column Remarks:
     *   票号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.e_ticket_number
     *
     * @mbg.generated
     */
    private String eTicketNumber;

    /**
     * Database Column Remarks:
     *   PNR中展示的附加服务明细
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.ticket_advisory
     *
     * @mbg.generated
     */
    private String ticketAdvisory;

    /**
     * Database Column Remarks:
     *   退行李手续费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Baggage.cancel_amount
     *
     * @mbg.generated
     */
    private String cancelAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.super_pnr_id
     *
     * @return the value of MP_Baggage.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.super_pnr_id
     *
     * @param superPnrId the value for MP_Baggage.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.search_id
     *
     * @return the value of MP_Baggage.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.search_id
     *
     * @param searchId the value for MP_Baggage.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.product_number
     *
     * @return the value of MP_Baggage.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.product_number
     *
     * @param productNumber the value for MP_Baggage.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.pnr
     *
     * @return the value of MP_Baggage.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.pnr
     *
     * @param pnr the value for MP_Baggage.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.cancelable
     *
     * @return the value of MP_Baggage.cancelable
     *
     * @mbg.generated
     */
    public String getCancelable() {
        return cancelable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.cancelable
     *
     * @param cancelable the value for MP_Baggage.cancelable
     *
     * @mbg.generated
     */
    public void setCancelable(String cancelable) {
        this.cancelable = cancelable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.quantity
     *
     * @return the value of MP_Baggage.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.quantity
     *
     * @param quantity the value for MP_Baggage.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.refundable
     *
     * @return the value of MP_Baggage.refundable
     *
     * @mbg.generated
     */
    public String getRefundable() {
        return refundable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.refundable
     *
     * @param refundable the value for MP_Baggage.refundable
     *
     * @mbg.generated
     */
    public void setRefundable(String refundable) {
        this.refundable = refundable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.is_seg_bind
     *
     * @return the value of MP_Baggage.is_seg_bind
     *
     * @mbg.generated
     */
    public String getIsSegBind() {
        return isSegBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.is_seg_bind
     *
     * @param isSegBind the value for MP_Baggage.is_seg_bind
     *
     * @mbg.generated
     */
    public void setIsSegBind(String isSegBind) {
        this.isSegBind = isSegBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.departure_code
     *
     * @return the value of MP_Baggage.departure_code
     *
     * @mbg.generated
     */
    public String getDepartureCode() {
        return departureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.departure_code
     *
     * @param departureCode the value for MP_Baggage.departure_code
     *
     * @mbg.generated
     */
    public void setDepartureCode(String departureCode) {
        this.departureCode = departureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.arrival_code
     *
     * @return the value of MP_Baggage.arrival_code
     *
     * @mbg.generated
     */
    public String getArrivalCode() {
        return arrivalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.arrival_code
     *
     * @param arrivalCode the value for MP_Baggage.arrival_code
     *
     * @mbg.generated
     */
    public void setArrivalCode(String arrivalCode) {
        this.arrivalCode = arrivalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.max_weight_unit
     *
     * @return the value of MP_Baggage.max_weight_unit
     *
     * @mbg.generated
     */
    public String getMaxWeightUnit() {
        return maxWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.max_weight_unit
     *
     * @param maxWeightUnit the value for MP_Baggage.max_weight_unit
     *
     * @mbg.generated
     */
    public void setMaxWeightUnit(String maxWeightUnit) {
        this.maxWeightUnit = maxWeightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.max_dimensionsl_cm
     *
     * @return the value of MP_Baggage.max_dimensionsl_cm
     *
     * @mbg.generated
     */
    public String getMaxDimensionslCm() {
        return maxDimensionslCm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.max_dimensionsl_cm
     *
     * @param maxDimensionslCm the value for MP_Baggage.max_dimensionsl_cm
     *
     * @mbg.generated
     */
    public void setMaxDimensionslCm(String maxDimensionslCm) {
        this.maxDimensionslCm = maxDimensionslCm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.max_dimensions_units
     *
     * @return the value of MP_Baggage.max_dimensions_units
     *
     * @mbg.generated
     */
    public String getMaxDimensionsUnits() {
        return maxDimensionsUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.max_dimensions_units
     *
     * @param maxDimensionsUnits the value for MP_Baggage.max_dimensions_units
     *
     * @mbg.generated
     */
    public void setMaxDimensionsUnits(String maxDimensionsUnits) {
        this.maxDimensionsUnits = maxDimensionsUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.adjusted
     *
     * @return the value of MP_Baggage.adjusted
     *
     * @mbg.generated
     */
    public String getAdjusted() {
        return adjusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.adjusted
     *
     * @param adjusted the value for MP_Baggage.adjusted
     *
     * @mbg.generated
     */
    public void setAdjusted(String adjusted) {
        this.adjusted = adjusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.amt
     *
     * @return the value of MP_Baggage.amt
     *
     * @mbg.generated
     */
    public String getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.amt
     *
     * @param amt the value for MP_Baggage.amt
     *
     * @mbg.generated
     */
    public void setAmt(String amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.amt_before_tax
     *
     * @return the value of MP_Baggage.amt_before_tax
     *
     * @mbg.generated
     */
    public String getAmtBeforeTax() {
        return amtBeforeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.amt_before_tax
     *
     * @param amtBeforeTax the value for MP_Baggage.amt_before_tax
     *
     * @mbg.generated
     */
    public void setAmtBeforeTax(String amtBeforeTax) {
        this.amtBeforeTax = amtBeforeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.currency_code
     *
     * @return the value of MP_Baggage.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.currency_code
     *
     * @param currencyCode the value for MP_Baggage.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.decimal_places
     *
     * @return the value of MP_Baggage.decimal_places
     *
     * @mbg.generated
     */
    public String getDecimalPlaces() {
        return decimalPlaces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.decimal_places
     *
     * @param decimalPlaces the value for MP_Baggage.decimal_places
     *
     * @mbg.generated
     */
    public void setDecimalPlaces(String decimalPlaces) {
        this.decimalPlaces = decimalPlaces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.ori_amt_after_tax
     *
     * @return the value of MP_Baggage.ori_amt_after_tax
     *
     * @mbg.generated
     */
    public String getOriAmtAfterTax() {
        return oriAmtAfterTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.ori_amt_after_tax
     *
     * @param oriAmtAfterTax the value for MP_Baggage.ori_amt_after_tax
     *
     * @mbg.generated
     */
    public void setOriAmtAfterTax(String oriAmtAfterTax) {
        this.oriAmtAfterTax = oriAmtAfterTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.ori_currency_code
     *
     * @return the value of MP_Baggage.ori_currency_code
     *
     * @mbg.generated
     */
    public String getOriCurrencyCode() {
        return oriCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.ori_currency_code
     *
     * @param oriCurrencyCode the value for MP_Baggage.ori_currency_code
     *
     * @mbg.generated
     */
    public void setOriCurrencyCode(String oriCurrencyCode) {
        this.oriCurrencyCode = oriCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.flight_segment_number
     *
     * @return the value of MP_Baggage.flight_segment_number
     *
     * @mbg.generated
     */
    public String getFlightSegmentNumber() {
        return flightSegmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.flight_segment_number
     *
     * @param flightSegmentNumber the value for MP_Baggage.flight_segment_number
     *
     * @mbg.generated
     */
    public void setFlightSegmentNumber(String flightSegmentNumber) {
        this.flightSegmentNumber = flightSegmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.segment_id_ref
     *
     * @return the value of MP_Baggage.segment_id_ref
     *
     * @mbg.generated
     */
    public String getSegmentIdRef() {
        return segmentIdRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.segment_id_ref
     *
     * @param segmentIdRef the value for MP_Baggage.segment_id_ref
     *
     * @mbg.generated
     */
    public void setSegmentIdRef(String segmentIdRef) {
        this.segmentIdRef = segmentIdRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.traveler_id_ref
     *
     * @return the value of MP_Baggage.traveler_id_ref
     *
     * @mbg.generated
     */
    public String getTravelerIdRef() {
        return travelerIdRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.traveler_id_ref
     *
     * @param travelerIdRef the value for MP_Baggage.traveler_id_ref
     *
     * @mbg.generated
     */
    public void setTravelerIdRef(String travelerIdRef) {
        this.travelerIdRef = travelerIdRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.flight_segment_ref_number
     *
     * @return the value of MP_Baggage.flight_segment_ref_number
     *
     * @mbg.generated
     */
    public String getFlightSegmentRefNumber() {
        return flightSegmentRefNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.flight_segment_ref_number
     *
     * @param flightSegmentRefNumber the value for MP_Baggage.flight_segment_ref_number
     *
     * @mbg.generated
     */
    public void setFlightSegmentRefNumber(String flightSegmentRefNumber) {
        this.flightSegmentRefNumber = flightSegmentRefNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.geo_indicator
     *
     * @return the value of MP_Baggage.geo_indicator
     *
     * @mbg.generated
     */
    public String getGeoIndicator() {
        return geoIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.geo_indicator
     *
     * @param geoIndicator the value for MP_Baggage.geo_indicator
     *
     * @mbg.generated
     */
    public void setGeoIndicator(String geoIndicator) {
        this.geoIndicator = geoIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.sale_model
     *
     * @return the value of MP_Baggage.sale_model
     *
     * @mbg.generated
     */
    public String getSaleModel() {
        return saleModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.sale_model
     *
     * @param saleModel the value for MP_Baggage.sale_model
     *
     * @mbg.generated
     */
    public void setSaleModel(String saleModel) {
        this.saleModel = saleModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.ticket_time
     *
     * @return the value of MP_Baggage.ticket_time
     *
     * @mbg.generated
     */
    public String getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.ticket_time
     *
     * @param ticketTime the value for MP_Baggage.ticket_time
     *
     * @mbg.generated
     */
    public void setTicketTime(String ticketTime) {
        this.ticketTime = ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.ticketing_status
     *
     * @return the value of MP_Baggage.ticketing_status
     *
     * @mbg.generated
     */
    public String getTicketingStatus() {
        return ticketingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.ticketing_status
     *
     * @param ticketingStatus the value for MP_Baggage.ticketing_status
     *
     * @mbg.generated
     */
    public void setTicketingStatus(String ticketingStatus) {
        this.ticketingStatus = ticketingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.e_ticket_number
     *
     * @return the value of MP_Baggage.e_ticket_number
     *
     * @mbg.generated
     */
    public String geteTicketNumber() {
        return eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.e_ticket_number
     *
     * @param eTicketNumber the value for MP_Baggage.e_ticket_number
     *
     * @mbg.generated
     */
    public void seteTicketNumber(String eTicketNumber) {
        this.eTicketNumber = eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.ticket_advisory
     *
     * @return the value of MP_Baggage.ticket_advisory
     *
     * @mbg.generated
     */
    public String getTicketAdvisory() {
        return ticketAdvisory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.ticket_advisory
     *
     * @param ticketAdvisory the value for MP_Baggage.ticket_advisory
     *
     * @mbg.generated
     */
    public void setTicketAdvisory(String ticketAdvisory) {
        this.ticketAdvisory = ticketAdvisory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Baggage.cancel_amount
     *
     * @return the value of MP_Baggage.cancel_amount
     *
     * @mbg.generated
     */
    public String getCancelAmount() {
        return cancelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Baggage.cancel_amount
     *
     * @param cancelAmount the value for MP_Baggage.cancel_amount
     *
     * @mbg.generated
     */
    public void setCancelAmount(String cancelAmount) {
        this.cancelAmount = cancelAmount;
    }
}