package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP内产品的价格信息汇总
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_Pricing
 */
public class MP_PricingPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   PNR号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   原始价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.pre_amt
     *
     * @mbg.generated
     */
    private String preAmt;

    /**
     * Database Column Remarks:
     *   该笔支付是否让订单出票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.pre_pay_ind
     *
     * @mbg.generated
     */
    private String prePayInd;

    /**
     * Database Column Remarks:
     *   总调价金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.adjustments_amt
     *
     * @mbg.generated
     */
    private String adjustmentsAmt;

    /**
     * Database Column Remarks:
     *   实际总价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.total_amt
     *
     * @mbg.generated
     */
    private String totalAmt;

    /**
     * Database Column Remarks:
     *   扣款信息金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.cancellation_fees
     *
     * @mbg.generated
     */
    private String cancellationFees;

    /**
     * Database Column Remarks:
     *   退票信息金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing.cancellation_refunds
     *
     * @mbg.generated
     */
    private String cancellationRefunds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.super_pnr_id
     *
     * @return the value of MP_Pricing.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.super_pnr_id
     *
     * @param superPnrId the value for MP_Pricing.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.search_id
     *
     * @return the value of MP_Pricing.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.search_id
     *
     * @param searchId the value for MP_Pricing.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.product_number
     *
     * @return the value of MP_Pricing.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.product_number
     *
     * @param productNumber the value for MP_Pricing.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.pnr
     *
     * @return the value of MP_Pricing.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.pnr
     *
     * @param pnr the value for MP_Pricing.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.pre_amt
     *
     * @return the value of MP_Pricing.pre_amt
     *
     * @mbg.generated
     */
    public String getPreAmt() {
        return preAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.pre_amt
     *
     * @param preAmt the value for MP_Pricing.pre_amt
     *
     * @mbg.generated
     */
    public void setPreAmt(String preAmt) {
        this.preAmt = preAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.pre_pay_ind
     *
     * @return the value of MP_Pricing.pre_pay_ind
     *
     * @mbg.generated
     */
    public String getPrePayInd() {
        return prePayInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.pre_pay_ind
     *
     * @param prePayInd the value for MP_Pricing.pre_pay_ind
     *
     * @mbg.generated
     */
    public void setPrePayInd(String prePayInd) {
        this.prePayInd = prePayInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.adjustments_amt
     *
     * @return the value of MP_Pricing.adjustments_amt
     *
     * @mbg.generated
     */
    public String getAdjustmentsAmt() {
        return adjustmentsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.adjustments_amt
     *
     * @param adjustmentsAmt the value for MP_Pricing.adjustments_amt
     *
     * @mbg.generated
     */
    public void setAdjustmentsAmt(String adjustmentsAmt) {
        this.adjustmentsAmt = adjustmentsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.total_amt
     *
     * @return the value of MP_Pricing.total_amt
     *
     * @mbg.generated
     */
    public String getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.total_amt
     *
     * @param totalAmt the value for MP_Pricing.total_amt
     *
     * @mbg.generated
     */
    public void setTotalAmt(String totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.cancellation_fees
     *
     * @return the value of MP_Pricing.cancellation_fees
     *
     * @mbg.generated
     */
    public String getCancellationFees() {
        return cancellationFees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.cancellation_fees
     *
     * @param cancellationFees the value for MP_Pricing.cancellation_fees
     *
     * @mbg.generated
     */
    public void setCancellationFees(String cancellationFees) {
        this.cancellationFees = cancellationFees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing.cancellation_refunds
     *
     * @return the value of MP_Pricing.cancellation_refunds
     *
     * @mbg.generated
     */
    public String getCancellationRefunds() {
        return cancellationRefunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing.cancellation_refunds
     *
     * @param cancellationRefunds the value for MP_Pricing.cancellation_refunds
     *
     * @mbg.generated
     */
    public void setCancellationRefunds(String cancellationRefunds) {
        this.cancellationRefunds = cancellationRefunds;
    }
}