package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP的手续费信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_Pricing_AmendmentFee
 */
public class MP_Pricing_AmendmentFeePo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_AmendmentFee.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_AmendmentFee.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_AmendmentFee.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   PNR号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_AmendmentFee.pnr
     *
     * @mbg.generated
     */
    private String pnr;

    /**
     * Database Column Remarks:
     *   对应此次手续费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_AmendmentFee.amt
     *
     * @mbg.generated
     */
    private Double amt;

    /**
     * Database Column Remarks:
     *   货币单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_AmendmentFee.currency_code
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     * Database Column Remarks:
     *   增加此笔手续费的时间，非北京时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_AmendmentFee.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_AmendmentFee.super_pnr_id
     *
     * @return the value of MP_Pricing_AmendmentFee.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_AmendmentFee.super_pnr_id
     *
     * @param superPnrId the value for MP_Pricing_AmendmentFee.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_AmendmentFee.search_id
     *
     * @return the value of MP_Pricing_AmendmentFee.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_AmendmentFee.search_id
     *
     * @param searchId the value for MP_Pricing_AmendmentFee.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_AmendmentFee.product_number
     *
     * @return the value of MP_Pricing_AmendmentFee.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_AmendmentFee.product_number
     *
     * @param productNumber the value for MP_Pricing_AmendmentFee.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_AmendmentFee.pnr
     *
     * @return the value of MP_Pricing_AmendmentFee.pnr
     *
     * @mbg.generated
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_AmendmentFee.pnr
     *
     * @param pnr the value for MP_Pricing_AmendmentFee.pnr
     *
     * @mbg.generated
     */
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_AmendmentFee.amt
     *
     * @return the value of MP_Pricing_AmendmentFee.amt
     *
     * @mbg.generated
     */
    public Double getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_AmendmentFee.amt
     *
     * @param amt the value for MP_Pricing_AmendmentFee.amt
     *
     * @mbg.generated
     */
    public void setAmt(Double amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_AmendmentFee.currency_code
     *
     * @return the value of MP_Pricing_AmendmentFee.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_AmendmentFee.currency_code
     *
     * @param currencyCode the value for MP_Pricing_AmendmentFee.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_AmendmentFee.date
     *
     * @return the value of MP_Pricing_AmendmentFee.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_AmendmentFee.date
     *
     * @param date the value for MP_Pricing_AmendmentFee.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date;
    }
}