package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP产品的扣款信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MP_Pricing_CancellationFees
 */
public class MP_Pricing_CancellationFeesPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   此次扣款对应的旅客序号。@OJ_Supe
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.oj_super_pnr_rph
     *
     * @mbg.generated
     */
    private String ojSuperPnrRph;

    /**
     * Database Column Remarks:
     *   此次扣款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.amt
     *
     * @mbg.generated
     */
    private Double amt;

    /**
     * Database Column Remarks:
     *   货币单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.currency_code
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     * Database Column Remarks:
     *   添加此CancellationFee的A
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.audit_id
     *
     * @mbg.generated
     */
    private String auditId;

    /**
     * Database Column Remarks:
     *   此次扣款对应的航段序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.flight_segment_rph
     *
     * @mbg.generated
     */
    private String flightSegmentRph;

    /**
     * Database Column Remarks:
     *   添加此节点的时间，非北京时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.added_date
     *
     * @mbg.generated
     */
    private String addedDate;

    /**
     * Database Column Remarks:
     *   如果此产品是另一个产品的附加产品，则它包
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.master_product_number
     *
     * @mbg.generated
     */
    private String masterProductNumber;

    /**
     * Database Column Remarks:
     *   费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.percentage
     *
     * @mbg.generated
     */
    private String percentage;

    /**
     * Database Column Remarks:
     *   当前CancellationFee是在M
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.cancel_product_number
     *
     * @mbg.generated
     */
    private String cancelProductNumber;

    /**
     * Database Column Remarks:
     *   产品类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     * Database Column Remarks:
     *   渠道名或ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.agent
     *
     * @mbg.generated
     */
    private String agent;

    /**
     * Database Column Remarks:
     *   处理该次请求的服务器IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.agent_url
     *
     * @mbg.generated
     */
    private String agentUrl;

    /**
     * Database Column Remarks:
     *   渠道名或ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MP_Pricing_CancellationFees.agency
     *
     * @mbg.generated
     */
    private String agency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.super_pnr_id
     *
     * @return the value of MP_Pricing_CancellationFees.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.super_pnr_id
     *
     * @param superPnrId the value for MP_Pricing_CancellationFees.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.search_id
     *
     * @return the value of MP_Pricing_CancellationFees.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.search_id
     *
     * @param searchId the value for MP_Pricing_CancellationFees.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.product_number
     *
     * @return the value of MP_Pricing_CancellationFees.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.product_number
     *
     * @param productNumber the value for MP_Pricing_CancellationFees.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.oj_super_pnr_rph
     *
     * @return the value of MP_Pricing_CancellationFees.oj_super_pnr_rph
     *
     * @mbg.generated
     */
    public String getOjSuperPnrRph() {
        return ojSuperPnrRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.oj_super_pnr_rph
     *
     * @param ojSuperPnrRph the value for MP_Pricing_CancellationFees.oj_super_pnr_rph
     *
     * @mbg.generated
     */
    public void setOjSuperPnrRph(String ojSuperPnrRph) {
        this.ojSuperPnrRph = ojSuperPnrRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.amt
     *
     * @return the value of MP_Pricing_CancellationFees.amt
     *
     * @mbg.generated
     */
    public Double getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.amt
     *
     * @param amt the value for MP_Pricing_CancellationFees.amt
     *
     * @mbg.generated
     */
    public void setAmt(Double amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.currency_code
     *
     * @return the value of MP_Pricing_CancellationFees.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.currency_code
     *
     * @param currencyCode the value for MP_Pricing_CancellationFees.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.audit_id
     *
     * @return the value of MP_Pricing_CancellationFees.audit_id
     *
     * @mbg.generated
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.audit_id
     *
     * @param auditId the value for MP_Pricing_CancellationFees.audit_id
     *
     * @mbg.generated
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.flight_segment_rph
     *
     * @return the value of MP_Pricing_CancellationFees.flight_segment_rph
     *
     * @mbg.generated
     */
    public String getFlightSegmentRph() {
        return flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.flight_segment_rph
     *
     * @param flightSegmentRph the value for MP_Pricing_CancellationFees.flight_segment_rph
     *
     * @mbg.generated
     */
    public void setFlightSegmentRph(String flightSegmentRph) {
        this.flightSegmentRph = flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.added_date
     *
     * @return the value of MP_Pricing_CancellationFees.added_date
     *
     * @mbg.generated
     */
    public String getAddedDate() {
        return addedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.added_date
     *
     * @param addedDate the value for MP_Pricing_CancellationFees.added_date
     *
     * @mbg.generated
     */
    public void setAddedDate(String addedDate) {
        this.addedDate = addedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.master_product_number
     *
     * @return the value of MP_Pricing_CancellationFees.master_product_number
     *
     * @mbg.generated
     */
    public String getMasterProductNumber() {
        return masterProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.master_product_number
     *
     * @param masterProductNumber the value for MP_Pricing_CancellationFees.master_product_number
     *
     * @mbg.generated
     */
    public void setMasterProductNumber(String masterProductNumber) {
        this.masterProductNumber = masterProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.percentage
     *
     * @return the value of MP_Pricing_CancellationFees.percentage
     *
     * @mbg.generated
     */
    public String getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.percentage
     *
     * @param percentage the value for MP_Pricing_CancellationFees.percentage
     *
     * @mbg.generated
     */
    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.cancel_product_number
     *
     * @return the value of MP_Pricing_CancellationFees.cancel_product_number
     *
     * @mbg.generated
     */
    public String getCancelProductNumber() {
        return cancelProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.cancel_product_number
     *
     * @param cancelProductNumber the value for MP_Pricing_CancellationFees.cancel_product_number
     *
     * @mbg.generated
     */
    public void setCancelProductNumber(String cancelProductNumber) {
        this.cancelProductNumber = cancelProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.product_type
     *
     * @return the value of MP_Pricing_CancellationFees.product_type
     *
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.product_type
     *
     * @param productType the value for MP_Pricing_CancellationFees.product_type
     *
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.agent
     *
     * @return the value of MP_Pricing_CancellationFees.agent
     *
     * @mbg.generated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.agent
     *
     * @param agent the value for MP_Pricing_CancellationFees.agent
     *
     * @mbg.generated
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.agent_url
     *
     * @return the value of MP_Pricing_CancellationFees.agent_url
     *
     * @mbg.generated
     */
    public String getAgentUrl() {
        return agentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.agent_url
     *
     * @param agentUrl the value for MP_Pricing_CancellationFees.agent_url
     *
     * @mbg.generated
     */
    public void setAgentUrl(String agentUrl) {
        this.agentUrl = agentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MP_Pricing_CancellationFees.agency
     *
     * @return the value of MP_Pricing_CancellationFees.agency
     *
     * @mbg.generated
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MP_Pricing_CancellationFees.agency
     *
     * @param agency the value for MP_Pricing_CancellationFees.agency
     *
     * @mbg.generated
     */
    public void setAgency(String agency) {
        this.agency = agency;
    }
}