package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储订单的POS信息（在SPNR内有且仅有一个，其节点用于表明该SPNR所属的航空公司、预定渠道等。）
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Spnr_POS
 */
public class Spnr_POSPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   所属航司两字码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.airline_vendor_id
     *
     * @mbg.generated
     */
    private String airlineVendorId;

    /**
     * Database Column Remarks:
     *   IBE:网站订单；B2B：第三方订单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.channel
     *
     * @mbg.generated
     */
    private String channel;

    /**
     * Database Column Remarks:
     *   发送请求方的国家代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.iso_country
     *
     * @mbg.generated
     */
    private String isoCountry;

    /**
     * Database Column Remarks:
     *   订单出票的货币代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.iso_currency
     *
     * @mbg.generated
     */
    private String isoCurrency;

    /**
     * Database Column Remarks:
     *   标识用于创建此 SuperPNR 的语言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.locale
     *
     * @mbg.generated
     */
    private String locale;

    /**
     * Database Column Remarks:
     *   标识发出预订请求的入口点。取值为omni
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.entry_point
     *
     * @mbg.generated
     */
    private String entryPoint;

    /**
     * Database Column Remarks:
     *   IBE:网站订单，其他值：第三方公司代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.requestor_id
     *
     * @mbg.generated
     */
    private String requestorId;

    /**
     * Database Column Remarks:
     *   订单请求方所属公司的名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.company_short_name
     *
     * @mbg.generated
     */
    private String companyShortName;

    /**
     * Database Column Remarks:
     *   订单请求方所属公司的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_POS.company_name_code
     *
     * @mbg.generated
     */
    private String companyNameCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.super_pnr_id
     *
     * @return the value of Spnr_POS.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.super_pnr_id
     *
     * @param superPnrId the value for Spnr_POS.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.airline_vendor_id
     *
     * @return the value of Spnr_POS.airline_vendor_id
     *
     * @mbg.generated
     */
    public String getAirlineVendorId() {
        return airlineVendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.airline_vendor_id
     *
     * @param airlineVendorId the value for Spnr_POS.airline_vendor_id
     *
     * @mbg.generated
     */
    public void setAirlineVendorId(String airlineVendorId) {
        this.airlineVendorId = airlineVendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.channel
     *
     * @return the value of Spnr_POS.channel
     *
     * @mbg.generated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.channel
     *
     * @param channel the value for Spnr_POS.channel
     *
     * @mbg.generated
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.iso_country
     *
     * @return the value of Spnr_POS.iso_country
     *
     * @mbg.generated
     */
    public String getIsoCountry() {
        return isoCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.iso_country
     *
     * @param isoCountry the value for Spnr_POS.iso_country
     *
     * @mbg.generated
     */
    public void setIsoCountry(String isoCountry) {
        this.isoCountry = isoCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.iso_currency
     *
     * @return the value of Spnr_POS.iso_currency
     *
     * @mbg.generated
     */
    public String getIsoCurrency() {
        return isoCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.iso_currency
     *
     * @param isoCurrency the value for Spnr_POS.iso_currency
     *
     * @mbg.generated
     */
    public void setIsoCurrency(String isoCurrency) {
        this.isoCurrency = isoCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.locale
     *
     * @return the value of Spnr_POS.locale
     *
     * @mbg.generated
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.locale
     *
     * @param locale the value for Spnr_POS.locale
     *
     * @mbg.generated
     */
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.entry_point
     *
     * @return the value of Spnr_POS.entry_point
     *
     * @mbg.generated
     */
    public String getEntryPoint() {
        return entryPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.entry_point
     *
     * @param entryPoint the value for Spnr_POS.entry_point
     *
     * @mbg.generated
     */
    public void setEntryPoint(String entryPoint) {
        this.entryPoint = entryPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.requestor_id
     *
     * @return the value of Spnr_POS.requestor_id
     *
     * @mbg.generated
     */
    public String getRequestorId() {
        return requestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.requestor_id
     *
     * @param requestorId the value for Spnr_POS.requestor_id
     *
     * @mbg.generated
     */
    public void setRequestorId(String requestorId) {
        this.requestorId = requestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.company_short_name
     *
     * @return the value of Spnr_POS.company_short_name
     *
     * @mbg.generated
     */
    public String getCompanyShortName() {
        return companyShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.company_short_name
     *
     * @param companyShortName the value for Spnr_POS.company_short_name
     *
     * @mbg.generated
     */
    public void setCompanyShortName(String companyShortName) {
        this.companyShortName = companyShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_POS.company_name_code
     *
     * @return the value of Spnr_POS.company_name_code
     *
     * @mbg.generated
     */
    public String getCompanyNameCode() {
        return companyNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_POS.company_name_code
     *
     * @param companyNameCode the value for Spnr_POS.company_name_code
     *
     * @mbg.generated
     */
    public void setCompanyNameCode(String companyNameCode) {
        this.companyNameCode = companyNameCode;
    }
}