package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储订单的每一笔支付信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Spnr_Paymentinfo
 */
public class Spnr_PaymentinfoPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   当前Payment在SPNR内的唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   数据库自增字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.seq_no
     *
     * @mbg.generated
     */
    private Long seqNo;

    /**
     * Database Column Remarks:
     *   此次Payment记录对应的金额 @Am
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.amt
     *
     * @mbg.generated
     */
    private Double amt;

    /**
     * Database Column Remarks:
     *   添加该Payment时的Audit ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.audit_id
     *
     * @mbg.generated
     */
    private String auditId;

    /**
     * Database Column Remarks:
     *   货币单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.currency_code
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     * Database Column Remarks:
     *   true:该Payment为历史记录，不
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.historic
     *
     * @mbg.generated
     */
    private String historic;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.history_id
     *
     * @mbg.generated
     */
    private String historyId;

    /**
     * Database Column Remarks:
     *   添加此Payment的时间，非北京时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.payment_date
     *
     * @mbg.generated
     */
    private String paymentDate;

    /**
     * Database Column Remarks:
     *   RPH list of Products
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.product_list
     *
     * @mbg.generated
     */
    private String productList;

    /**
     * Database Column Remarks:
     *   支付状态： Paid：已支付 Unpai
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   Debit：付款 Credit：退款
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.transaction_type
     *
     * @mbg.generated
     */
    private String transactionType;

    /**
     * Database Column Remarks:
     *   该笔支付是否让订单出票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.pre_pay_ind
     *
     * @mbg.generated
     */
    private String prePayInd;

    /**
     * Database Column Remarks:
     *   渠道名或ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.agent
     *
     * @mbg.generated
     */
    private String agent;

    /**
     * Database Column Remarks:
     *   处理该次请求的服务器IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.agent_url
     *
     * @mbg.generated
     */
    private String agentUrl;

    /**
     * Database Column Remarks:
     *   渠道名或ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.agency
     *
     * @mbg.generated
     */
    private String agency;

    /**
     * Database Column Remarks:
     *   支付类型： 101 - 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.payment_form_type
     *
     * @mbg.generated
     */
    private Integer paymentFormType;

    /**
     * Database Column Remarks:
     *   此特定参考的代码。 常用的参考代码是: 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Paymentinfo.ref_code
     *
     * @mbg.generated
     */
    private String refCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.super_pnr_id
     *
     * @return the value of Spnr_Paymentinfo.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.super_pnr_id
     *
     * @param superPnrId the value for Spnr_Paymentinfo.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.id
     *
     * @return the value of Spnr_Paymentinfo.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.id
     *
     * @param id the value for Spnr_Paymentinfo.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.seq_no
     *
     * @return the value of Spnr_Paymentinfo.seq_no
     *
     * @mbg.generated
     */
    public Long getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.seq_no
     *
     * @param seqNo the value for Spnr_Paymentinfo.seq_no
     *
     * @mbg.generated
     */
    public void setSeqNo(Long seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.amt
     *
     * @return the value of Spnr_Paymentinfo.amt
     *
     * @mbg.generated
     */
    public Double getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.amt
     *
     * @param amt the value for Spnr_Paymentinfo.amt
     *
     * @mbg.generated
     */
    public void setAmt(Double amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.audit_id
     *
     * @return the value of Spnr_Paymentinfo.audit_id
     *
     * @mbg.generated
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.audit_id
     *
     * @param auditId the value for Spnr_Paymentinfo.audit_id
     *
     * @mbg.generated
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.currency_code
     *
     * @return the value of Spnr_Paymentinfo.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.currency_code
     *
     * @param currencyCode the value for Spnr_Paymentinfo.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.historic
     *
     * @return the value of Spnr_Paymentinfo.historic
     *
     * @mbg.generated
     */
    public String getHistoric() {
        return historic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.historic
     *
     * @param historic the value for Spnr_Paymentinfo.historic
     *
     * @mbg.generated
     */
    public void setHistoric(String historic) {
        this.historic = historic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.history_id
     *
     * @return the value of Spnr_Paymentinfo.history_id
     *
     * @mbg.generated
     */
    public String getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.history_id
     *
     * @param historyId the value for Spnr_Paymentinfo.history_id
     *
     * @mbg.generated
     */
    public void setHistoryId(String historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.payment_date
     *
     * @return the value of Spnr_Paymentinfo.payment_date
     *
     * @mbg.generated
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.payment_date
     *
     * @param paymentDate the value for Spnr_Paymentinfo.payment_date
     *
     * @mbg.generated
     */
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.product_list
     *
     * @return the value of Spnr_Paymentinfo.product_list
     *
     * @mbg.generated
     */
    public String getProductList() {
        return productList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.product_list
     *
     * @param productList the value for Spnr_Paymentinfo.product_list
     *
     * @mbg.generated
     */
    public void setProductList(String productList) {
        this.productList = productList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.status
     *
     * @return the value of Spnr_Paymentinfo.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.status
     *
     * @param status the value for Spnr_Paymentinfo.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.transaction_type
     *
     * @return the value of Spnr_Paymentinfo.transaction_type
     *
     * @mbg.generated
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.transaction_type
     *
     * @param transactionType the value for Spnr_Paymentinfo.transaction_type
     *
     * @mbg.generated
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.pre_pay_ind
     *
     * @return the value of Spnr_Paymentinfo.pre_pay_ind
     *
     * @mbg.generated
     */
    public String getPrePayInd() {
        return prePayInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.pre_pay_ind
     *
     * @param prePayInd the value for Spnr_Paymentinfo.pre_pay_ind
     *
     * @mbg.generated
     */
    public void setPrePayInd(String prePayInd) {
        this.prePayInd = prePayInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.agent
     *
     * @return the value of Spnr_Paymentinfo.agent
     *
     * @mbg.generated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.agent
     *
     * @param agent the value for Spnr_Paymentinfo.agent
     *
     * @mbg.generated
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.agent_url
     *
     * @return the value of Spnr_Paymentinfo.agent_url
     *
     * @mbg.generated
     */
    public String getAgentUrl() {
        return agentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.agent_url
     *
     * @param agentUrl the value for Spnr_Paymentinfo.agent_url
     *
     * @mbg.generated
     */
    public void setAgentUrl(String agentUrl) {
        this.agentUrl = agentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.agency
     *
     * @return the value of Spnr_Paymentinfo.agency
     *
     * @mbg.generated
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.agency
     *
     * @param agency the value for Spnr_Paymentinfo.agency
     *
     * @mbg.generated
     */
    public void setAgency(String agency) {
        this.agency = agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.payment_form_type
     *
     * @return the value of Spnr_Paymentinfo.payment_form_type
     *
     * @mbg.generated
     */
    public Integer getPaymentFormType() {
        return paymentFormType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.payment_form_type
     *
     * @param paymentFormType the value for Spnr_Paymentinfo.payment_form_type
     *
     * @mbg.generated
     */
    public void setPaymentFormType(Integer paymentFormType) {
        this.paymentFormType = paymentFormType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Paymentinfo.ref_code
     *
     * @return the value of Spnr_Paymentinfo.ref_code
     *
     * @mbg.generated
     */
    public String getRefCode() {
        return refCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Paymentinfo.ref_code
     *
     * @param refCode the value for Spnr_Paymentinfo.ref_code
     *
     * @mbg.generated
     */
    public void setRefCode(String refCode) {
        this.refCode = refCode;
    }
}