package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储MP的基础属性（ModularProduct（简称MP），是SPNR下最重要的一个节点，每一个MP都代表着一个产品的详情信息，如机票、保险、预付费座位、预付费餐食等预定信息，都保存在其对应的MP内。）
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Spnr_MP
 */
public class Spnr_MPPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   最终用户进行的搜索的 ID的唯一标识。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     * Database Column Remarks:
     *   该SPNR内MP唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * Database Column Remarks:
     *   Link to the @history
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.booked_with
     *
     * @mbg.generated
     */
    private String bookedWith;

    /**
     * Database Column Remarks:
     *   预订产品的SUPPLIER渠道
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.booking_channel
     *
     * @mbg.generated
     */
    private String bookingChannel;

    /**
     * Database Column Remarks:
     *   MP预订时间，非北京时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.booking_date
     *
     * @mbg.generated
     */
    private String bookingDate;

    /**
     * Database Column Remarks:
     *   MP状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.booking_status
     *
     * @mbg.generated
     */
    private String bookingStatus;

    /**
     * Database Column Remarks:
     *   取消时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.cancellation_date
     *
     * @mbg.generated
     */
    private String cancellationDate;

    /**
     * Database Column Remarks:
     *   MP内最后一个航段的到达时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.end_date
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     * Database Column Remarks:
     *   该MP是否有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.historic
     *
     * @mbg.generated
     */
    private String historic;

    /**
     * Database Column Remarks:
     *   表明该MP是从哪一个最原始的MP变化而来
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.historic_id
     *
     * @mbg.generated
     */
    private String historicId;

    /**
     * Database Column Remarks:
     *   该MP最后一次修改时间，非北京时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.last_modified
     *
     * @mbg.generated
     */
    private String lastModified;

    /**
     * Database Column Remarks:
     *   如果此产品是另一个产品的附加产品，则它包
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.master_product_number
     *
     * @mbg.generated
     */
    private String masterProductNumber;

    /**
     * Database Column Remarks:
     *   预订使用的语言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.primary_lang_id
     *
     * @mbg.generated
     */
    private String primaryLangId;

    /**
     * Database Column Remarks:
     *   PNR 级别的每个产品的自定义产品 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   产品类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     * Database Column Remarks:
     *   产品类别Code值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.product_type_code
     *
     * @mbg.generated
     */
    private String productTypeCode;

    /**
     * Database Column Remarks:
     *   该MP第一个航段的起飞时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.start_date
     *
     * @mbg.generated
     */
    private String startDate;

    /**
     * Database Column Remarks:
     *   该MP是否进行过同步
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.synchronised
     *
     * @mbg.generated
     */
    private String synchronised;

    /**
     * Database Column Remarks:
     *   国航用来扩充标识国航产品状态的字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.tsbooking_status
     *
     * @mbg.generated
     */
    private String tsbookingStatus;

    /**
     * Database Column Remarks:
     *   指的是哪一个MP是在本MP上变化而来的,
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.live_id
     *
     * @mbg.generated
     */
    private String liveId;

    /**
     * Database Column Remarks:
     *   是否允许退票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.refundable
     *
     * @mbg.generated
     */
    private String refundable;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.replaced_by
     *
     * @mbg.generated
     */
    private String replacedBy;

    /**
     * Database Column Remarks:
     *   票台officeno
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.agent_duty_code
     *
     * @mbg.generated
     */
    private String agentDutyCode;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.ersp_user_id
     *
     * @mbg.generated
     */
    private String erspUserId;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.terminal_id
     *
     * @mbg.generated
     */
    private String terminalId;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.requestor_id
     *
     * @mbg.generated
     */
    private String requestorId;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.company_code
     *
     * @mbg.generated
     */
    private String companyCode;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.company_code_context
     *
     * @mbg.generated
     */
    private String companyCodeContext;

    /**
     * Database Column Remarks:
     *   TSDF:国内票 TSIF:国际票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * Database Column Remarks:
     *   每个Note对应一条信息，以@Type和
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_MP.supplier_notes
     *
     * @mbg.generated
     */
    private String supplierNotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.super_pnr_id
     *
     * @return the value of Spnr_MP.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.super_pnr_id
     *
     * @param superPnrId the value for Spnr_MP.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.search_id
     *
     * @return the value of Spnr_MP.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.search_id
     *
     * @param searchId the value for Spnr_MP.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.product_number
     *
     * @return the value of Spnr_MP.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.product_number
     *
     * @param productNumber the value for Spnr_MP.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.booked_with
     *
     * @return the value of Spnr_MP.booked_with
     *
     * @mbg.generated
     */
    public String getBookedWith() {
        return bookedWith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.booked_with
     *
     * @param bookedWith the value for Spnr_MP.booked_with
     *
     * @mbg.generated
     */
    public void setBookedWith(String bookedWith) {
        this.bookedWith = bookedWith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.booking_channel
     *
     * @return the value of Spnr_MP.booking_channel
     *
     * @mbg.generated
     */
    public String getBookingChannel() {
        return bookingChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.booking_channel
     *
     * @param bookingChannel the value for Spnr_MP.booking_channel
     *
     * @mbg.generated
     */
    public void setBookingChannel(String bookingChannel) {
        this.bookingChannel = bookingChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.booking_date
     *
     * @return the value of Spnr_MP.booking_date
     *
     * @mbg.generated
     */
    public String getBookingDate() {
        return bookingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.booking_date
     *
     * @param bookingDate the value for Spnr_MP.booking_date
     *
     * @mbg.generated
     */
    public void setBookingDate(String bookingDate) {
        this.bookingDate = bookingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.booking_status
     *
     * @return the value of Spnr_MP.booking_status
     *
     * @mbg.generated
     */
    public String getBookingStatus() {
        return bookingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.booking_status
     *
     * @param bookingStatus the value for Spnr_MP.booking_status
     *
     * @mbg.generated
     */
    public void setBookingStatus(String bookingStatus) {
        this.bookingStatus = bookingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.cancellation_date
     *
     * @return the value of Spnr_MP.cancellation_date
     *
     * @mbg.generated
     */
    public String getCancellationDate() {
        return cancellationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.cancellation_date
     *
     * @param cancellationDate the value for Spnr_MP.cancellation_date
     *
     * @mbg.generated
     */
    public void setCancellationDate(String cancellationDate) {
        this.cancellationDate = cancellationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.end_date
     *
     * @return the value of Spnr_MP.end_date
     *
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.end_date
     *
     * @param endDate the value for Spnr_MP.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.historic
     *
     * @return the value of Spnr_MP.historic
     *
     * @mbg.generated
     */
    public String getHistoric() {
        return historic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.historic
     *
     * @param historic the value for Spnr_MP.historic
     *
     * @mbg.generated
     */
    public void setHistoric(String historic) {
        this.historic = historic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.historic_id
     *
     * @return the value of Spnr_MP.historic_id
     *
     * @mbg.generated
     */
    public String getHistoricId() {
        return historicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.historic_id
     *
     * @param historicId the value for Spnr_MP.historic_id
     *
     * @mbg.generated
     */
    public void setHistoricId(String historicId) {
        this.historicId = historicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.last_modified
     *
     * @return the value of Spnr_MP.last_modified
     *
     * @mbg.generated
     */
    public String getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.last_modified
     *
     * @param lastModified the value for Spnr_MP.last_modified
     *
     * @mbg.generated
     */
    public void setLastModified(String lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.master_product_number
     *
     * @return the value of Spnr_MP.master_product_number
     *
     * @mbg.generated
     */
    public String getMasterProductNumber() {
        return masterProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.master_product_number
     *
     * @param masterProductNumber the value for Spnr_MP.master_product_number
     *
     * @mbg.generated
     */
    public void setMasterProductNumber(String masterProductNumber) {
        this.masterProductNumber = masterProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.primary_lang_id
     *
     * @return the value of Spnr_MP.primary_lang_id
     *
     * @mbg.generated
     */
    public String getPrimaryLangId() {
        return primaryLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.primary_lang_id
     *
     * @param primaryLangId the value for Spnr_MP.primary_lang_id
     *
     * @mbg.generated
     */
    public void setPrimaryLangId(String primaryLangId) {
        this.primaryLangId = primaryLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.product_id
     *
     * @return the value of Spnr_MP.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.product_id
     *
     * @param productId the value for Spnr_MP.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.product_type
     *
     * @return the value of Spnr_MP.product_type
     *
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.product_type
     *
     * @param productType the value for Spnr_MP.product_type
     *
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.product_type_code
     *
     * @return the value of Spnr_MP.product_type_code
     *
     * @mbg.generated
     */
    public String getProductTypeCode() {
        return productTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.product_type_code
     *
     * @param productTypeCode the value for Spnr_MP.product_type_code
     *
     * @mbg.generated
     */
    public void setProductTypeCode(String productTypeCode) {
        this.productTypeCode = productTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.start_date
     *
     * @return the value of Spnr_MP.start_date
     *
     * @mbg.generated
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.start_date
     *
     * @param startDate the value for Spnr_MP.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.synchronised
     *
     * @return the value of Spnr_MP.synchronised
     *
     * @mbg.generated
     */
    public String getSynchronised() {
        return synchronised;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.synchronised
     *
     * @param synchronised the value for Spnr_MP.synchronised
     *
     * @mbg.generated
     */
    public void setSynchronised(String synchronised) {
        this.synchronised = synchronised;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.tsbooking_status
     *
     * @return the value of Spnr_MP.tsbooking_status
     *
     * @mbg.generated
     */
    public String getTsbookingStatus() {
        return tsbookingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.tsbooking_status
     *
     * @param tsbookingStatus the value for Spnr_MP.tsbooking_status
     *
     * @mbg.generated
     */
    public void setTsbookingStatus(String tsbookingStatus) {
        this.tsbookingStatus = tsbookingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.live_id
     *
     * @return the value of Spnr_MP.live_id
     *
     * @mbg.generated
     */
    public String getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.live_id
     *
     * @param liveId the value for Spnr_MP.live_id
     *
     * @mbg.generated
     */
    public void setLiveId(String liveId) {
        this.liveId = liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.refundable
     *
     * @return the value of Spnr_MP.refundable
     *
     * @mbg.generated
     */
    public String getRefundable() {
        return refundable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.refundable
     *
     * @param refundable the value for Spnr_MP.refundable
     *
     * @mbg.generated
     */
    public void setRefundable(String refundable) {
        this.refundable = refundable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.replaced_by
     *
     * @return the value of Spnr_MP.replaced_by
     *
     * @mbg.generated
     */
    public String getReplacedBy() {
        return replacedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.replaced_by
     *
     * @param replacedBy the value for Spnr_MP.replaced_by
     *
     * @mbg.generated
     */
    public void setReplacedBy(String replacedBy) {
        this.replacedBy = replacedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.agent_duty_code
     *
     * @return the value of Spnr_MP.agent_duty_code
     *
     * @mbg.generated
     */
    public String getAgentDutyCode() {
        return agentDutyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.agent_duty_code
     *
     * @param agentDutyCode the value for Spnr_MP.agent_duty_code
     *
     * @mbg.generated
     */
    public void setAgentDutyCode(String agentDutyCode) {
        this.agentDutyCode = agentDutyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.ersp_user_id
     *
     * @return the value of Spnr_MP.ersp_user_id
     *
     * @mbg.generated
     */
    public String getErspUserId() {
        return erspUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.ersp_user_id
     *
     * @param erspUserId the value for Spnr_MP.ersp_user_id
     *
     * @mbg.generated
     */
    public void setErspUserId(String erspUserId) {
        this.erspUserId = erspUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.terminal_id
     *
     * @return the value of Spnr_MP.terminal_id
     *
     * @mbg.generated
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.terminal_id
     *
     * @param terminalId the value for Spnr_MP.terminal_id
     *
     * @mbg.generated
     */
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.requestor_id
     *
     * @return the value of Spnr_MP.requestor_id
     *
     * @mbg.generated
     */
    public String getRequestorId() {
        return requestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.requestor_id
     *
     * @param requestorId the value for Spnr_MP.requestor_id
     *
     * @mbg.generated
     */
    public void setRequestorId(String requestorId) {
        this.requestorId = requestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.company_code
     *
     * @return the value of Spnr_MP.company_code
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.company_code
     *
     * @param companyCode the value for Spnr_MP.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.company_code_context
     *
     * @return the value of Spnr_MP.company_code_context
     *
     * @mbg.generated
     */
    public String getCompanyCodeContext() {
        return companyCodeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.company_code_context
     *
     * @param companyCodeContext the value for Spnr_MP.company_code_context
     *
     * @mbg.generated
     */
    public void setCompanyCodeContext(String companyCodeContext) {
        this.companyCodeContext = companyCodeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.company_name
     *
     * @return the value of Spnr_MP.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.company_name
     *
     * @param companyName the value for Spnr_MP.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_MP.supplier_notes
     *
     * @return the value of Spnr_MP.supplier_notes
     *
     * @mbg.generated
     */
    public String getSupplierNotes() {
        return supplierNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_MP.supplier_notes
     *
     * @param supplierNotes the value for Spnr_MP.supplier_notes
     *
     * @mbg.generated
     */
    public void setSupplierNotes(String supplierNotes) {
        this.supplierNotes = supplierNotes;
    }
}