package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储订单的队列信息（每个Queue子节点，都代表一个队列，用于存储订单该、曾经所存在的队列）
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Spnr_Queues
 */
public class Spnr_QueuesPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   队列ID，数据表里作为主键存在，唯一值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.queue_id
     *
     * @mbg.generated
     */
    private Integer queueId;

    /**
     * Database Column Remarks:
     *   SPNR该是否处于该队列下
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.active
     *
     * @mbg.generated
     */
    private String active;

    /**
     * Database Column Remarks:
     *   队列名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.queue_name
     *
     * @mbg.generated
     */
    private String queueName;

    /**
     * Database Column Remarks:
     *   Add:加入队列Delete:从队列中移
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     * Database Column Remarks:
     *   触发此次操作的渠道
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.agent
     *
     * @mbg.generated
     */
    private String agent;

    /**
     * Database Column Remarks:
     *   触发此次操作的时间，非北京时间，需+8处
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.ops_date
     *
     * @mbg.generated
     */
    private String opsDate;

    /**
     * Database Column Remarks:
     *   数据库中的序列号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.seq_no
     *
     * @mbg.generated
     */
    private Long seqNo;

    /**
     * Database Column Remarks:
     *   表示此项是否需要立即处理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.urgent
     *
     * @mbg.generated
     */
    private String urgent;

    /**
     * Database Column Remarks:
     *   此次操作的原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Queues.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.super_pnr_id
     *
     * @return the value of Spnr_Queues.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.super_pnr_id
     *
     * @param superPnrId the value for Spnr_Queues.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.queue_id
     *
     * @return the value of Spnr_Queues.queue_id
     *
     * @mbg.generated
     */
    public Integer getQueueId() {
        return queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.queue_id
     *
     * @param queueId the value for Spnr_Queues.queue_id
     *
     * @mbg.generated
     */
    public void setQueueId(Integer queueId) {
        this.queueId = queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.active
     *
     * @return the value of Spnr_Queues.active
     *
     * @mbg.generated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.active
     *
     * @param active the value for Spnr_Queues.active
     *
     * @mbg.generated
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.queue_name
     *
     * @return the value of Spnr_Queues.queue_name
     *
     * @mbg.generated
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.queue_name
     *
     * @param queueName the value for Spnr_Queues.queue_name
     *
     * @mbg.generated
     */
    public void setQueueName(String queueName) {
        this.queueName = queueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.action
     *
     * @return the value of Spnr_Queues.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.action
     *
     * @param action the value for Spnr_Queues.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.agent
     *
     * @return the value of Spnr_Queues.agent
     *
     * @mbg.generated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.agent
     *
     * @param agent the value for Spnr_Queues.agent
     *
     * @mbg.generated
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.ops_date
     *
     * @return the value of Spnr_Queues.ops_date
     *
     * @mbg.generated
     */
    public String getOpsDate() {
        return opsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.ops_date
     *
     * @param opsDate the value for Spnr_Queues.ops_date
     *
     * @mbg.generated
     */
    public void setOpsDate(String opsDate) {
        this.opsDate = opsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.seq_no
     *
     * @return the value of Spnr_Queues.seq_no
     *
     * @mbg.generated
     */
    public Long getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.seq_no
     *
     * @param seqNo the value for Spnr_Queues.seq_no
     *
     * @mbg.generated
     */
    public void setSeqNo(Long seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.urgent
     *
     * @return the value of Spnr_Queues.urgent
     *
     * @mbg.generated
     */
    public String getUrgent() {
        return urgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.urgent
     *
     * @param urgent the value for Spnr_Queues.urgent
     *
     * @mbg.generated
     */
    public void setUrgent(String urgent) {
        this.urgent = urgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Queues.reason
     *
     * @return the value of Spnr_Queues.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Queues.reason
     *
     * @param reason the value for Spnr_Queues.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}