package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储订单的退后审核信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Spnr_remarks
 */
public class Spnr_remarksPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   该Remark是否是激活状态，还是已成为
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.active
     *
     * @mbg.generated
     */
    private String active;

    /**
     * Database Column Remarks:
     *   跟审计节点关联的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.audit_id
     *
     * @mbg.generated
     */
    private String auditId;

    /**
     * Database Column Remarks:
     *   动作代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.code_context
     *
     * @mbg.generated
     */
    private String codeContext;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.remark_date
     *
     * @mbg.generated
     */
    private String remarkDate;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.history_rph
     *
     * @mbg.generated
     */
    private String historyRph;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.last_modified
     *
     * @mbg.generated
     */
    private String lastModified;

    /**
     * Database Column Remarks:
     *   why not 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.rph
     *
     * @mbg.generated
     */
    private String rph;

    /**
     * Database Column Remarks:
     *   nan
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.seq_no
     *
     * @mbg.generated
     */
    private String seqNo;

    /**
     * Database Column Remarks:
     *   渠道名或ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.agent
     *
     * @mbg.generated
     */
    private String agent;

    /**
     * Database Column Remarks:
     *   所记录审核信息的类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.qualifier_description
     *
     * @mbg.generated
     */
    private String qualifierDescription;

    /**
     * Database Column Remarks:
     *   所记录审核信息的值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.qualifier_value
     *
     * @mbg.generated
     */
    private String qualifierValue;

    /**
     * Database Column Remarks:
     *   审核所处理的航段序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.flight_segment_rph
     *
     * @mbg.generated
     */
    private String flightSegmentRph;

    /**
     * Database Column Remarks:
     *   审核所处理的旅客序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.oj_super_pnr_rph
     *
     * @mbg.generated
     */
    private String ojSuperPnrRph;

    /**
     * Database Column Remarks:
     *   审核所关联的电子客票号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.e_ticket_number
     *
     * @mbg.generated
     */
    private String eTicketNumber;

    /**
     * Database Column Remarks:
     *   旅客类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.passenger_type_code
     *
     * @mbg.generated
     */
    private String passengerTypeCode;

    /**
     * Database Column Remarks:
     *   审核所处理产品的原始ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.history_id
     *
     * @mbg.generated
     */
    private String historyId;

    /**
     * Database Column Remarks:
     *   审核所处理产品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_remarks.product_number
     *
     * @mbg.generated
     */
    private String productNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.super_pnr_id
     *
     * @return the value of Spnr_remarks.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.super_pnr_id
     *
     * @param superPnrId the value for Spnr_remarks.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.active
     *
     * @return the value of Spnr_remarks.active
     *
     * @mbg.generated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.active
     *
     * @param active the value for Spnr_remarks.active
     *
     * @mbg.generated
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.audit_id
     *
     * @return the value of Spnr_remarks.audit_id
     *
     * @mbg.generated
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.audit_id
     *
     * @param auditId the value for Spnr_remarks.audit_id
     *
     * @mbg.generated
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.code
     *
     * @return the value of Spnr_remarks.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.code
     *
     * @param code the value for Spnr_remarks.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.code_context
     *
     * @return the value of Spnr_remarks.code_context
     *
     * @mbg.generated
     */
    public String getCodeContext() {
        return codeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.code_context
     *
     * @param codeContext the value for Spnr_remarks.code_context
     *
     * @mbg.generated
     */
    public void setCodeContext(String codeContext) {
        this.codeContext = codeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.remark_date
     *
     * @return the value of Spnr_remarks.remark_date
     *
     * @mbg.generated
     */
    public String getRemarkDate() {
        return remarkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.remark_date
     *
     * @param remarkDate the value for Spnr_remarks.remark_date
     *
     * @mbg.generated
     */
    public void setRemarkDate(String remarkDate) {
        this.remarkDate = remarkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.history_rph
     *
     * @return the value of Spnr_remarks.history_rph
     *
     * @mbg.generated
     */
    public String getHistoryRph() {
        return historyRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.history_rph
     *
     * @param historyRph the value for Spnr_remarks.history_rph
     *
     * @mbg.generated
     */
    public void setHistoryRph(String historyRph) {
        this.historyRph = historyRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.last_modified
     *
     * @return the value of Spnr_remarks.last_modified
     *
     * @mbg.generated
     */
    public String getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.last_modified
     *
     * @param lastModified the value for Spnr_remarks.last_modified
     *
     * @mbg.generated
     */
    public void setLastModified(String lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.rph
     *
     * @return the value of Spnr_remarks.rph
     *
     * @mbg.generated
     */
    public String getRph() {
        return rph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.rph
     *
     * @param rph the value for Spnr_remarks.rph
     *
     * @mbg.generated
     */
    public void setRph(String rph) {
        this.rph = rph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.seq_no
     *
     * @return the value of Spnr_remarks.seq_no
     *
     * @mbg.generated
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.seq_no
     *
     * @param seqNo the value for Spnr_remarks.seq_no
     *
     * @mbg.generated
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.agent
     *
     * @return the value of Spnr_remarks.agent
     *
     * @mbg.generated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.agent
     *
     * @param agent the value for Spnr_remarks.agent
     *
     * @mbg.generated
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.qualifier_description
     *
     * @return the value of Spnr_remarks.qualifier_description
     *
     * @mbg.generated
     */
    public String getQualifierDescription() {
        return qualifierDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.qualifier_description
     *
     * @param qualifierDescription the value for Spnr_remarks.qualifier_description
     *
     * @mbg.generated
     */
    public void setQualifierDescription(String qualifierDescription) {
        this.qualifierDescription = qualifierDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.qualifier_value
     *
     * @return the value of Spnr_remarks.qualifier_value
     *
     * @mbg.generated
     */
    public String getQualifierValue() {
        return qualifierValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.qualifier_value
     *
     * @param qualifierValue the value for Spnr_remarks.qualifier_value
     *
     * @mbg.generated
     */
    public void setQualifierValue(String qualifierValue) {
        this.qualifierValue = qualifierValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.flight_segment_rph
     *
     * @return the value of Spnr_remarks.flight_segment_rph
     *
     * @mbg.generated
     */
    public String getFlightSegmentRph() {
        return flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.flight_segment_rph
     *
     * @param flightSegmentRph the value for Spnr_remarks.flight_segment_rph
     *
     * @mbg.generated
     */
    public void setFlightSegmentRph(String flightSegmentRph) {
        this.flightSegmentRph = flightSegmentRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.oj_super_pnr_rph
     *
     * @return the value of Spnr_remarks.oj_super_pnr_rph
     *
     * @mbg.generated
     */
    public String getOjSuperPnrRph() {
        return ojSuperPnrRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.oj_super_pnr_rph
     *
     * @param ojSuperPnrRph the value for Spnr_remarks.oj_super_pnr_rph
     *
     * @mbg.generated
     */
    public void setOjSuperPnrRph(String ojSuperPnrRph) {
        this.ojSuperPnrRph = ojSuperPnrRph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.e_ticket_number
     *
     * @return the value of Spnr_remarks.e_ticket_number
     *
     * @mbg.generated
     */
    public String geteTicketNumber() {
        return eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.e_ticket_number
     *
     * @param eTicketNumber the value for Spnr_remarks.e_ticket_number
     *
     * @mbg.generated
     */
    public void seteTicketNumber(String eTicketNumber) {
        this.eTicketNumber = eTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.passenger_type_code
     *
     * @return the value of Spnr_remarks.passenger_type_code
     *
     * @mbg.generated
     */
    public String getPassengerTypeCode() {
        return passengerTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.passenger_type_code
     *
     * @param passengerTypeCode the value for Spnr_remarks.passenger_type_code
     *
     * @mbg.generated
     */
    public void setPassengerTypeCode(String passengerTypeCode) {
        this.passengerTypeCode = passengerTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.history_id
     *
     * @return the value of Spnr_remarks.history_id
     *
     * @mbg.generated
     */
    public String getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.history_id
     *
     * @param historyId the value for Spnr_remarks.history_id
     *
     * @mbg.generated
     */
    public void setHistoryId(String historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_remarks.product_number
     *
     * @return the value of Spnr_remarks.product_number
     *
     * @mbg.generated
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_remarks.product_number
     *
     * @param productNumber the value for Spnr_remarks.product_number
     *
     * @mbg.generated
     */
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }
}