package com.airchina.datacenter.spnr.sdk.dao.entity;

/**
 * Database Table Remarks:
 *   存储订单的价格信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Spnr_Pricing
 */
public class Spnr_PricingPo {
    /**
     * Database Column Remarks:
     *   SPNR ID，唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.super_pnr_id
     *
     * @mbg.generated
     */
    private String superPnrId;

    /**
     * Database Column Remarks:
     *   配送费？
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.post_amt
     *
     * @mbg.generated
     */
    private String postAmt;

    /**
     * Database Column Remarks:
     *   原始价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.pre_amt
     *
     * @mbg.generated
     */
    private String preAmt;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.pre_ori_amt
     *
     * @mbg.generated
     */
    private String preOriAmt;

    /**
     * Database Column Remarks:
     *   要支付的总调价金额，所有子节点Price
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.adjustments_amt
     *
     * @mbg.generated
     */
    private String adjustmentsAmt;

    /**
     * Database Column Remarks:
     *   要支付的总手续费金额，所有子节点Amen
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.amendments_amt
     *
     * @mbg.generated
     */
    private String amendmentsAmt;

    /**
     * Database Column Remarks:
     *   实际总价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.total_amt
     *
     * @mbg.generated
     */
    private String totalAmt;

    /**
     * Database Column Remarks:
     *   未知，待核实
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Spnr_Pricing.total_ori_amt
     *
     * @mbg.generated
     */
    private String totalOriAmt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.super_pnr_id
     *
     * @return the value of Spnr_Pricing.super_pnr_id
     *
     * @mbg.generated
     */
    public String getSuperPnrId() {
        return superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.super_pnr_id
     *
     * @param superPnrId the value for Spnr_Pricing.super_pnr_id
     *
     * @mbg.generated
     */
    public void setSuperPnrId(String superPnrId) {
        this.superPnrId = superPnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.post_amt
     *
     * @return the value of Spnr_Pricing.post_amt
     *
     * @mbg.generated
     */
    public String getPostAmt() {
        return postAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.post_amt
     *
     * @param postAmt the value for Spnr_Pricing.post_amt
     *
     * @mbg.generated
     */
    public void setPostAmt(String postAmt) {
        this.postAmt = postAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.pre_amt
     *
     * @return the value of Spnr_Pricing.pre_amt
     *
     * @mbg.generated
     */
    public String getPreAmt() {
        return preAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.pre_amt
     *
     * @param preAmt the value for Spnr_Pricing.pre_amt
     *
     * @mbg.generated
     */
    public void setPreAmt(String preAmt) {
        this.preAmt = preAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.pre_ori_amt
     *
     * @return the value of Spnr_Pricing.pre_ori_amt
     *
     * @mbg.generated
     */
    public String getPreOriAmt() {
        return preOriAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.pre_ori_amt
     *
     * @param preOriAmt the value for Spnr_Pricing.pre_ori_amt
     *
     * @mbg.generated
     */
    public void setPreOriAmt(String preOriAmt) {
        this.preOriAmt = preOriAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.adjustments_amt
     *
     * @return the value of Spnr_Pricing.adjustments_amt
     *
     * @mbg.generated
     */
    public String getAdjustmentsAmt() {
        return adjustmentsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.adjustments_amt
     *
     * @param adjustmentsAmt the value for Spnr_Pricing.adjustments_amt
     *
     * @mbg.generated
     */
    public void setAdjustmentsAmt(String adjustmentsAmt) {
        this.adjustmentsAmt = adjustmentsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.amendments_amt
     *
     * @return the value of Spnr_Pricing.amendments_amt
     *
     * @mbg.generated
     */
    public String getAmendmentsAmt() {
        return amendmentsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.amendments_amt
     *
     * @param amendmentsAmt the value for Spnr_Pricing.amendments_amt
     *
     * @mbg.generated
     */
    public void setAmendmentsAmt(String amendmentsAmt) {
        this.amendmentsAmt = amendmentsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.total_amt
     *
     * @return the value of Spnr_Pricing.total_amt
     *
     * @mbg.generated
     */
    public String getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.total_amt
     *
     * @param totalAmt the value for Spnr_Pricing.total_amt
     *
     * @mbg.generated
     */
    public void setTotalAmt(String totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Spnr_Pricing.total_ori_amt
     *
     * @return the value of Spnr_Pricing.total_ori_amt
     *
     * @mbg.generated
     */
    public String getTotalOriAmt() {
        return totalOriAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Spnr_Pricing.total_ori_amt
     *
     * @param totalOriAmt the value for Spnr_Pricing.total_ori_amt
     *
     * @mbg.generated
     */
    public void setTotalOriAmt(String totalOriAmt) {
        this.totalOriAmt = totalOriAmt;
    }
}