package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.MP_AirTravelerInfoPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_AirTravelerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirTravelerInfo
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_AirTravelerInfo (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "oj_super_pnr_rph, traveler_ref_number_rph, ",
        "passenger_type_code, age, ",
        "gender, birth_date, ",
        "ptcsub_type, verify_adt_accompanier_age, ",
        "traveler_name, name_prefix, ",
        "telephone, doc_id, ",
        "doc_type, doc_nationality, ",
        "doc_expire_date, birth_country, ",
        "doc_issue_country, additional_doc, ",
        "doc_required, email, ",
        "address_formatted_ind, address_lineindex, ",
        "city_name, postal_code, ",
        "country_name, membership_id, ",
        "`status`, customer_value, ",
        "loyal_level, signup_date, ",
        "effective_date, expire_date, ",
        "single_vendor_ind)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{ojSuperPnrRph,jdbcType=VARCHAR}, #{travelerRefNumberRph,jdbcType=VARCHAR}, ",
        "#{passengerTypeCode,jdbcType=VARCHAR}, #{age,jdbcType=VARCHAR}, ",
        "#{gender,jdbcType=VARCHAR}, #{birthDate,jdbcType=VARCHAR}, ",
        "#{ptcsubType,jdbcType=VARCHAR}, #{verifyAdtAccompanierAge,jdbcType=VARCHAR}, ",
        "#{travelerName,jdbcType=VARCHAR}, #{namePrefix,jdbcType=VARCHAR}, ",
        "#{telephone,jdbcType=VARCHAR}, #{docId,jdbcType=VARCHAR}, ",
        "#{docType,jdbcType=INTEGER}, #{docNationality,jdbcType=VARCHAR}, ",
        "#{docExpireDate,jdbcType=VARCHAR}, #{birthCountry,jdbcType=VARCHAR}, ",
        "#{docIssueCountry,jdbcType=VARCHAR}, #{additionalDoc,jdbcType=VARCHAR}, ",
        "#{docRequired,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{addressFormattedInd,jdbcType=VARCHAR}, #{addressLineindex,jdbcType=VARCHAR}, ",
        "#{cityName,jdbcType=VARCHAR}, #{postalCode,jdbcType=VARCHAR}, ",
        "#{countryName,jdbcType=VARCHAR}, #{membershipId,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{customerValue,jdbcType=VARCHAR}, ",
        "#{loyalLevel,jdbcType=VARCHAR}, #{signupDate,jdbcType=VARCHAR}, ",
        "#{effectiveDate,jdbcType=VARCHAR}, #{expireDate,jdbcType=VARCHAR}, ",
        "#{singleVendorInd,jdbcType=VARCHAR})"
    })
    int insert(MP_AirTravelerInfoPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirTravelerInfo
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, oj_super_pnr_rph, traveler_ref_number_rph, ",
        "passenger_type_code, age, gender, birth_date, ptcsub_type, verify_adt_accompanier_age, ",
        "traveler_name, name_prefix, telephone, doc_id, doc_type, doc_nationality, doc_expire_date, ",
        "birth_country, doc_issue_country, additional_doc, doc_required, email, address_formatted_ind, ",
        "address_lineindex, city_name, postal_code, country_name, membership_id, `status`, ",
        "customer_value, loyal_level, signup_date, effective_date, expire_date, single_vendor_ind",
        "from MP_AirTravelerInfo"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="oj_super_pnr_rph", property="ojSuperPnrRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="traveler_ref_number_rph", property="travelerRefNumberRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="passenger_type_code", property="passengerTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="birth_date", property="birthDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptcsub_type", property="ptcsubType", jdbcType=JdbcType.VARCHAR),
        @Result(column="verify_adt_accompanier_age", property="verifyAdtAccompanierAge", jdbcType=JdbcType.VARCHAR),
        @Result(column="traveler_name", property="travelerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="name_prefix", property="namePrefix", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_id", property="docId", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_type", property="docType", jdbcType=JdbcType.INTEGER),
        @Result(column="doc_nationality", property="docNationality", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_expire_date", property="docExpireDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="birth_country", property="birthCountry", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_issue_country", property="docIssueCountry", jdbcType=JdbcType.VARCHAR),
        @Result(column="additional_doc", property="additionalDoc", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_required", property="docRequired", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="address_formatted_ind", property="addressFormattedInd", jdbcType=JdbcType.VARCHAR),
        @Result(column="address_lineindex", property="addressLineindex", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_name", property="cityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="postal_code", property="postalCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="country_name", property="countryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="membership_id", property="membershipId", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="customer_value", property="customerValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="loyal_level", property="loyalLevel", jdbcType=JdbcType.VARCHAR),
        @Result(column="signup_date", property="signupDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="effective_date", property="effectiveDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="expire_date", property="expireDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="single_vendor_ind", property="singleVendorInd", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_AirTravelerInfoPo> selectAll();
}