package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.MP_AirAirItinerary_SegmentPo;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_AirAirItinerary_segmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirAirItinerary_segment
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_AirAirItinerary_segment (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "od_rph, flight_segment_rph, ",
        "info_source, mod_type, ",
        "original_rph, dport, ",
        "dport_context, dport_terminal, ",
        "dcity, dcountry, ",
        "aport, aport_context, ",
        "aport_terminal, acity, ",
        "acountry, departure_time, ",
        "ori_departure_time, arrival_time, ",
        "marketing_flight_no, operating_flight_no, ",
        "cabin_code, subclass, ",
        "`status`, duration, ",
        "infant_avail_quantity, meal_code, ",
        "segment_type, inv_control, ",
        "mileage, stop_quantity, ",
        "pre_checkin, online_checkin, ",
        "air_equip_type, stop_over, ",
        "stoppoint, stop_context, ",
        "stop_time, av_rph, ",
        "av_subclass, av_subclass_quantity, ",
        "av_subclass_status)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{odRph,jdbcType=VARCHAR}, #{flightSegmentRph,jdbcType=VARCHAR}, ",
        "#{infoSource,jdbcType=VARCHAR}, #{modType,jdbcType=VARCHAR}, ",
        "#{originalRph,jdbcType=VARCHAR}, #{dport,jdbcType=VARCHAR}, ",
        "#{dportContext,jdbcType=VARCHAR}, #{dportTerminal,jdbcType=VARCHAR}, ",
        "#{dcity,jdbcType=VARCHAR}, #{dcountry,jdbcType=VARCHAR}, ",
        "#{aport,jdbcType=VARCHAR}, #{aportContext,jdbcType=VARCHAR}, ",
        "#{aportTerminal,jdbcType=VARCHAR}, #{acity,jdbcType=VARCHAR}, ",
        "#{acountry,jdbcType=VARCHAR}, #{departureTime,jdbcType=VARCHAR}, ",
        "#{oriDepartureTime,jdbcType=VARCHAR}, #{arrivalTime,jdbcType=VARCHAR}, ",
        "#{marketingFlightNo,jdbcType=VARCHAR}, #{operatingFlightNo,jdbcType=VARCHAR}, ",
        "#{cabinCode,jdbcType=VARCHAR}, #{subclass,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{duration,jdbcType=VARCHAR}, ",
        "#{infantAvailQuantity,jdbcType=VARCHAR}, #{mealCode,jdbcType=VARCHAR}, ",
        "#{segmentType,jdbcType=VARCHAR}, #{invControl,jdbcType=VARCHAR}, ",
        "#{mileage,jdbcType=VARCHAR}, #{stopQuantity,jdbcType=VARCHAR}, ",
        "#{preCheckin,jdbcType=VARCHAR}, #{onlineCheckin,jdbcType=VARCHAR}, ",
        "#{airEquipType,jdbcType=VARCHAR}, #{stopOver,jdbcType=VARCHAR}, ",
        "#{stoppoint,jdbcType=VARCHAR}, #{stopContext,jdbcType=VARCHAR}, ",
        "#{stopTime,jdbcType=VARCHAR}, #{avRph,jdbcType=VARCHAR}, ",
        "#{avSubclass,jdbcType=VARCHAR}, #{avSubclassQuantity,jdbcType=VARCHAR}, ",
        "#{avSubclassStatus,jdbcType=VARCHAR})"
    })
    int insert(MP_AirAirItinerary_SegmentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirAirItinerary_segment
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, od_rph, flight_segment_rph, info_source, ",
        "mod_type, original_rph, dport, dport_context, dport_terminal, dcity, dcountry, ",
        "aport, aport_context, aport_terminal, acity, acountry, departure_time, ori_departure_time, ",
        "arrival_time, marketing_flight_no, operating_flight_no, cabin_code, subclass, ",
        "`status`, duration, infant_avail_quantity, meal_code, segment_type, inv_control, ",
        "mileage, stop_quantity, pre_checkin, online_checkin, air_equip_type, stop_over, ",
        "stoppoint, stop_context, stop_time, av_rph, av_subclass, av_subclass_quantity, ",
        "av_subclass_status",
        "from MP_AirAirItinerary_segment"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="od_rph", property="odRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_rph", property="flightSegmentRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="info_source", property="infoSource", jdbcType=JdbcType.VARCHAR),
        @Result(column="mod_type", property="modType", jdbcType=JdbcType.VARCHAR),
        @Result(column="original_rph", property="originalRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="dport", property="dport", jdbcType=JdbcType.VARCHAR),
        @Result(column="dport_context", property="dportContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="dport_terminal", property="dportTerminal", jdbcType=JdbcType.VARCHAR),
        @Result(column="dcity", property="dcity", jdbcType=JdbcType.VARCHAR),
        @Result(column="dcountry", property="dcountry", jdbcType=JdbcType.VARCHAR),
        @Result(column="aport", property="aport", jdbcType=JdbcType.VARCHAR),
        @Result(column="aport_context", property="aportContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="aport_terminal", property="aportTerminal", jdbcType=JdbcType.VARCHAR),
        @Result(column="acity", property="acity", jdbcType=JdbcType.VARCHAR),
        @Result(column="acountry", property="acountry", jdbcType=JdbcType.VARCHAR),
        @Result(column="departure_time", property="departureTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="ori_departure_time", property="oriDepartureTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="arrival_time", property="arrivalTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="marketing_flight_no", property="marketingFlightNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="operating_flight_no", property="operatingFlightNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="cabin_code", property="cabinCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="subclass", property="subclass", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="duration", property="duration", jdbcType=JdbcType.VARCHAR),
        @Result(column="infant_avail_quantity", property="infantAvailQuantity", jdbcType=JdbcType.VARCHAR),
        @Result(column="meal_code", property="mealCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="segment_type", property="segmentType", jdbcType=JdbcType.VARCHAR),
        @Result(column="inv_control", property="invControl", jdbcType=JdbcType.VARCHAR),
        @Result(column="mileage", property="mileage", jdbcType=JdbcType.VARCHAR),
        @Result(column="stop_quantity", property="stopQuantity", jdbcType=JdbcType.VARCHAR),
        @Result(column="pre_checkin", property="preCheckin", jdbcType=JdbcType.VARCHAR),
        @Result(column="online_checkin", property="onlineCheckin", jdbcType=JdbcType.VARCHAR),
        @Result(column="air_equip_type", property="airEquipType", jdbcType=JdbcType.VARCHAR),
        @Result(column="stop_over", property="stopOver", jdbcType=JdbcType.VARCHAR),
        @Result(column="stoppoint", property="stoppoint", jdbcType=JdbcType.VARCHAR),
        @Result(column="stop_context", property="stopContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="stop_time", property="stopTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="av_rph", property="avRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="av_subclass", property="avSubclass", jdbcType=JdbcType.VARCHAR),
        @Result(column="av_subclass_quantity", property="avSubclassQuantity", jdbcType=JdbcType.VARCHAR),
        @Result(column="av_subclass_status", property="avSubclassStatus", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_AirAirItinerary_SegmentPo> selectAll();
}