package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_AirPriceInfo_PTCsPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_AirPriceInfo_PTCsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirPriceInfo_PTCs
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_AirPriceInfo_PTCs (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "passenger_type_code, ptc_sub_type, ",
        "quantity, base_fare_adjusted, ",
        "base_fare_amt, base_fare_ori_amt, ",
        "tax_deatils, price_adjustments_amt, ",
        "total_fare_adjusted, total_fare_amt, ",
        "total_fare_ori_amt, fc_avstring, ",
        "fc_pnr_string, fc_string, ",
        "fn_string, char_set)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{passengerTypeCode,jdbcType=VARCHAR}, #{ptcSubType,jdbcType=VARCHAR}, ",
        "#{quantity,jdbcType=VARCHAR}, #{baseFareAdjusted,jdbcType=VARCHAR}, ",
        "#{baseFareAmt,jdbcType=VARCHAR}, #{baseFareOriAmt,jdbcType=VARCHAR}, ",
        "#{taxDeatils,jdbcType=VARCHAR}, #{priceAdjustmentsAmt,jdbcType=VARCHAR}, ",
        "#{totalFareAdjusted,jdbcType=VARCHAR}, #{totalFareAmt,jdbcType=VARCHAR}, ",
        "#{totalFareOriAmt,jdbcType=VARCHAR}, #{fcAvstring,jdbcType=VARCHAR}, ",
        "#{fcPnrString,jdbcType=VARCHAR}, #{fcString,jdbcType=VARCHAR}, ",
        "#{fnString,jdbcType=VARCHAR}, #{charSet,jdbcType=VARCHAR})"
    })
    int insert(MP_AirPriceInfo_PTCsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirPriceInfo_PTCs
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, passenger_type_code, ptc_sub_type, ",
        "quantity, base_fare_adjusted, base_fare_amt, base_fare_ori_amt, tax_deatils, ",
        "price_adjustments_amt, total_fare_adjusted, total_fare_amt, total_fare_ori_amt, ",
        "fc_avstring, fc_pnr_string, fc_string, fn_string, char_set",
        "from MP_AirPriceInfo_PTCs"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="passenger_type_code", property="passengerTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptc_sub_type", property="ptcSubType", jdbcType=JdbcType.VARCHAR),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_fare_adjusted", property="baseFareAdjusted", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_fare_amt", property="baseFareAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_fare_ori_amt", property="baseFareOriAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_deatils", property="taxDeatils", jdbcType=JdbcType.VARCHAR),
        @Result(column="price_adjustments_amt", property="priceAdjustmentsAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_fare_adjusted", property="totalFareAdjusted", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_fare_amt", property="totalFareAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_fare_ori_amt", property="totalFareOriAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="fc_avstring", property="fcAvstring", jdbcType=JdbcType.VARCHAR),
        @Result(column="fc_pnr_string", property="fcPnrString", jdbcType=JdbcType.VARCHAR),
        @Result(column="fc_string", property="fcString", jdbcType=JdbcType.VARCHAR),
        @Result(column="fn_string", property="fnString", jdbcType=JdbcType.VARCHAR),
        @Result(column="char_set", property="charSet", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_AirPriceInfo_PTCsPo> selectAll();
}