package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_AirTicketingPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_AirTicketingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirTicketing
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_AirTicketing (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "flight_segment_ref_number, irr, ",
        "irr_reason, issuing_agent_id, ",
        "item_number, printed, ",
        "ticket_time, ticketing_status, ",
        "traveler_ref_number, e_ticket_number, ",
        "ticket_time_limit, expiry_date_time, ",
        "waitlist_status, refund_audit_id, ",
        "refund_historic, refund_history_id, ",
        "refund_id, refund_status, ",
        "refund_e_refund_number)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{flightSegmentRefNumber,jdbcType=INTEGER}, #{irr,jdbcType=VARCHAR}, ",
        "#{irrReason,jdbcType=VARCHAR}, #{issuingAgentId,jdbcType=VARCHAR}, ",
        "#{itemNumber,jdbcType=VARCHAR}, #{printed,jdbcType=VARCHAR}, ",
        "#{ticketTime,jdbcType=VARCHAR}, #{ticketingStatus,jdbcType=VARCHAR}, ",
        "#{travelerRefNumber,jdbcType=VARCHAR}, #{eTicketNumber,jdbcType=VARCHAR}, ",
        "#{ticketTimeLimit,jdbcType=VARCHAR}, #{expiryDateTime,jdbcType=VARCHAR}, ",
        "#{waitlistStatus,jdbcType=VARCHAR}, #{refundAuditId,jdbcType=VARCHAR}, ",
        "#{refundHistoric,jdbcType=VARCHAR}, #{refundHistoryId,jdbcType=VARCHAR}, ",
        "#{refundId,jdbcType=VARCHAR}, #{refundStatus,jdbcType=VARCHAR}, ",
        "#{refundERefundNumber,jdbcType=VARCHAR})"
    })
    int insert(MP_AirTicketingPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirTicketing
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, flight_segment_ref_number, irr, ",
        "irr_reason, issuing_agent_id, item_number, printed, ticket_time, ticketing_status, ",
        "traveler_ref_number, e_ticket_number, ticket_time_limit, expiry_date_time, waitlist_status, ",
        "refund_audit_id, refund_historic, refund_history_id, refund_id, refund_status, ",
        "refund_e_refund_number",
        "from MP_AirTicketing"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_ref_number", property="flightSegmentRefNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="irr", property="irr", jdbcType=JdbcType.VARCHAR),
        @Result(column="irr_reason", property="irrReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="issuing_agent_id", property="issuingAgentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_number", property="itemNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="printed", property="printed", jdbcType=JdbcType.VARCHAR),
        @Result(column="ticket_time", property="ticketTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="ticketing_status", property="ticketingStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="traveler_ref_number", property="travelerRefNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="e_ticket_number", property="eTicketNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="ticket_time_limit", property="ticketTimeLimit", jdbcType=JdbcType.VARCHAR),
        @Result(column="expiry_date_time", property="expiryDateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="waitlist_status", property="waitlistStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_audit_id", property="refundAuditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_historic", property="refundHistoric", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_history_id", property="refundHistoryId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_id", property="refundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_status", property="refundStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_e_refund_number", property="refundERefundNumber", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_AirTicketingPo> selectAll();
}