package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_AirPriceInfo_farefamilyPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_AirPriceInfo_farefamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirPriceInfo_farefamily
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_AirPriceInfo_farefamily (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "fare_family_code, fare_family_name, ",
        "chd_rule_as_yfare, cabin_name, ",
        "change_to_open, description, ",
        "domestic_self_checkin, fare_basis, ",
        "inf_rule_as_y_fare, intl_self_checkin, ",
        "upgradable, user_type, ",
        "username, change_aft_dept_rate, ",
        "change_bef_dept_rate, change_currency, ",
        "change_psg_type, change_time_threshold, ",
        "change_type, change_voluntary, ",
        "change_policy_cabin, change_starttime, ",
        "change_endtime, change_policy_rbd, ",
        "change_limit, refund_aft_dept_rate, ",
        "refund_bef_dept_rate, refund_currency, ",
        "refund_psg_type, refund_time_threshold, ",
        "refund_type, refund_voluntary, ",
        "refund_policy_cabin, refund_limit, ",
        "refund_eligible, refund_loyalty_refund_rule_id, ",
        "refund_endtime, refund_starttime, ",
        "refund_policy_rbd)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{fareFamilyCode,jdbcType=VARCHAR}, #{fareFamilyName,jdbcType=VARCHAR}, ",
        "#{chdRuleAsYfare,jdbcType=VARCHAR}, #{cabinName,jdbcType=VARCHAR}, ",
        "#{changeToOpen,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{domesticSelfCheckin,jdbcType=VARCHAR}, #{fareBasis,jdbcType=VARCHAR}, ",
        "#{infRuleAsYFare,jdbcType=VARCHAR}, #{intlSelfCheckin,jdbcType=VARCHAR}, ",
        "#{upgradable,jdbcType=VARCHAR}, #{userType,jdbcType=VARCHAR}, ",
        "#{username,jdbcType=VARCHAR}, #{changeAftDeptRate,jdbcType=DOUBLE}, ",
        "#{changeBefDeptRate,jdbcType=DOUBLE}, #{changeCurrency,jdbcType=VARCHAR}, ",
        "#{changePsgType,jdbcType=VARCHAR}, #{changeTimeThreshold,jdbcType=VARCHAR}, ",
        "#{changeType,jdbcType=VARCHAR}, #{changeVoluntary,jdbcType=VARCHAR}, ",
        "#{changePolicyCabin,jdbcType=VARCHAR}, #{changeStarttime,jdbcType=VARCHAR}, ",
        "#{changeEndtime,jdbcType=VARCHAR}, #{changePolicyRbd,jdbcType=VARCHAR}, ",
        "#{changeLimit,jdbcType=VARCHAR}, #{refundAftDeptRate,jdbcType=DOUBLE}, ",
        "#{refundBefDeptRate,jdbcType=DOUBLE}, #{refundCurrency,jdbcType=VARCHAR}, ",
        "#{refundPsgType,jdbcType=VARCHAR}, #{refundTimeThreshold,jdbcType=VARCHAR}, ",
        "#{refundType,jdbcType=VARCHAR}, #{refundVoluntary,jdbcType=VARCHAR}, ",
        "#{refundPolicyCabin,jdbcType=VARCHAR}, #{refundLimit,jdbcType=VARCHAR}, ",
        "#{refundEligible,jdbcType=VARCHAR}, #{refundLoyaltyRefundRuleId,jdbcType=VARCHAR}, ",
        "#{refundEndtime,jdbcType=VARCHAR}, #{refundStarttime,jdbcType=VARCHAR}, ",
        "#{refundPolicyRbd,jdbcType=VARCHAR})"
    })
    int insert(MP_AirPriceInfo_farefamilyPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirPriceInfo_farefamily
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, fare_family_code, fare_family_name, ",
        "chd_rule_as_yfare, cabin_name, change_to_open, description, domestic_self_checkin, ",
        "fare_basis, inf_rule_as_y_fare, intl_self_checkin, upgradable, user_type, username, ",
        "change_aft_dept_rate, change_bef_dept_rate, change_currency, change_psg_type, ",
        "change_time_threshold, change_type, change_voluntary, change_policy_cabin, change_starttime, ",
        "change_endtime, change_policy_rbd, change_limit, refund_aft_dept_rate, refund_bef_dept_rate, ",
        "refund_currency, refund_psg_type, refund_time_threshold, refund_type, refund_voluntary, ",
        "refund_policy_cabin, refund_limit, refund_eligible, refund_loyalty_refund_rule_id, ",
        "refund_endtime, refund_starttime, refund_policy_rbd",
        "from MP_AirPriceInfo_farefamily"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="fare_family_code", property="fareFamilyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="fare_family_name", property="fareFamilyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="chd_rule_as_yfare", property="chdRuleAsYfare", jdbcType=JdbcType.VARCHAR),
        @Result(column="cabin_name", property="cabinName", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_to_open", property="changeToOpen", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="domestic_self_checkin", property="domesticSelfCheckin", jdbcType=JdbcType.VARCHAR),
        @Result(column="fare_basis", property="fareBasis", jdbcType=JdbcType.VARCHAR),
        @Result(column="inf_rule_as_y_fare", property="infRuleAsYFare", jdbcType=JdbcType.VARCHAR),
        @Result(column="intl_self_checkin", property="intlSelfCheckin", jdbcType=JdbcType.VARCHAR),
        @Result(column="upgradable", property="upgradable", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_type", property="userType", jdbcType=JdbcType.VARCHAR),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_aft_dept_rate", property="changeAftDeptRate", jdbcType=JdbcType.DOUBLE),
        @Result(column="change_bef_dept_rate", property="changeBefDeptRate", jdbcType=JdbcType.DOUBLE),
        @Result(column="change_currency", property="changeCurrency", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_psg_type", property="changePsgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_time_threshold", property="changeTimeThreshold", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_type", property="changeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_voluntary", property="changeVoluntary", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_policy_cabin", property="changePolicyCabin", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_starttime", property="changeStarttime", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_endtime", property="changeEndtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_policy_rbd", property="changePolicyRbd", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_limit", property="changeLimit", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_aft_dept_rate", property="refundAftDeptRate", jdbcType=JdbcType.DOUBLE),
        @Result(column="refund_bef_dept_rate", property="refundBefDeptRate", jdbcType=JdbcType.DOUBLE),
        @Result(column="refund_currency", property="refundCurrency", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_psg_type", property="refundPsgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_time_threshold", property="refundTimeThreshold", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_type", property="refundType", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_voluntary", property="refundVoluntary", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_policy_cabin", property="refundPolicyCabin", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_limit", property="refundLimit", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_eligible", property="refundEligible", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_loyalty_refund_rule_id", property="refundLoyaltyRefundRuleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_endtime", property="refundEndtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_starttime", property="refundStarttime", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_policy_rbd", property="refundPolicyRbd", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_AirPriceInfo_farefamilyPo> selectAll();
}