package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_AncillaryProductPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_AncillaryProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AncillaryProduct
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_AncillaryProduct (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "cancelable, category, ",
        "code, book_date, ",
        "origin, destination, ",
        "flight_number, flight_segment_rph, ",
        "marketing_airline, quantity, ",
        "refundable, seat_number, ",
        "`type`, is_seg_bind, ",
        "traveler_ref_number_rph, e_ticket_number, ",
        "ticket_advisory, contact_person_name, ",
        "airport, booking_channel, ",
        "booking_reference_id, booking_status, ",
        "cabin_class, carrier, ",
        "`name`, origin_destination_rph, ",
        "pool_id, product_sequence, ",
        "`ref`, selling_proposition, ",
        "sub_type, supplier_code, ",
        "supplier_product_code, tag, ",
        "terminal, cancel_penalty_deadline_offset_time_unit, ",
        "cancel_penalty_deadline_offset_unit_multiplier, ",
        "amount_percent, loyalty_level, ",
        "passenger_type_code, base_amount, ",
        "unit_price, price_adjustments_amount, ",
        "total_adjusted, total_amount, ",
        "checkin_offset_drop_time, checkin_offset_time_unit, ",
        "checkin_offset_unit_multiplier, area_sub_type, ",
        "area_type, capacity, ",
        "room_code, room_opentime_language, ",
        "descriptive_text, gate, ",
        "room_language, display_name, ",
        "airport_name, short_content, ",
        "location_description, official_name, ",
        "image_url)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{cancelable,jdbcType=VARCHAR}, #{category,jdbcType=VARCHAR}, ",
        "#{code,jdbcType=VARCHAR}, #{bookDate,jdbcType=VARCHAR}, ",
        "#{origin,jdbcType=VARCHAR}, #{destination,jdbcType=VARCHAR}, ",
        "#{flightNumber,jdbcType=VARCHAR}, #{flightSegmentRph,jdbcType=VARCHAR}, ",
        "#{marketingAirline,jdbcType=VARCHAR}, #{quantity,jdbcType=VARCHAR}, ",
        "#{refundable,jdbcType=VARCHAR}, #{seatNumber,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{isSegBind,jdbcType=VARCHAR}, ",
        "#{travelerRefNumberRph,jdbcType=VARCHAR}, #{eTicketNumber,jdbcType=VARCHAR}, ",
        "#{ticketAdvisory,jdbcType=VARCHAR}, #{contactPersonName,jdbcType=VARCHAR}, ",
        "#{airport,jdbcType=VARCHAR}, #{bookingChannel,jdbcType=VARCHAR}, ",
        "#{bookingReferenceId,jdbcType=VARCHAR}, #{bookingStatus,jdbcType=VARCHAR}, ",
        "#{cabinClass,jdbcType=VARCHAR}, #{carrier,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{originDestinationRph,jdbcType=VARCHAR}, ",
        "#{poolId,jdbcType=VARCHAR}, #{productSequence,jdbcType=VARCHAR}, ",
        "#{ref,jdbcType=VARCHAR}, #{sellingProposition,jdbcType=VARCHAR}, ",
        "#{subType,jdbcType=VARCHAR}, #{supplierCode,jdbcType=VARCHAR}, ",
        "#{supplierProductCode,jdbcType=VARCHAR}, #{tag,jdbcType=VARCHAR}, ",
        "#{terminal,jdbcType=VARCHAR}, #{cancelPenaltyDeadlineOffsetTimeUnit,jdbcType=VARCHAR}, ",
        "#{cancelPenaltyDeadlineOffsetUnitMultiplier,jdbcType=VARCHAR}, ",
        "#{amountPercent,jdbcType=VARCHAR}, #{loyaltyLevel,jdbcType=VARCHAR}, ",
        "#{passengerTypeCode,jdbcType=VARCHAR}, #{baseAmount,jdbcType=VARCHAR}, ",
        "#{unitPrice,jdbcType=VARCHAR}, #{priceAdjustmentsAmount,jdbcType=VARCHAR}, ",
        "#{totalAdjusted,jdbcType=VARCHAR}, #{totalAmount,jdbcType=VARCHAR}, ",
        "#{checkinOffsetDropTime,jdbcType=VARCHAR}, #{checkinOffsetTimeUnit,jdbcType=VARCHAR}, ",
        "#{checkinOffsetUnitMultiplier,jdbcType=VARCHAR}, #{areaSubType,jdbcType=VARCHAR}, ",
        "#{areaType,jdbcType=VARCHAR}, #{capacity,jdbcType=VARCHAR}, ",
        "#{roomCode,jdbcType=VARCHAR}, #{roomOpentimeLanguage,jdbcType=VARCHAR}, ",
        "#{descriptiveText,jdbcType=VARCHAR}, #{gate,jdbcType=VARCHAR}, ",
        "#{roomLanguage,jdbcType=VARCHAR}, #{displayName,jdbcType=VARCHAR}, ",
        "#{airportName,jdbcType=VARCHAR}, #{shortContent,jdbcType=VARCHAR}, ",
        "#{locationDescription,jdbcType=VARCHAR}, #{officialName,jdbcType=VARCHAR}, ",
        "#{imageUrl,jdbcType=VARCHAR})"
    })
    int insert(MP_AncillaryProductPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AncillaryProduct
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, cancelable, category, code, book_date, ",
        "origin, destination, flight_number, flight_segment_rph, marketing_airline, quantity, ",
        "refundable, seat_number, `type`, is_seg_bind, traveler_ref_number_rph, e_ticket_number, ",
        "ticket_advisory, contact_person_name, airport, booking_channel, booking_reference_id, ",
        "booking_status, cabin_class, carrier, `name`, origin_destination_rph, pool_id, ",
        "product_sequence, `ref`, selling_proposition, sub_type, supplier_code, supplier_product_code, ",
        "tag, terminal, cancel_penalty_deadline_offset_time_unit, cancel_penalty_deadline_offset_unit_multiplier, ",
        "amount_percent, loyalty_level, passenger_type_code, base_amount, unit_price, ",
        "price_adjustments_amount, total_adjusted, total_amount, checkin_offset_drop_time, ",
        "checkin_offset_time_unit, checkin_offset_unit_multiplier, area_sub_type, area_type, ",
        "capacity, room_code, room_opentime_language, descriptive_text, gate, room_language, ",
        "display_name, airport_name, short_content, location_description, official_name, ",
        "image_url",
        "from MP_AncillaryProduct"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="cancelable", property="cancelable", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="book_date", property="bookDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="origin", property="origin", jdbcType=JdbcType.VARCHAR),
        @Result(column="destination", property="destination", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_number", property="flightNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_rph", property="flightSegmentRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="marketing_airline", property="marketingAirline", jdbcType=JdbcType.VARCHAR),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.VARCHAR),
        @Result(column="refundable", property="refundable", jdbcType=JdbcType.VARCHAR),
        @Result(column="seat_number", property="seatNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_seg_bind", property="isSegBind", jdbcType=JdbcType.VARCHAR),
        @Result(column="traveler_ref_number_rph", property="travelerRefNumberRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="e_ticket_number", property="eTicketNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="ticket_advisory", property="ticketAdvisory", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_person_name", property="contactPersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="airport", property="airport", jdbcType=JdbcType.VARCHAR),
        @Result(column="booking_channel", property="bookingChannel", jdbcType=JdbcType.VARCHAR),
        @Result(column="booking_reference_id", property="bookingReferenceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="booking_status", property="bookingStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="cabin_class", property="cabinClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="carrier", property="carrier", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="origin_destination_rph", property="originDestinationRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="pool_id", property="poolId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_sequence", property="productSequence", jdbcType=JdbcType.VARCHAR),
        @Result(column="ref", property="ref", jdbcType=JdbcType.VARCHAR),
        @Result(column="selling_proposition", property="sellingProposition", jdbcType=JdbcType.VARCHAR),
        @Result(column="sub_type", property="subType", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_code", property="supplierCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_product_code", property="supplierProductCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="tag", property="tag", jdbcType=JdbcType.VARCHAR),
        @Result(column="terminal", property="terminal", jdbcType=JdbcType.VARCHAR),
        @Result(column="cancel_penalty_deadline_offset_time_unit", property="cancelPenaltyDeadlineOffsetTimeUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="cancel_penalty_deadline_offset_unit_multiplier", property="cancelPenaltyDeadlineOffsetUnitMultiplier", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount_percent", property="amountPercent", jdbcType=JdbcType.VARCHAR),
        @Result(column="loyalty_level", property="loyaltyLevel", jdbcType=JdbcType.VARCHAR),
        @Result(column="passenger_type_code", property="passengerTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_amount", property="baseAmount", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.VARCHAR),
        @Result(column="price_adjustments_amount", property="priceAdjustmentsAmount", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_adjusted", property="totalAdjusted", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.VARCHAR),
        @Result(column="checkin_offset_drop_time", property="checkinOffsetDropTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="checkin_offset_time_unit", property="checkinOffsetTimeUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="checkin_offset_unit_multiplier", property="checkinOffsetUnitMultiplier", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_sub_type", property="areaSubType", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_type", property="areaType", jdbcType=JdbcType.VARCHAR),
        @Result(column="capacity", property="capacity", jdbcType=JdbcType.VARCHAR),
        @Result(column="room_code", property="roomCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="room_opentime_language", property="roomOpentimeLanguage", jdbcType=JdbcType.VARCHAR),
        @Result(column="descriptive_text", property="descriptiveText", jdbcType=JdbcType.VARCHAR),
        @Result(column="gate", property="gate", jdbcType=JdbcType.VARCHAR),
        @Result(column="room_language", property="roomLanguage", jdbcType=JdbcType.VARCHAR),
        @Result(column="display_name", property="displayName", jdbcType=JdbcType.VARCHAR),
        @Result(column="airport_name", property="airportName", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_content", property="shortContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="location_description", property="locationDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="official_name", property="officialName", jdbcType=JdbcType.VARCHAR),
        @Result(column="image_url", property="imageUrl", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_AncillaryProductPo> selectAll();
}