package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_AirPriceInfo_ItinTotalFarePo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_AirPriceInfo_ItinTotalFareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirPriceInfo_ItinTotalFare
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_AirPriceInfo_ItinTotalFare (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "pricing_source, fare_family_code, ",
        "farefamily_name, price_quote_date, ",
        "base_fare_adjusted, base_fare_amt, ",
        "base_fare_ori_amt, tax_deatils, ",
        "total_fare_adjusted, total_fare_amt, ",
        "total_fare_ori_amt)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{pricingSource,jdbcType=VARCHAR}, #{fareFamilyCode,jdbcType=VARCHAR}, ",
        "#{farefamilyName,jdbcType=VARCHAR}, #{priceQuoteDate,jdbcType=VARCHAR}, ",
        "#{baseFareAdjusted,jdbcType=VARCHAR}, #{baseFareAmt,jdbcType=VARCHAR}, ",
        "#{baseFareOriAmt,jdbcType=VARCHAR}, #{taxDeatils,jdbcType=VARCHAR}, ",
        "#{totalFareAdjusted,jdbcType=VARCHAR}, #{totalFareAmt,jdbcType=VARCHAR}, ",
        "#{totalFareOriAmt,jdbcType=VARCHAR})"
    })
    int insert(MP_AirPriceInfo_ItinTotalFarePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_AirPriceInfo_ItinTotalFare
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, pricing_source, fare_family_code, ",
        "farefamily_name, price_quote_date, base_fare_adjusted, base_fare_amt, base_fare_ori_amt, ",
        "tax_deatils, total_fare_adjusted, total_fare_amt, total_fare_ori_amt",
        "from MP_AirPriceInfo_ItinTotalFare"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="pricing_source", property="pricingSource", jdbcType=JdbcType.VARCHAR),
        @Result(column="fare_family_code", property="fareFamilyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="farefamily_name", property="farefamilyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="price_quote_date", property="priceQuoteDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_fare_adjusted", property="baseFareAdjusted", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_fare_amt", property="baseFareAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_fare_ori_amt", property="baseFareOriAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_deatils", property="taxDeatils", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_fare_adjusted", property="totalFareAdjusted", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_fare_amt", property="totalFareAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_fare_ori_amt", property="totalFareOriAmt", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_AirPriceInfo_ItinTotalFarePo> selectAll();
}