package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.MP_itineraryreceiptPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_itineraryreceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_itineraryreceipt
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_itineraryreceipt (super_pnr_id, search_id, ",
        "product_number, channel, ",
        "itinerary_receipt_id, logistics_id, ",
        "`status`, tracking_number, ",
        "recipient_person_name, recipient_telephone, ",
        "recipient_address, estimated_price, ",
        "recipient_currency_code, product_arrival_date_time, ",
        "product_channel, product_geo_indicator, ",
        "product_history_id, product_product_number, ",
        "product_product_type, product_e_ticket_number, ",
        "product_ticket_price, product_currency_code, ",
        "product_passenger_name, sequence_id)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{channel,jdbcType=VARCHAR}, ",
        "#{itineraryReceiptId,jdbcType=VARCHAR}, #{logisticsId,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{trackingNumber,jdbcType=VARCHAR}, ",
        "#{recipientPersonName,jdbcType=VARCHAR}, #{recipientTelephone,jdbcType=VARCHAR}, ",
        "#{recipientAddress,jdbcType=VARCHAR}, #{estimatedPrice,jdbcType=VARCHAR}, ",
        "#{recipientCurrencyCode,jdbcType=VARCHAR}, #{productArrivalDateTime,jdbcType=VARCHAR}, ",
        "#{productChannel,jdbcType=VARCHAR}, #{productGeoIndicator,jdbcType=VARCHAR}, ",
        "#{productHistoryId,jdbcType=VARCHAR}, #{productProductNumber,jdbcType=VARCHAR}, ",
        "#{productProductType,jdbcType=VARCHAR}, #{productETicketNumber,jdbcType=VARCHAR}, ",
        "#{productTicketPrice,jdbcType=VARCHAR}, #{productCurrencyCode,jdbcType=VARCHAR}, ",
        "#{productPassengerName,jdbcType=VARCHAR}, #{sequenceId,jdbcType=VARCHAR})"
    })
    int insert(MP_itineraryreceiptPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_itineraryreceipt
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, channel, itinerary_receipt_id, logistics_id, ",
        "`status`, tracking_number, recipient_person_name, recipient_telephone, recipient_address, ",
        "estimated_price, recipient_currency_code, product_arrival_date_time, product_channel, ",
        "product_geo_indicator, product_history_id, product_product_number, product_product_type, ",
        "product_e_ticket_number, product_ticket_price, product_currency_code, product_passenger_name, ",
        "sequence_id",
        "from MP_itineraryreceipt"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel", property="channel", jdbcType=JdbcType.VARCHAR),
        @Result(column="itinerary_receipt_id", property="itineraryReceiptId", jdbcType=JdbcType.VARCHAR),
        @Result(column="logistics_id", property="logisticsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="tracking_number", property="trackingNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="recipient_person_name", property="recipientPersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="recipient_telephone", property="recipientTelephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="recipient_address", property="recipientAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="estimated_price", property="estimatedPrice", jdbcType=JdbcType.VARCHAR),
        @Result(column="recipient_currency_code", property="recipientCurrencyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_arrival_date_time", property="productArrivalDateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_channel", property="productChannel", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_geo_indicator", property="productGeoIndicator", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_history_id", property="productHistoryId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_product_number", property="productProductNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_product_type", property="productProductType", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_e_ticket_number", property="productETicketNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_ticket_price", property="productTicketPrice", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_currency_code", property="productCurrencyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_passenger_name", property="productPassengerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_id", property="sequenceId", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_itineraryreceiptPo> selectAll();
}