package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_ModifyTypesPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_ModifyTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_ModifyTypes
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_ModifyTypes (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "audit_id, original_history_id, ",
        "rph, `type`, free_date_change, ",
        "old_mp_num, split_required, ",
        "need_cancel, old_pnr, ",
        "reshop_id)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{auditId,jdbcType=VARCHAR}, #{originalHistoryId,jdbcType=VARCHAR}, ",
        "#{rph,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, #{freeDateChange,jdbcType=VARCHAR}, ",
        "#{oldMpNum,jdbcType=VARCHAR}, #{splitRequired,jdbcType=VARCHAR}, ",
        "#{needCancel,jdbcType=VARCHAR}, #{oldPnr,jdbcType=VARCHAR}, ",
        "#{reshopId,jdbcType=VARCHAR})"
    })
    int insert(MP_ModifyTypesPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_ModifyTypes
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, audit_id, original_history_id, ",
        "rph, `type`, free_date_change, old_mp_num, split_required, need_cancel, old_pnr, ",
        "reshop_id",
        "from MP_ModifyTypes"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="original_history_id", property="originalHistoryId", jdbcType=JdbcType.VARCHAR),
        @Result(column="rph", property="rph", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="free_date_change", property="freeDateChange", jdbcType=JdbcType.VARCHAR),
        @Result(column="old_mp_num", property="oldMpNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="split_required", property="splitRequired", jdbcType=JdbcType.VARCHAR),
        @Result(column="need_cancel", property="needCancel", jdbcType=JdbcType.VARCHAR),
        @Result(column="old_pnr", property="oldPnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="reshop_id", property="reshopId", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_ModifyTypesPo> selectAll();
}