package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.MP_PricingPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_PricingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_Pricing (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "pre_amt, pre_pay_ind, ",
        "adjustments_amt, total_amt, ",
        "cancellation_fees, cancellation_refunds)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{preAmt,jdbcType=VARCHAR}, #{prePayInd,jdbcType=VARCHAR}, ",
        "#{adjustmentsAmt,jdbcType=VARCHAR}, #{totalAmt,jdbcType=VARCHAR}, ",
        "#{cancellationFees,jdbcType=VARCHAR}, #{cancellationRefunds,jdbcType=VARCHAR})"
    })
    int insert(MP_PricingPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, pre_amt, pre_pay_ind, adjustments_amt, ",
        "total_amt, cancellation_fees, cancellation_refunds",
        "from MP_Pricing"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="pre_amt", property="preAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="pre_pay_ind", property="prePayInd", jdbcType=JdbcType.VARCHAR),
        @Result(column="adjustments_amt", property="adjustmentsAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_amt", property="totalAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="cancellation_fees", property="cancellationFees", jdbcType=JdbcType.VARCHAR),
        @Result(column="cancellation_refunds", property="cancellationRefunds", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_PricingPo> selectAll();
}