package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_Pricing_CancellationFeesPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_Pricing_CancellationFeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing_CancellationFees
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_Pricing_CancellationFees (super_pnr_id, search_id, ",
        "product_number, oj_super_pnr_rph, ",
        "amt, currency_code, ",
        "audit_id, flight_segment_rph, ",
        "added_date, master_product_number, ",
        "percentage, cancel_product_number, ",
        "product_type, agent, ",
        "agent_url, agency)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{ojSuperPnrRph,jdbcType=VARCHAR}, ",
        "#{amt,jdbcType=DOUBLE}, #{currencyCode,jdbcType=VARCHAR}, ",
        "#{auditId,jdbcType=VARCHAR}, #{flightSegmentRph,jdbcType=VARCHAR}, ",
        "#{addedDate,jdbcType=VARCHAR}, #{masterProductNumber,jdbcType=VARCHAR}, ",
        "#{percentage,jdbcType=VARCHAR}, #{cancelProductNumber,jdbcType=VARCHAR}, ",
        "#{productType,jdbcType=VARCHAR}, #{agent,jdbcType=VARCHAR}, ",
        "#{agentUrl,jdbcType=VARCHAR}, #{agency,jdbcType=VARCHAR})"
    })
    int insert(MP_Pricing_CancellationFeesPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing_CancellationFees
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, oj_super_pnr_rph, amt, currency_code, ",
        "audit_id, flight_segment_rph, added_date, master_product_number, percentage, ",
        "cancel_product_number, product_type, agent, agent_url, agency",
        "from MP_Pricing_CancellationFees"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="oj_super_pnr_rph", property="ojSuperPnrRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="amt", property="amt", jdbcType=JdbcType.DOUBLE),
        @Result(column="currency_code", property="currencyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_rph", property="flightSegmentRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="added_date", property="addedDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="master_product_number", property="masterProductNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="percentage", property="percentage", jdbcType=JdbcType.VARCHAR),
        @Result(column="cancel_product_number", property="cancelProductNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_type", property="productType", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent", property="agent", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent_url", property="agentUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="agency", property="agency", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_Pricing_CancellationFeesPo> selectAll();
}