package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.MP_PTCsPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_PtcsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Ptcs
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_Ptcs (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "ptc_code, ptc_quantity, ",
        "rph_list)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{ptcCode,jdbcType=VARCHAR}, #{ptcQuantity,jdbcType=INTEGER}, ",
        "#{rphList,jdbcType=VARCHAR})"
    })
    int insert(MP_PTCsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Ptcs
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, ptc_code, ptc_quantity, rph_list",
        "from MP_Ptcs"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptc_code", property="ptcCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptc_quantity", property="ptcQuantity", jdbcType=JdbcType.INTEGER),
        @Result(column="rph_list", property="rphList", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_PTCsPo> selectAll();
}