package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_Pricing_AmendmentFeePo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_Pricing_AmendmentFeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing_AmendmentFee
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_Pricing_AmendmentFee (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "amt, currency_code, ",
        "`date`)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{amt,jdbcType=DOUBLE}, #{currencyCode,jdbcType=VARCHAR}, ",
        "#{date,jdbcType=VARCHAR})"
    })
    int insert(MP_Pricing_AmendmentFeePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing_AmendmentFee
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, amt, currency_code, `date`",
        "from MP_Pricing_AmendmentFee"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="amt", property="amt", jdbcType=JdbcType.DOUBLE),
        @Result(column="currency_code", property="currencyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_Pricing_AmendmentFeePo> selectAll();
}