package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.MP_PaymentRefsPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_PaymentRefsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_PaymentRefs
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_PaymentRefs (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "payment_refs_audit_id, payment_state, ",
        "payment_ref_id, payment_id, ",
        "payment_ref_audit_id)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{paymentRefsAuditId,jdbcType=VARCHAR}, #{paymentState,jdbcType=VARCHAR}, ",
        "#{paymentRefId,jdbcType=VARCHAR}, #{paymentId,jdbcType=VARCHAR}, ",
        "#{paymentRefAuditId,jdbcType=VARCHAR})"
    })
    int insert(MP_PaymentRefsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_PaymentRefs
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, payment_refs_audit_id, payment_state, ",
        "payment_ref_id, payment_id, payment_ref_audit_id",
        "from MP_PaymentRefs"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_refs_audit_id", property="paymentRefsAuditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_state", property="paymentState", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_ref_id", property="paymentRefId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_id", property="paymentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_ref_audit_id", property="paymentRefAuditId", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_PaymentRefsPo> selectAll();
}