package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_Pricing_PriceAdjustmentsPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_Pricing_PriceAdjustmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing_PriceAdjustments
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_Pricing_PriceAdjustments (super_pnr_id, search_id, ",
        "product_number, pnr, ",
        "adjust_date, code, ",
        "product_type, description, ",
        "amt, currency_code, ",
        "unit_amt, audit_id, ",
        "passenger_type_code, flight_segment_rph, ",
        "agent, agent_url, ",
        "agency)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{pnr,jdbcType=VARCHAR}, ",
        "#{adjustDate,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{productType,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{amt,jdbcType=DOUBLE}, #{currencyCode,jdbcType=VARCHAR}, ",
        "#{unitAmt,jdbcType=DOUBLE}, #{auditId,jdbcType=VARCHAR}, ",
        "#{passengerTypeCode,jdbcType=VARCHAR}, #{flightSegmentRph,jdbcType=VARCHAR}, ",
        "#{agent,jdbcType=VARCHAR}, #{agentUrl,jdbcType=VARCHAR}, ",
        "#{agency,jdbcType=VARCHAR})"
    })
    int insert(MP_Pricing_PriceAdjustmentsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Pricing_PriceAdjustments
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, pnr, adjust_date, code, product_type, ",
        "description, amt, currency_code, unit_amt, audit_id, passenger_type_code, flight_segment_rph, ",
        "agent, agent_url, agency",
        "from MP_Pricing_PriceAdjustments"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="pnr", property="pnr", jdbcType=JdbcType.VARCHAR),
        @Result(column="adjust_date", property="adjustDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_type", property="productType", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="amt", property="amt", jdbcType=JdbcType.DOUBLE),
        @Result(column="currency_code", property="currencyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_amt", property="unitAmt", jdbcType=JdbcType.DOUBLE),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="passenger_type_code", property="passengerTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_rph", property="flightSegmentRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent", property="agent", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent_url", property="agentUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="agency", property="agency", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_Pricing_PriceAdjustmentsPo> selectAll();
}