package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.MP_RemarksPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MP_RemarksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Remarks
     *
     * @mbg.generated
     */
    @Insert({
        "insert into MP_Remarks (super_pnr_id, search_id, ",
        "product_number, active, ",
        "audit_id, code, code_context, ",
        "ops_date, last_modified, ",
        "rph, agent, agent_source_address, ",
        "in_timestamp, qualifier_description, ",
        "qualifier_value, flight_segment_rph, ",
        "oj_super_pnr_rph, e_ticket_number, ",
        "qualifier_item_name, qualifier_item_value, ",
        "passenger_type_code, history_id, ",
        "product_no, tax_code)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{searchId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR}, #{active,jdbcType=VARCHAR}, ",
        "#{auditId,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, #{codeContext,jdbcType=VARCHAR}, ",
        "#{opsDate,jdbcType=VARCHAR}, #{lastModified,jdbcType=VARCHAR}, ",
        "#{rph,jdbcType=VARCHAR}, #{agent,jdbcType=VARCHAR}, #{agentSourceAddress,jdbcType=VARCHAR}, ",
        "#{inTimestamp,jdbcType=VARCHAR}, #{qualifierDescription,jdbcType=VARCHAR}, ",
        "#{qualifierValue,jdbcType=VARCHAR}, #{flightSegmentRph,jdbcType=VARCHAR}, ",
        "#{ojSuperPnrRph,jdbcType=VARCHAR}, #{eTicketNumber,jdbcType=VARCHAR}, ",
        "#{qualifierItemName,jdbcType=VARCHAR}, #{qualifierItemValue,jdbcType=VARCHAR}, ",
        "#{passengerTypeCode,jdbcType=VARCHAR}, #{historyId,jdbcType=VARCHAR}, ",
        "#{productNo,jdbcType=VARCHAR}, #{taxCode,jdbcType=VARCHAR})"
    })
    int insert(MP_RemarksPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MP_Remarks
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, search_id, product_number, active, audit_id, code, code_context, ",
        "ops_date, last_modified, rph, agent, agent_source_address, in_timestamp, qualifier_description, ",
        "qualifier_value, flight_segment_rph, oj_super_pnr_rph, e_ticket_number, qualifier_item_name, ",
        "qualifier_item_value, passenger_type_code, history_id, product_no, tax_code",
        "from MP_Remarks"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_id", property="searchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="active", property="active", jdbcType=JdbcType.VARCHAR),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="code_context", property="codeContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="ops_date", property="opsDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified", property="lastModified", jdbcType=JdbcType.VARCHAR),
        @Result(column="rph", property="rph", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent", property="agent", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent_source_address", property="agentSourceAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_timestamp", property="inTimestamp", jdbcType=JdbcType.VARCHAR),
        @Result(column="qualifier_description", property="qualifierDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="qualifier_value", property="qualifierValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_rph", property="flightSegmentRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="oj_super_pnr_rph", property="ojSuperPnrRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="e_ticket_number", property="eTicketNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="qualifier_item_name", property="qualifierItemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="qualifier_item_value", property="qualifierItemValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="passenger_type_code", property="passengerTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="history_id", property="historyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_no", property="productNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_code", property="taxCode", jdbcType=JdbcType.VARCHAR)
    })
    List<MP_RemarksPo> selectAll();
}