package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.Spnr_AuditsPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Spnr_AuditsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Audits
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Spnr_Audits (super_pnr_id, audit_id, ",
        "requestor_id, channel, ",
        "version, ops_timestamp, ",
        "source_address, `action`, ",
        "agent, agent_url, ",
        "agency, event_context, ",
        "event_id, event_oj_super_pnr_rph, ",
        "event_orig_value, event_ref_id, ",
        "event_path, event_type, ",
        "event_flt_seg_rph, event_ref_path)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{auditId,jdbcType=INTEGER}, ",
        "#{requestorId,jdbcType=VARCHAR}, #{channel,jdbcType=VARCHAR}, ",
        "#{version,jdbcType=VARCHAR}, #{opsTimestamp,jdbcType=VARCHAR}, ",
        "#{sourceAddress,jdbcType=VARCHAR}, #{action,jdbcType=VARCHAR}, ",
        "#{agent,jdbcType=VARCHAR}, #{agentUrl,jdbcType=VARCHAR}, ",
        "#{agency,jdbcType=VARCHAR}, #{eventContext,jdbcType=VARCHAR}, ",
        "#{eventId,jdbcType=INTEGER}, #{eventOjSuperPnrRph,jdbcType=VARCHAR}, ",
        "#{eventOrigValue,jdbcType=VARCHAR}, #{eventRefId,jdbcType=VARCHAR}, ",
        "#{eventPath,jdbcType=VARCHAR}, #{eventType,jdbcType=VARCHAR}, ",
        "#{eventFltSegRph,jdbcType=VARCHAR}, #{eventRefPath,jdbcType=VARCHAR})"
    })
    int insert(Spnr_AuditsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Audits
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, audit_id, requestor_id, channel, version, ops_timestamp, source_address, ",
        "`action`, agent, agent_url, agency, event_context, event_id, event_oj_super_pnr_rph, ",
        "event_orig_value, event_ref_id, event_path, event_type, event_flt_seg_rph, event_ref_path",
        "from Spnr_Audits"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.INTEGER),
        @Result(column="requestor_id", property="requestorId", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel", property="channel", jdbcType=JdbcType.VARCHAR),
        @Result(column="version", property="version", jdbcType=JdbcType.VARCHAR),
        @Result(column="ops_timestamp", property="opsTimestamp", jdbcType=JdbcType.VARCHAR),
        @Result(column="source_address", property="sourceAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="action", property="action", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent", property="agent", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent_url", property="agentUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="agency", property="agency", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_context", property="eventContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_id", property="eventId", jdbcType=JdbcType.INTEGER),
        @Result(column="event_oj_super_pnr_rph", property="eventOjSuperPnrRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_orig_value", property="eventOrigValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_ref_id", property="eventRefId", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_path", property="eventPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_type", property="eventType", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_flt_seg_rph", property="eventFltSegRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="event_ref_path", property="eventRefPath", jdbcType=JdbcType.VARCHAR)
    })
    List<Spnr_AuditsPo> selectAll();
}