package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.Spnr_PassengersPo;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Spnr_passengersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_passengers
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Spnr_passengers (super_pnr_id, audit_id, ",
        "customer_id, seq_no, ",
        "age, birth_date, ",
        "oj_super_pnr_rph, passenger_type_code, ",
        "traveler_name, name_prefix, ",
        "telephone, citizen_country_code, ",
        "doc_id, doc_type, ",
        "doc_nationality, doc_expire_date)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{auditId,jdbcType=INTEGER}, ",
        "#{customerId,jdbcType=VARCHAR}, #{seqNo,jdbcType=BIGINT}, ",
        "#{age,jdbcType=VARCHAR}, #{birthDate,jdbcType=VARCHAR}, ",
        "#{ojSuperPnrRph,jdbcType=VARCHAR}, #{passengerTypeCode,jdbcType=VARCHAR}, ",
        "#{travelerName,jdbcType=VARCHAR}, #{namePrefix,jdbcType=VARCHAR}, ",
        "#{telephone,jdbcType=VARCHAR}, #{citizenCountryCode,jdbcType=VARCHAR}, ",
        "#{docId,jdbcType=VARCHAR}, #{docType,jdbcType=INTEGER}, ",
        "#{docNationality,jdbcType=VARCHAR}, #{docExpireDate,jdbcType=VARCHAR})"
    })
    int insert(Spnr_PassengersPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_passengers
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, audit_id, customer_id, seq_no, age, birth_date, oj_super_pnr_rph, ",
        "passenger_type_code, traveler_name, name_prefix, telephone, citizen_country_code, ",
        "doc_id, doc_type, doc_nationality, doc_expire_date",
        "from Spnr_passengers"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.INTEGER),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="seq_no", property="seqNo", jdbcType=JdbcType.BIGINT),
        @Result(column="age", property="age", jdbcType=JdbcType.VARCHAR),
        @Result(column="birth_date", property="birthDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="oj_super_pnr_rph", property="ojSuperPnrRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="passenger_type_code", property="passengerTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="traveler_name", property="travelerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="name_prefix", property="namePrefix", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="citizen_country_code", property="citizenCountryCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_id", property="docId", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_type", property="docType", jdbcType=JdbcType.INTEGER),
        @Result(column="doc_nationality", property="docNationality", jdbcType=JdbcType.VARCHAR),
        @Result(column="doc_expire_date", property="docExpireDate", jdbcType=JdbcType.VARCHAR)
    })
    List<Spnr_PassengersPo> selectAll();
}