package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.entity.Spnr_AssociatedBookingPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Spnr_AssociatedBookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_AssociatedBooking
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Spnr_AssociatedBooking (super_pnr_id, associate_super_pnr_id, ",
        "booking_status, association_type, ",
        "history_id, product_id, ",
        "refund_apply_id, `status`, ",
        "`type`, reshop_id, ",
        "refund_apply_time, rph, ",
        "departure_date, flight_number, ",
        "origin_destination, flight_segment_rph, ",
        "ticketing_status, e_ticket_number, ",
        "traveler_rph, profile_id, ",
        "profile_type)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{associateSuperPnrId,jdbcType=VARCHAR}, ",
        "#{bookingStatus,jdbcType=VARCHAR}, #{associationType,jdbcType=VARCHAR}, ",
        "#{historyId,jdbcType=VARCHAR}, #{productId,jdbcType=VARCHAR}, ",
        "#{refundApplyId,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{reshopId,jdbcType=VARCHAR}, ",
        "#{refundApplyTime,jdbcType=VARCHAR}, #{rph,jdbcType=VARCHAR}, ",
        "#{departureDate,jdbcType=VARCHAR}, #{flightNumber,jdbcType=VARCHAR}, ",
        "#{originDestination,jdbcType=VARCHAR}, #{flightSegmentRph,jdbcType=VARCHAR}, ",
        "#{ticketingStatus,jdbcType=VARCHAR}, #{eTicketNumber,jdbcType=VARCHAR}, ",
        "#{travelerRph,jdbcType=VARCHAR}, #{profileId,jdbcType=VARCHAR}, ",
        "#{profileType,jdbcType=VARCHAR})"
    })
    int insert(Spnr_AssociatedBookingPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_AssociatedBooking
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, associate_super_pnr_id, booking_status, association_type, history_id, ",
        "product_id, refund_apply_id, `status`, `type`, reshop_id, refund_apply_time, ",
        "rph, departure_date, flight_number, origin_destination, flight_segment_rph, ",
        "ticketing_status, e_ticket_number, traveler_rph, profile_id, profile_type",
        "from Spnr_AssociatedBooking"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="associate_super_pnr_id", property="associateSuperPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="booking_status", property="bookingStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="association_type", property="associationType", jdbcType=JdbcType.VARCHAR),
        @Result(column="history_id", property="historyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_apply_id", property="refundApplyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="reshop_id", property="reshopId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_apply_time", property="refundApplyTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="rph", property="rph", jdbcType=JdbcType.VARCHAR),
        @Result(column="departure_date", property="departureDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_number", property="flightNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="origin_destination", property="originDestination", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_rph", property="flightSegmentRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="ticketing_status", property="ticketingStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="e_ticket_number", property="eTicketNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="traveler_rph", property="travelerRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="profile_id", property="profileId", jdbcType=JdbcType.VARCHAR),
        @Result(column="profile_type", property="profileType", jdbcType=JdbcType.VARCHAR)
    })
    List<Spnr_AssociatedBookingPo> selectAll();
}