package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.Spnr_QueuesPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Spnr_QueuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Queues
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Spnr_Queues (super_pnr_id, queue_id, ",
        "active, queue_name, ",
        "`action`, agent, ops_date, ",
        "seq_no, urgent, reason)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{queueId,jdbcType=INTEGER}, ",
        "#{active,jdbcType=VARCHAR}, #{queueName,jdbcType=VARCHAR}, ",
        "#{action,jdbcType=VARCHAR}, #{agent,jdbcType=VARCHAR}, #{opsDate,jdbcType=VARCHAR}, ",
        "#{seqNo,jdbcType=BIGINT}, #{urgent,jdbcType=VARCHAR}, #{reason,jdbcType=VARCHAR})"
    })
    int insert(Spnr_QueuesPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Queues
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, queue_id, active, queue_name, `action`, agent, ops_date, seq_no, ",
        "urgent, reason",
        "from Spnr_Queues"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="queue_id", property="queueId", jdbcType=JdbcType.INTEGER),
        @Result(column="active", property="active", jdbcType=JdbcType.VARCHAR),
        @Result(column="queue_name", property="queueName", jdbcType=JdbcType.VARCHAR),
        @Result(column="action", property="action", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent", property="agent", jdbcType=JdbcType.VARCHAR),
        @Result(column="ops_date", property="opsDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="seq_no", property="seqNo", jdbcType=JdbcType.BIGINT),
        @Result(column="urgent", property="urgent", jdbcType=JdbcType.VARCHAR),
        @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR)
    })
    List<Spnr_QueuesPo> selectAll();
}