package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.Spnr_PricingPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Spnr_PricingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Pricing
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Spnr_Pricing (super_pnr_id, post_amt, ",
        "pre_amt, pre_ori_amt, ",
        "adjustments_amt, amendments_amt, ",
        "total_amt, total_ori_amt)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{postAmt,jdbcType=VARCHAR}, ",
        "#{preAmt,jdbcType=VARCHAR}, #{preOriAmt,jdbcType=VARCHAR}, ",
        "#{adjustmentsAmt,jdbcType=VARCHAR}, #{amendmentsAmt,jdbcType=VARCHAR}, ",
        "#{totalAmt,jdbcType=VARCHAR}, #{totalOriAmt,jdbcType=VARCHAR})"
    })
    int insert(Spnr_PricingPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Pricing
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, post_amt, pre_amt, pre_ori_amt, adjustments_amt, amendments_amt, ",
        "total_amt, total_ori_amt",
        "from Spnr_Pricing"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_amt", property="postAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="pre_amt", property="preAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="pre_ori_amt", property="preOriAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="adjustments_amt", property="adjustmentsAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="amendments_amt", property="amendmentsAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_amt", property="totalAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_ori_amt", property="totalOriAmt", jdbcType=JdbcType.VARCHAR)
    })
    List<Spnr_PricingPo> selectAll();
}