package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.Spnr_PaymentinfoPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Spnr_PaymentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Paymentinfo
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Spnr_Paymentinfo (super_pnr_id, id, ",
        "seq_no, amt, audit_id, ",
        "currency_code, historic, ",
        "history_id, payment_date, ",
        "product_list, `status`, ",
        "transaction_type, pre_pay_ind, ",
        "agent, agent_url, ",
        "agency, payment_form_type, ",
        "ref_code)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR}, ",
        "#{seqNo,jdbcType=BIGINT}, #{amt,jdbcType=DOUBLE}, #{auditId,jdbcType=VARCHAR}, ",
        "#{currencyCode,jdbcType=VARCHAR}, #{historic,jdbcType=VARCHAR}, ",
        "#{historyId,jdbcType=VARCHAR}, #{paymentDate,jdbcType=VARCHAR}, ",
        "#{productList,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{transactionType,jdbcType=VARCHAR}, #{prePayInd,jdbcType=VARCHAR}, ",
        "#{agent,jdbcType=VARCHAR}, #{agentUrl,jdbcType=VARCHAR}, ",
        "#{agency,jdbcType=VARCHAR}, #{paymentFormType,jdbcType=INTEGER}, ",
        "#{refCode,jdbcType=VARCHAR})"
    })
    int insert(Spnr_PaymentinfoPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_Paymentinfo
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, id, seq_no, amt, audit_id, currency_code, historic, history_id, ",
        "payment_date, product_list, `status`, transaction_type, pre_pay_ind, agent, ",
        "agent_url, agency, payment_form_type, ref_code",
        "from Spnr_Paymentinfo"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="seq_no", property="seqNo", jdbcType=JdbcType.BIGINT),
        @Result(column="amt", property="amt", jdbcType=JdbcType.DOUBLE),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="currency_code", property="currencyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="historic", property="historic", jdbcType=JdbcType.VARCHAR),
        @Result(column="history_id", property="historyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_date", property="paymentDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_list", property="productList", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="transaction_type", property="transactionType", jdbcType=JdbcType.VARCHAR),
        @Result(column="pre_pay_ind", property="prePayInd", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent", property="agent", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent_url", property="agentUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="agency", property="agency", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_form_type", property="paymentFormType", jdbcType=JdbcType.INTEGER),
        @Result(column="ref_code", property="refCode", jdbcType=JdbcType.VARCHAR)
    })
    List<Spnr_PaymentinfoPo> selectAll();
}