package com.airchina.datacenter.spnr.sdk.dao.mapper;

import com.airchina.datacenter.spnr.sdk.dao.pojo.Spnr_remarksPo;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface Spnr_remarksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_remarks
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Spnr_remarks (super_pnr_id, active, ",
        "audit_id, code, code_context, ",
        "remark_date, history_rph, ",
        "last_modified, rph, ",
        "seq_no, agent, qualifier_description, ",
        "qualifier_value, flight_segment_rph, ",
        "oj_super_pnr_rph, e_ticket_number, ",
        "passenger_type_code, history_id, ",
        "product_number)",
        "values (#{superPnrId,jdbcType=VARCHAR}, #{active,jdbcType=VARCHAR}, ",
        "#{auditId,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, #{codeContext,jdbcType=VARCHAR}, ",
        "#{remarkDate,jdbcType=VARCHAR}, #{historyRph,jdbcType=VARCHAR}, ",
        "#{lastModified,jdbcType=VARCHAR}, #{rph,jdbcType=VARCHAR}, ",
        "#{seqNo,jdbcType=VARCHAR}, #{agent,jdbcType=VARCHAR}, #{qualifierDescription,jdbcType=VARCHAR}, ",
        "#{qualifierValue,jdbcType=VARCHAR}, #{flightSegmentRph,jdbcType=VARCHAR}, ",
        "#{ojSuperPnrRph,jdbcType=VARCHAR}, #{eTicketNumber,jdbcType=VARCHAR}, ",
        "#{passengerTypeCode,jdbcType=VARCHAR}, #{historyId,jdbcType=VARCHAR}, ",
        "#{productNumber,jdbcType=VARCHAR})"
    })
    int insert(Spnr_remarksPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Spnr_remarks
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "super_pnr_id, active, audit_id, code, code_context, remark_date, history_rph, ",
        "last_modified, rph, seq_no, agent, qualifier_description, qualifier_value, flight_segment_rph, ",
        "oj_super_pnr_rph, e_ticket_number, passenger_type_code, history_id, product_number",
        "from Spnr_remarks"
    })
    @Results({
        @Result(column="super_pnr_id", property="superPnrId", jdbcType=JdbcType.VARCHAR),
        @Result(column="active", property="active", jdbcType=JdbcType.VARCHAR),
        @Result(column="audit_id", property="auditId", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="code_context", property="codeContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark_date", property="remarkDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="history_rph", property="historyRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified", property="lastModified", jdbcType=JdbcType.VARCHAR),
        @Result(column="rph", property="rph", jdbcType=JdbcType.VARCHAR),
        @Result(column="seq_no", property="seqNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent", property="agent", jdbcType=JdbcType.VARCHAR),
        @Result(column="qualifier_description", property="qualifierDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="qualifier_value", property="qualifierValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="flight_segment_rph", property="flightSegmentRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="oj_super_pnr_rph", property="ojSuperPnrRph", jdbcType=JdbcType.VARCHAR),
        @Result(column="e_ticket_number", property="eTicketNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="passenger_type_code", property="passengerTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="history_id", property="historyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_number", property="productNumber", jdbcType=JdbcType.VARCHAR)
    })
    List<Spnr_remarksPo> selectAll();
}